### PR TITLE
feat: added notifications for useful in research

### PR DESCRIPTION
**Pull request by ryanwbass**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Enables useful notifications for research

## Git Issues

Closes # 1611

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

image

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by patrycjapraczyk** [comment]
Heyy @ryanwbass the newly added linter check is failing. Could you please run `yarn format` to fix the formatting? Thanks!

**Comment by patrycjapraczyk** [comment]
Otherwise it looks good to me :)

**Comment by ryanwbass** [comment]
@patrycjapraczyk It seems the unit tests are failing. Not sure why as they passed locally and tests I didn't touch are failing too.

**Comment by patrycjapraczyk** [comment]
Hey @ryanwbass these tests are flaky and are failing with every PR pretty much, so I don't think it's your PR that makes them fail.
You've only changed 3 files in your formatting commit and it still works fine locally for me too.

**Review by patrycjapraczyk — APPROVED** [review]

**Review by patrycjapraczyk — APPROVED** [review]

**Comment by ryanwbass** [comment]
> Hey @ryanwbass these tests are flaky and are failing with every PR pretty much, so I don't think it's your PR that makes them fail. You've only changed 3 files in your formatting commit and it still works fine locally for me too.

@patrycjapraczyk 

Ok, great glad I didn't screw anything up! Is there anything I should do to help or do you guys know what needs to be done?

If there isnt much for me to do, I will look around for another issue to take a look at in the mean time.

**Comment by patrycjapraczyk** [comment]
All good with this PR, I just didn't have the right permissions for it to get merged. Someone should be able to help out with this soon. Thanks for adding this feature!

**Comment by chrismclarke** [comment]
Thanks for the work on this @ryanwbass  and review @patrycjapraczyk 
I'm happy to take a look at the tests tomorrow to clean up and merge

**Comment by chrismclarke** [comment]
Found the issue with the tests, it's the e2e tests not unit (run in cypress via `yarn test` command). These tests can indeed be a bit flaky as we don't have sufficient methods to stub out database interaction, and rely on writing to a server db and querying from it - so there's quite a few hardcoded wait times which are basically our way of hoping that the db has had enough time to update.

I've managed to replace a couple of these db waits with a better lookup that instead checks for UI elements to appear (like comment text) because cypress has methods built-in for waiting for UI which are more flexible than our db waiting. I've also managed to remove and tidy up a few others so I _think_ all should be working.

Thanks for helping to flag this, I'll also add to the maintainer roadmap to try and revisit at some point in the future to see if we can bring the wait times down a bit more with some additional methods (hopefully should be easier in the future when we run the firebase db via a local emulator instead of server).

**Review by chrismclarke — APPROVED** [review]

**Pull request merged**
