### PR TITLE
fix: margin on user and space profiles

### LINKED ISSUE #2036: Contact & Links top margin
Contact and link section is glued to the profile description and would benefit from some 30px top margin

You can check it on any profiles https://community.preciousplastic.com/u/seko-upcycle

Screenshot_2022-12-15_at_18_36_13

Fix: add 30px top margin

Thanks!

### PR DESCRIPTION
**Pull request by asheerrizvi**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Fixes margin for `user.about` prop within member and space profiles

## Git Issues

Closes #2036 

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by davehakkens** [comment]
@thisismattia good for you like this?
you can see the preview here https://onearmy-next--pr2094-fix-2036-nlf8wv4u.web.app/

**Comment by thisismattia** [comment]
Link is broken for me

**Comment by asheerrizvi** [comment]
@thisismattia can you try again? Seems to be working for me.

**Comment by thisismattia** [comment]
Hello @asheerrizvi thanks. Yes it is loading now. 

Was a bit hard to find complete profiles 🧞‍♂️

The issues seem to persist though. have a look at the screenshots below
https://onearmy-next--pr2094-fix-2036-nlf8wv4u.web.app/u/testarh
image


https://onearmy-next--pr2094-fix-2036-nlf8wv4u.web.app/u/drydenwilliams
image

Thanks 🤙

**Review by davehakkens — APPROVED** [review]

**Pull request merged**
