### PR TITLE
fix: support more username variants

### LINKED ISSUE #1980: [bug] @mentions dont work with all characters
**Describe the bug**
Some usernames dont show well when mentioned in the comments.
Below a screenshot of the user [@paul-r-](https://community.projectkamp.com/u/paul-r-) on Project Kamp Instance. (last one)
probably because of the last character` - `

**Screenshots**
afbeelding

**Problem**
This is the problematic line, https://github.com/ONEARMY/community-platform/blob/master/src/stores/common/mentions/index.ts#L48

This is where a test needs to be added that verifies the fix https://github.com/ONEARMY/community-platform/blob/master/src/stores/common/mentions/index.test.ts#L74

**Expected behaviour**
@mentions should accept the same formatting as usernames. (Use the same characters, no uppercase, no spaces)

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Fixes a missing edge case in how we convert userRefence to an `@mention`

## Git Issues

Closes #1980

### CODE REVIEW

**Comment by davehakkens** [comment]
Does it by any chance also make it all lowercase (like the format used for usernames)
For instance this one `@OhKaspian` (on top in the original issue) Also didnt work due to the caps used.
Seems better to force-format any @mention to lowercase only.


afbeelding

**Comment by thisislawatts** [comment]
@davehakkens could you drop a link to the affected comment? I don't think mentions should work unless there is an exact match (lowercase) with an existing user.

**Comment by davehakkens** [comment]
I already changed it back manually to lowercase, now it works.
But here is a newly created one: 
https://dev.onearmy.world/research/support-mention-in-the-key-research-textareas-and-comments
afbeelding

**Comment by davehakkens** [comment]
yeh looks like you can mention anything, hehe
afbeelding

**Comment by thisislawatts** [comment]
Ah interesting, this is slightly separate to the `@mention` implementation. Instead we have a plugins which automatically turns `@aNytHING` into [community.projectkamp.com/u/aNytHING](https://community.projectkamp.com/u/aNytHING) a profile link _without_ verifying that the user exists.

**Comment by thisislawatts** [comment]
Okay fun, have found a fix for this by introducing a zero-width character so that we can have some `@mention` which become links and other `@invalid-username` which do not become links.

Screenshot 2022-10-14 at 09 10 27


> U+2060 Word-Joiner &#8288; representative by no visible character, it prohibits a line break at its position.
https://stackoverflow.com/a/28405917/3292677

**Comment by davehakkens** [comment]
Sounds good. 
But tested the preview, still seem to be able to mention anything? (except `@more`. hehe)
Perhaps it only runs a check on the first one?
afbeelding

**Comment by davehakkens** [comment]
that seems to do the trick here! 
Works good now

**Review by davehakkens — APPROVED** [review]

**Pull request merged**
