### PR TITLE
feat: add email hero banner

### PR DESCRIPTION
**Pull request by benfurber**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] New feature (non-breaking change which adds functionality)

## Description

Adds an email graphic to the sign-up success page. 

## Screenshots/Videos

Screenshot 2024-07-09 at 17 16 15

### CODE REVIEW

**Comment by benfurber** [comment]
@davehakkens How do you feel about the copy. 

I thought @dalibormrska's suggestion (below) could be jazzed up a bit.
Screenshot 2024-07-09 at 17 18 49

**Comment by davehakkens** [comment]
yeh sure works for me. But i think the mockup has a few other interesting things to implement (like removing that top blue bar) but could also do that later on

**Comment by benfurber** [comment]
@davehakkens Sure! Makes sense to do in this PR.

How's this:

Screenshot 2024-07-10 at 09 10 31
Screenshot 2024-07-10 at 09 10 36
Screenshot 2024-07-10 at 09 10 51

**Comment by benfurber** [comment]
Chatted with @davehakkens on discord. There's some changes to make to the CTA on the sign-up success page, but will pick-up in a future conversation.

**Pull request merged**
