### PR TITLE
chore: migrate notifications to component

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Developer experience (improves developer workflows for contributing to the project)

## Screenshots/Videos

Screenshot 2022-06-15 at 22 45 52

Screenshot 2022-06-15 at 22 46 04

Screenshot 2022-06-15 at 22 46 01

Screenshot 2022-06-15 at 22 46 00Screenshot 2022-06-15 at 22 45 58

### CODE REVIEW

**Comment by laianbraum** [comment]
Hey @thisislawatts , which tool did you use to capture these screenshots? They look amazing!

**Comment by thisislawatts** [comment]
Hey @laianbraum, I am using MacOS built in screengrab mechanism. https://support.apple.com/en-us/HT201361

**Comment by chrismclarke** [comment]
@laianbraum  - also if you mean more generally the individual UI component pages, they're generated using [storybook](https://storybook.js.org/) and available if you follow the `Component Storybook` link from the documentation: https://onearmy.github.io/community-platform

Or run locally via `yarn workspace oa-components start`

**Review by chrismclarke — APPROVED** [review]
Impressive code reduction even with all the additional stories!
Nice to have more examples of complex stories too.

The code all looks good to me, some nice general tidying too which is great. I ran the notifications tests locally to take a look at the outputs and all looked good to me (couldn't figure out how to send myself notifications for testing locally otherwise), so I'd say good to go!

**Comment by davehakkens** [comment]
Small detail.
There just to be a scroll in here so the pop-up doesnt get to long.
This seems to be not there anymore, creating a lonng list
afbeelding

**Pull request merged**
