### PR TITLE
Prefactor: Email notifications

### PR DESCRIPTION
**Pull request by adrianduke**
PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Developer experience (improves developer workflows for contributing to the project)

## Description

1. Adds `notification_settings` to `IUser`
2. Refactors notification store `userNotificationsStore ` out of user store
3. Adds new state for notifications `notified`
4. Marks all notifications in notification list as `notified` when opened

See: https://docs.google.com/document/d/1dC_sKVLcSCggFftPFRcB1F5wt4ABQDtmVOX0oQGdXUw/edit#heading=h.crtcwv7i47zb

__Note: I can't base off of #1900 so theres duplicate diff related to docker stuff, will be fixed with a rebase__

### CODE REVIEW

**Comment by thisislawatts** [comment]
@adrianduke, have you had a chance to review https://github.com/ONEARMY/community-platform/pull/1789? I think it would be preferable to merge that work first and think it will impact the prefactor work you've started here.

**Comment by thisislawatts** [comment]
In an effort to unblock the work on this branch, I've taken the @mention capability without notifications out of #1789 and created a new PR #1930 to see that change merged.

This means we can move forward on the prefactoring work here and look to reference #1789 on the logic of how to handle `@mention` notifications.

**Comment by davehakkens** [comment]
Let me know @adrianduke if you are still able to wrap this one up.
Otherwise we will either have to start from scratch or try to built on top of this.

**Review by chrismclarke — APPROVED** [review]
Many thanks for this @adrianduke 
I've resolved the conflicts and added some additional unit tests so I think this should (finally) be good to go!

**Pull request merged**
