### PR TITLE
fix: form values for files reset after reupload click

### LINKED ISSUE #2313: [bug] Re-upload files not deleting original files from Howto when editing
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Howto you have created
2. Click edit
3. Upload a file if there isn't one --> then save (optional step)
4. Click Re-upload files
5. Click Publish
6. See error: file still in howto and when going to edit howto it is also still there

**Expected behaviour**
Pressing the reupload files button should delete the files from the form and not keep them store

**Screenshots**

https://user-images.githubusercontent.com/652368/235863900-8fe49bc1-80a8-4ff0-87d9-b31a3b8813df.mov

### PR DESCRIPTION
**Pull request by AlfonsoGhislieri**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Resets the files in the form to an empty array when the re-upload button is clicked, causing problems in #2280 as pointed out by @davehakkens 

This is done using the formApi in react final form (https://final-form.org/docs/final-form/types/FormApi)

## Git Issues

Closes #2313

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by davehakkens** [comment]
Yes. Works now. thankkss

**Comment by thisislawatts** [comment]
@AlfonsoGhislieri is there a test we can introduce that captures this bug fix?

**Comment by AlfonsoGhislieri** [comment]
> @AlfonsoGhislieri is there a test we can introduce that captures this bug fix?

Yes, now that #2280 has been merged I reckon I can add a few tests using the new test file!

**Comment by AlfonsoGhislieri** [comment]
@thisislawatts added as a unit test in [07e9736](https://github.com/ONEARMY/community-platform/pull/2314/commits/07e9736c7b3c78b81a6fe4a59e04f5cce092b709) to build off the existing checks for the invalid file warnings.

**Review by thisislawatts — APPROVED** [review]

**Pull request merged**
