### PR TITLE
Feat/admin users

### PR DESCRIPTION
**Pull request by Kiebert**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

- Merge master to this branch;
- Activated route 'Users';
- The table height was not responsive to the window height (check the screenshot);
- Update color of the 'User name' in grid;
- Filter when activated has now a border line;

## Git Issues
https://github.com/ONEARMY/community-platform/issues/1508

### CODE REVIEW

**Review by thisislawatts — CHANGES_REQUESTED** [review]
@Kiebert what is the intent here?
Are you attempting to merge your changes into `master` or the branch associated with the open PR: https://github.com/ONEARMY/community-platform/pull/1837

**Comment by thisislawatts** [comment]
(edited) Rather than targeting the stale branch, I think it would be better using the work there as a base and raising a PR from your branch into master. That should make a PR which is easier to review. At the moment we've got 246 commits and 219 files in this PR. We will then close out the original PR.

**Comment by Kiebert** [comment]
@thisislawatts Yeah. Makes sense.
I will change the target.

**Review by chrismclarke — APPROVED** [review]
Thanks for tidying this up and getting it back on the radar @Kiebert 🙌

Nice to make the table responsive, I've tweaked the values slightly because we won't have to worry about the space lost to header when running on production and added a minHeight in case on mobile, but otherwise nice to see this finally merged in!

**Comment by davehakkens** [comment]
awesome! :)

**Pull request merged**
