### PR TITLE
chore: update questions ui

### PR DESCRIPTION
**Pull request by jaykayudo**
## PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix (fixes an issue)
- [ ] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the new behavior?

_Describe the new behaviour_
_If useful, provide screenshot or capture to highlight main changes_
Screenshot from 2024-10-09 16-16-06

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Git Issues

Closes https://github.com/ONEARMY/community-platform/issues/3900

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by davehakkens** [comment]
Thanks for the fast PR!
Looks good, two minor things
1. Could you make the borders correct, currently the white box overrides the corner.
image

2. Could we change `padding: 5px` to `padding: 10px 15 px;`(to decrease the space inbetween questions)
image

**Comment by jaykayudo** [comment]
@davehakkens Done

**Comment by benfurber** [comment]
Fantastic, thank you @jaykayudo!

**Comment by benfurber** [comment]
@all-contributors add @jaykayudo for code

**Pull request merged**
