### PR TITLE
Allow notification icon to dim on click

### LINKED ISSUE #1654: [feature request] Notification lightbulb behaviour
Hey team,

I am a little confused with the behaviour of the notification icon. Currently icon only turn grey when notifications are cleared.
Screenshot 2022-05-06 at 16 08 43

Currently:
- When icon is yellow, user clicks on the icon and sees notifications
- Icon stays yellow until notifications are cleared
- As a returning user you might be tricked into thinking you have new notifications (as icon is yellow) but in fact no new notification is there. 

Proposed behavior:
- Default icon is grey
- New notification  > icon becomes yellow
- User clicks on icon and sees notification
- Icon turn grey
- Icon stays grey until new notification
- If users clears notifications, notifications get cleared, icon stays grey

Hope it makes sense

### PR DESCRIPTION
**Pull request by tedspare**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Latest `master` branch merged

PR Type

- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description

- Dims the notification icon (to gray colour) on click, regardless of previous state
- Allows user to dismiss orange icon without clearing all unread notifications
- Implements behaviour described by @mattia-io in #1654, common to other platforms
- Does not address @thisislawatts's accessibility concerns in #1654

_First PR here, open to feedback! Eg. not sure if `useState` and `useEffect` are common patterns in this project._

## Git Issues

Closes #1654

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

### CODE REVIEW

**Comment by davehakkens** [comment]
thanks for making the PR, much appreciated!

Just double checking the behaviour implemented.
1. When testing I noticed the Icon gets grey when clicking on it (awesome)
2. However when refreshing or visitng the webpage again, in a new tab, the icon is back to orange.
So if you would read all your notifications (grey) and come back later, without notification the icon is active again (orange)

The second function is not added right?

**Comment by tedspare** [comment]
> thanks for making the PR @tedspare, much appreciated!
> 
> Just double checking the behaviour implemented.
> 
> 1. When testing I noticed the Icon gets grey when clicking on it (awesome)
> 2. However when refreshing or visitng the webpage again, in a new tab, the icon is back to orange.
>    So if you would read all your notifications (grey) and come back later, without notification the icon is active again (orange)
> 
> The second function is not added right?

Thanks for your prompt review, @davehakkens!

The second case is not yet addressed, correct. I've thought of a few approaches:
1. subscribing to the notification count in **Header.tsx** and setting `areThereNotifications = true` only when it increases (this would always make the icon grey at first load),
2. calling `markAllNotificationsRead()` on clicking an orange notification icon (this may cause some notifications to be wrongly dismissed),
3. adding a user property `hasUnseenNotifications` and storing it in the DB (maybe overkill), or
4. keeping the current behaviour, to remind the user of unread notifications in each new tab.

What do you think? Thanks for your work.

**Comment by thisislawatts** [comment]
@davehakkens would appreciate your perspective on @tedspare's comments above. I am not convinced that the bolt should be left in a dimmed state _unless_ someone has triggered the **Clear notifications** button

Screenshot 2022-05-28 at 13 41 54

**Comment by davehakkens** [comment]
>  I am not convinced that the bolt should be left in a dimmed state _unless_ someone has triggered the **Clear notifications** button
> 
You mean like the current/orignal behaviour @thisislawatts? Only if user "clears notification" > icon becomes grey.
So not what @mattia-io proposes in the issue https://github.com/ONEARMY/community-platform/issues/1654

**Comment by thisislawatts** [comment]
That's right, I do not believe that opening the notifications pop-up can give us enough confidence that the user has read all of the messages contained within. 

I would expect interaction with a notification item to be the best indication that someone has read it. This could either be done by:

1. Clicking through to the linked item
1. Marking the individual Item as read
1. Clearing all notifications

**Comment by mattia-io** [comment]
Hey guys thanks for picking this up. 

In my experience notification icons have one goal (might be missing other use cases): 
- notify user of new (unseen) notification(s) from last time user checked their notifications

The proposed behavior above would add an additional goal:
- signify users whether or not they have clicked **all** notifications
 
In my experience notification icons purpose  **is not** to make sure users click through **all** notification, as some users might be checking new notifications and not clicking on them all. Specifically in our case, people might not want/need to click on a "useful" notification as clicking doesn't bring any further info or knowledge. 

Might be good to align on them underlying goal of the notification icons on the community platform?
1. Notify users when there is new notification(s) from last time notifications were checked (or last time notification icon was clicked).
2. Notify users when they have clicked all notification.

Out of curiosity would you guys have links to websites where notifications work as the above proposed behavior? 

Much love

**Comment by thisislawatts** [comment]
You're right @mattia-io, I think it would be good to understand the intended goal of the notifications feature. There are two quite distinct notification types here;
* _Actionable items:_ such as new comment (and incoming `@mentioned`) where I guess we want to reduce friction so it's easy for folks to use the Platform for discussions and jump between conversations. In which case a central Inbox style listing of all notifications.
* _Unactionable items:_ a piece of content you authored was voted Useful, maybe a notification for each file download? The aim here for content creators to feel that their contributions are making an impact. 

In terms of sites which present a persistent notification, requiring interaction with the message before it is dismissed:

**GitHub:**  

Screenshot 2022-05-28 at 20 02 03

**Discord:**  

Screenshot 2022-05-28 at 20 02 35

**Gmail:**  

Screenshot 2022-05-28 at 20 01 30

**Comment by tedspare** [comment]
Thanks for spotting the pain point, @mattia-io.

@thisislawatts I like the approach of drawing on behaviour from other, popular platforms. GitHub, Discord, Gmail, and also Reddit and Slack require "clearing all" before dimming the icon.

On the other hand, Facebook and Twitter dim their icons after a single click. It seems there's no right answer.

Three approaches:
1. Is @mattia-io's sentiment common among users? Is there a way to hold user interviews to verify?
1. An A/B test. Is user retention a goal on the platform? If so, is there telemetry to support an A/B test? Alternatively, try the new behaviour and see if anyone complains.
2. Keep the bolt lit for _actionable_ items only. The best [resource](https://bootcamp.uxdesign.cc/should-the-notification-counter-disappear-once-a-user-see-the-notification-or-not-26a15f62441c) I could find says high-frequency, persistent notifications will drive users to mute them entirely.

What do you think? How are decisions made in this community? I picked up a random issue and hope not to create more work 😅

**Comment by davehakkens** [comment]
I would say for now we postpone this feature since there isn't a pressing need from the community.
Seems like we need to get it more clear first what we want. And if we are going one layer deeper into improving notifications we should design it with email notifications in mind (a feature that would come in the near future) which might effect this behaviour. 

Sorry for not having this issue very clear @tedspare. But thanks a lot for putting the work in and opening the boxes. I did notice you usually work on (github) notifications! Let me know if you are interested to help figuring out email-notifications for the platform. Or feel free to take on another, more straightforward, issue like this one: https://github.com/ONEARMY/community-platform/issues/1619

**Comment by tedspare** [comment]
@davehakkens all good! Live and learn. Think I'll start with #1619 to get up to speed.

Thanks for your work in the community. Exciting project.

**Pull request closed without merging**
