### PR TITLE
feat: add generic map component

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Unit and e2e tests for the changes that have been added (for bug fixes / features) (some)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix (fixes an issue)
- [ ] Feature (adds functionality)
- [x] Refactoring (no functional changes)

## What is the current behavior?

The main map and the map generated for settings, were seperate instances of the map, which could lead to different behaviour.

## What is the new behavior?

Both now call the same map in the component library. Also fixes not loading from the map api locally.

### CODE REVIEW

**Comment by benfurber** [comment]
Manually tested locally and on preview branch. I don't believe this creates any user changes so will merge in once checks pass.

**Comment by mariojsnunes** [comment]
instead of moving the css to packages/components/src/Map/index.css, which might cause issues with the remix migration. Could we have that class inline?

**Comment by benfurber** [comment]
@mariojsnunes Would happily move the tiny contents of `packages/components/src/Map/index.css` to line, but the main leaflet css file is 600+ lines. With remix/vite I really should be able to import a css file!

**Comment by mariojsnunes** [comment]
Let's not make the migration harder than it needs to be... for now we know how to import from the main app.
To import from a package, we need to invest more time hacking around to figure it out.

**Comment by benfurber** [comment]
@mariojsnunes Good point.

**Pull request merged**
