### PR TITLE
feat: add profile tags to all final space profiles

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix (fixes an issue)
- [x] Feature (adds functionality)
- [x] CI related changes

## What is the current behavior?

* Workspaces for PP have custom db field

## What is the new behavior?

* Workspaces for PP, community points for PP and spaces for FF all have profile tags now
* Everything should be ready for PK spaces once added
* Drops (nearly all) code related to workspace sub type
* Updates design of profile tags field to something more align with the existing fields
* Changes the position of the profile tags field 
* Shows tags on new map pins

Screenshot 2024-10-30 at 16 59 17

Screenshot 2024-10-31 at 17 09 23

## Does this PR introduce a breaking change?

- [x] No, but requires a DB update

## Git Issues

Part of #3908

### CODE REVIEW

**Review by mariojsnunes — APPROVED** [review]

**Comment by davehakkens** [comment]
is the preview branch working?

**Comment by iSCJT** [comment]
@davehakkens They're set to stop themselves after a couple of minutes of inactivity. Keeps our fly.io bill down but means when someone opens the link it invariably needs to boot from cold and it takes a while ~30 seconds.

I've just tested this link and it is working. When it gets to the white screen / "loads", hit refresh and it should be there.

**Comment by benfurber** [comment]
I've got a data update ready to go on retool, thus could then merge this in but retool isn't connecting to firebase on my connection for some reason.

**Comment by benfurber** [comment]
Migration done. Merging.

**Pull request merged**
