### PR TITLE
Adding Google Analytics

### PR DESCRIPTION
**Pull request by drydenwilliams**
I decided to make a component to do all the analytics instead of using the Analytics store. It still uses `react-ga`. But I found the store to coupled to the frontend and backend and was confusing. So keep it simple and let the frontend and the `<Analytics />` component take care of the FE.

### CODE REVIEW

**Comment by chrismclarke** [comment]
Also, just realised that we still don't have anyone working on the privacy policy and opt-in/out GDPR requirements so we shouldn't merge into production site until that's done.

**Comment by drydenwilliams** [comment]
Do we have a ticket for the privacy and GDPR work?

**Comment by BenGamma** [comment]
> Do we have a ticket for the privacy and GDPR work?

I'm effraid not. I guess it would be a little banner in the bottom or top of the page mentionning that by browsing our site, they accept the tracking. Need to double check with the GDPR policy and with design team.
I will flag it to the team but for now we can consider it postpone to next release.

**Comment by chrismclarke** [comment]
Turns out we already do! #722 and #619 both talk about this. I better close/merge these into a single issue to link to this PR also. @BenGamma , I can't see the issue you mentioned but if you point me in the right direction I can add it also

**Comment by chrismclarke** [comment]
Ok, collated in #864

**Comment by chrismclarke** [comment]
I think we should be about ready to go, although did you ever make the minor changes requested from the review @drydenwilliams ?

> I see you've only enabled for production, although it would be good to test on the dev site also. instead of checking `SITE === 'production' && GOOGLE_ANALYTICS_CONFIG.trackingCode` just check whether the code exists as this is only populated on staging and production branches.
> 
> Couple additional minor nits:
> 
> * can we decide a consistent naming convention for the tracking code/id. Google uses both terms but i think we should just pick one. Let me know if you want me to change the env variable to `TRACKING_CODE` or whether you will change to trackingId
> * call the component `GoogleAnalytics` in case we ever decide to change providers or offer multiple

**Comment by chrismclarke** [comment]
Actually not to worry, I see they're there, approved

**Pull request merged**
