### PR TITLE
fix: flex layout for mobiles

### LINKED ISSUE #1851: [bug] How-to step layout
Issue:
How-to step layout is hard to read. 

Link:
https://community.preciousplastic.com/how-to/injection-machine-automatic-connection-upgrade-

Screenshots:
Screenshot_20220724-174722_Brave

Proposal:
A simple flex-direction: column could fix it + column reverse to have image first

css-s86h58 {
  flex-direction: column;
  flex-direction: column-reverse;
}

As a plus I would also reduce the height of the image to 300px (currently 450px)
.css-18eyh6c {
  height: 300px;
}

Screenshot 2022-07-24 at 17 56 01

### PR DESCRIPTION
**Pull request by asheerrizvi**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Fixes an issue with flex layout on mobile devices.

## Git Issues

Closes #1851 

## Screenshots/Videos

image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by thisislawatts** [comment]
@asheerrizvi thanks for raising this PR ✨ It looks like there is a merge conflict here. Would you be able to take a look at resolving this issue? Happy to help out if you'd prefer. All you need to do is grant my user @thisislawatts write permissions on your fork of the project.

**Comment by asheerrizvi** [comment]
@thisislawatts sure I'll have a look.

**Comment by asheerrizvi** [comment]
@thisislawatts so it looks like the ImageGallery component has been moved to `packages`. I am assuming my changes should go there now instead of `src/components/ImageGallery/ImageGallery.tsx`?

**Comment by asheerrizvi** [comment]
@thisislawatts done, have a question though. We moved `ThumbImage` inside the component in #1817 (I have done something similar with `ImageWithPointer` in this PR). I am assuming this was done in order to use `useTheme` but wont this lead to new instances of these components on each render? Maybe we should pass these values as props?

**Comment by thisislawatts** [comment]
Thanks for the follow up @asheerrizvi, would you be able to help me understand how to validate the statement: "wont this lead to new instances of these components on each render"?

**Comment by asheerrizvi** [comment]
@thisislawatts so every time `ImageGallery` re-renders (eg due to prop or state changes) React will run the code defined inside the `ImageGallery` function. In case of `ThumbImage` React will declare and initialise it again on each render. Earlier it was declared outside the `ImageGallery` function which means that it would've been declared and initialised only once and would've remained stable throughout every re-render. For this simple component this isn't a performance concern. However, I just wanted to let you know that there's a better way of doing this by moving these styled components outside the `ImageGallery` function.

**Comment by thisislawatts** [comment]
@asheerrizvi, thanks for taking the time to explain how this pattern may negatively impact performance. I agree that in this instance it is unlikely to introduce too much off an overhead to negatively affect user experience. 

Would you be up for refactoring this component to split the styled component definitions out of the `ImageGallery` function? I will merge this PR and then this can be addressed separately.

**Review by thisislawatts — APPROVED** [review]

**Comment by asheerrizvi** [comment]
@thisislawatts yep sounds good to me. Should I open an issue for this?

**Pull request merged**
