### PR TITLE
[draft] chore: add eslint import sort

### PR DESCRIPTION
**Pull request by iSCJT**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

Adds eslint config for sorting imports + initial changes after a format run

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by thisislawatts** [comment]
@iSCJT it looks like this PR needs some formatting applied. I wonder if there could be a conflict between the eslint and prettier rules?

**Comment by iSCJT** [comment]
Yea I was going to sort that and a couple of others this afternoon but only just got back to kamp. Will get it resolved in the morning.

**Comment by thisislawatts** [comment]
@iSCJT sounds great, no urgency from my side :)

**Comment by AlfonsoGhislieri** [comment]
Seems quite a little time has passed and this has become stale, what do you want to do here @iSCJT?

**Comment by iSCJT** [comment]
Thanks for prod @AlfonsoGhislieri 👍

I've closed it. Will come back to it another time.

**Pull request closed without merging**
