### PR TITLE
Linked username in comments to user profile

### PR DESCRIPTION
**Pull request by patrycjapraczyk**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

PR Type

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Linked username in comments to user profile.

## Git Issues

Closes [#1157](https://github.com/ONEARMY/community-platform/issues/1157)

## Screenshots/Videos

https://user-images.githubusercontent.com/35103888/121354255-ff124c80-c92e-11eb-9563-8d4160801445.mp4

### CODE REVIEW

**Comment by davehakkens** [comment]
thanks!
Just curious, did you manage to test this? Since Comments should be only visible to "beta tester" roles

**Comment by patrycjapraczyk** [comment]
Yeap, I tested it by running the code pulled from the repo locally (as shown in the video). You could see the comments on "dev" site.

image

**Review by chrismclarke — APPROVED** [review]
Looks good to me.

Yeah, we really should make it easier to test the different user roles. By default when running on local I think the user has full admin role rights, but definitely not obvious. Glad you were able to figure it out though!

**Comment by davehakkens** [comment]
Hi @patrycjapraczyk 

Thanks for helping with this pull request. There was a €20 bounty on the issue!
Let me know if you want to collect this.

Alternatively, we also have a lot more [new issues](https://github.com/ONEARMY/community-platform/issues) with bounties, in case you want to help out more. We could use your development power 💪

**Comment by patrycjapraczyk** [comment]
> Hi @patrycjapraczyk
> 
> Thanks for helping with this pull request. There was a €20 bounty on the issue!
> Let me know if you want to collect this.
> 
> Alternatively, we also have a lot more [new issues](https://github.com/ONEARMY/community-platform/issues) with bounties, in case you want to help out more. We could use your development power

Hi there, sure if this is an option. Could you please tell me how I could collect it? You could me the info through praczyk.patrycja@gmail.com if you'd like. I'm also going to have a look at your other issues and see if there's anywhere else I could help!

**Pull request merged**
