### PR TITLE
feat: show user howto & research on member / space profile

### LINKED ISSUE #2381: [feature request] show how-to and research created by or collaborated on by a user on their profile page
**Is your feature request related to a problem? Please describe.**
Nice to have feature [raised on discord](https://discord.com/channels/586676777334865928/1110629403857268766).

**Describe the solution you'd like**
Show how-to and research articles created by or collaborated on underneath a users profile information.  Possibly a simplified list rather than the full cards that exist on the current how-to / research listings. Maybe an additional tag if it is an item they are a collaborator on or possibly a separate section for collaborations.

**Describe alternatives you've considered**
Manually scrolling through lists to find items user has created or collaborated on.

**Additional context**

### PR DESCRIPTION
**Pull request by iSCJT**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

- Adds user created how to and research to member / space profile
- Deprecates user stats object
- Makes how-to count on member / space profile a simple count of approved how-tos

## Git Issues

Closes #2381 #2383 

Showing collaborated research to be spun out to new issue.

## Screenshots/Videos

image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by davehakkens** [comment]
Really cool PR! 💪
Could we release the overview on the bottom to `beta-tester` role only for now?
This gives us some time to test on live and iterate on the design.

Did notice a few times where the useful doesnt add up to the total useful count
14 vs 7
afbeelding


18 vs 15
afbeelding

**Comment by iSCJT** [comment]
@davehakkens the numbers didn't add up because the collaborated research wasn't included in the list, I've added that now.  Tried a few different ways of trying to indicate it was collaborated rather than created but couldn't get anything to look 'nice' so it's just one list.

Also updated so the section only appears for beta-testers.

**Comment by thisislawatts** [comment]
@iSCJT can we add either some Cypress or Jest tests which verify the behaviour and also validate how the changes behave in the event of a failure. For example, the request to fetch all howTo documents failing.

**Comment by iSCJT** [comment]
> @iSCJT can we add either some Cypress or Jest tests which verify the behaviour and also validate how the changes behave in the event of a failure. For example, the request to fetch all howTo documents failing.

@thisislawatts I've added a separate issue for adding the tests and will come back to later.  Think it will be a relatively complex one to add for all scenarios so would prefer to spend my time trying to get more issues fixed ahead of next week.  Also as it's beta tester only functionality and only a very small group of us likely to be working on it I think it's quite low value / nice to have.

**Review by thisislawatts — APPROVED** [review]

**Pull request merged**
