### PR TITLE
feat: adds global one army footer

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [ ] - Latest `master` branch merged
- [X] - PR title descriptive (can be used in release notes)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Work in progress, this component should not be visible on all pages, as it doesn't work with:
* The Map
* The Academy content

Some work here needs to be done so that it correctly renders depending on the page URL. It does that at the moment only after a **full page load** , see how it will not be added to [the homepage](https://onearmy-next--pr1249-feat-adds-global-one-wjhffkfz.web.app/academy/intro.html) but if you load an [individual howto](https://onearmy-next--pr1249-feat-adds-global-one-wjhffkfz.web.app/how-to/recycle-plastic-waste-into-3d-printing-filament) it will be at the bottom. You may need to refresh the page to force the conditional render logic to trigger. 

I believe the higher level App wrapper introduced as part of https://github.com/ONEARMY/community-platform/pull/1242, may be helpful here. So consider this blocked for the time being.

### CODE REVIEW

**Comment by davehakkens** [comment]
looks nice! Happy to merge if the "App wrapper" thing is cleared up

**Comment by davehakkens** [comment]
Suggestion for the footer. Instead of
`Precious Plastic is a project by One Army.`
We say something along these lines:
`Community is build by One Army. Help to code it.`
link to this site: https://platform.onearmy.earth/

Might get some developers to help out :)

**Comment by thisislawatts** [comment]
- Introduce the additional copy
- Left aligned the copy
- Increased vertical height so that when a user scrolls all the way to the bottom the Discord button appears vertically centered

🚧 Next step, figure out layout on small screens

**Comment by davehakkens** [comment]
Looks good.
1. Ideally it's linked to platform.onearmy.earth. (not directly Github) This gives a bit more background information about the development and the option to support the project financially.
2. Mobile seems almost good except the github logo is floating around weirdly, could just hide that on mobile and release it?

**Comment by thisislawatts** [comment]
@davehakkens, updated to:
1. Updated the link to go through to platform.onearmy.earth
2. Removed the GitHub logo entirely, it makes less sense once we are no longer linking through to it.

**Review by davehakkens — APPROVED** [review]
Looking good on mobile :)

**Pull request merged**
