### PR TITLE
fix: revert to nodejs18 runtime

### PR DESCRIPTION
**Pull request by AlfonsoGhislieri**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

1e6a58d5c changed the runtime for firebase to node 20, but this is causing errors when trying to deploy functions locally in order to test them: `Error: Cannot deploy function with runtime nodejs20`

This is an issue seeing as the emulator is currently blocked, making it impossible to test the functions.

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by thisislawatts** [comment]
@AlfonsoGhislieri could you share the command you are running and the full output? It would be great to get a more information on this.

**Comment by AlfonsoGhislieri** [comment]
Of course @thisislawatts, 
I ran `firebase deploy --only functions`

```
webpack 5.75.0 compiled with 6 warnings in 5244 ms
✔  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled

Error: Cannot deploy function with runtime nodejs20
```

**Comment by thisislawatts** [comment]
Can you run `which firebase` and `firebase --version` ?

**Comment by AlfonsoGhislieri** [comment]
which firebase `/usr/local/bin/firebase`
firebase --version `11.24.0`

**Comment by thisislawatts** [comment]
So it looks like you're using an older version of firetools which was installed globally. Could you try updating this to match the version used by the project, I think we are at 12.7.0

**Comment by AlfonsoGhislieri** [comment]
Aha well I have no idea how I ended up doing that.. But that fixed it thanks! I did think it was weir d node20 wasn’t supported..

**Pull request closed without merging**
