### PR TITLE
feat: add errors to research

### PR DESCRIPTION
**Pull request by benfurber**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Building off #2717, this adds an errors component to the research forms. It also adds a full e2e test for research updates, which was missing from the suite.

## Git Issues

Part of #2684.

### CODE REVIEW

**Review by evakill — COMMENTED** [review]
this one is looking good too! no comments, needs a rebase

**Comment by benfurber** [comment]
As there's relevent changes in #2720 that impact this. I'm waiting for that the merged in first, then I'll update this branch.

**Comment by benfurber** [comment]
@evakill Ready again.

**Review by evakill — APPROVED** [review]
looks great!

**Pull request merged**
