### PR TITLE
feat: add useful button to research module

### LINKED ISSUE #1405: Add useful button to Research module
### Description

We have a useful button in our [how-to](https://community.preciousplastic.com/how-to) module. We need the same button in our research module ( will be used extensively in Project Kamp setup next season🔥)

### Page related

Will be used in :
- PR related to useful button https://github.com/ONEARMY/community-platform/pull/1097
- See the [research module](https://community.preciousplastic.com/research) 

### Mockup

Add useful to research

### PR DESCRIPTION
**Pull request by chrismclarke**
Co-authored-by: mmortar

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Review Notes
Currently testing is quite tricky because it relies on aggregations that are not run on the preview site (side issue), and the local emulators still need work to properly link up different testing profiles (various draft prs open).

But see screenshots below as check that database is at least updating something (!). I've also wrapped in a `beta-tester` flag to make it easier to test once deployed to staging site and production

## Description

Rebase of  #1432 to fix linting

## Git Issues

Closes #1405

## Screenshots/Videos

image

image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Review by davehakkens — APPROVED** [review]
lets test on dev!

**Comment by thisislawatts** [comment]
@chrismclarke are there any lower level tests we could introduce here to validate that the behaviour works as expected?

**Comment by chrismclarke** [comment]
@thisislawatts 
> are there any lower level tests we could introduce here to validate that the behaviour works as expected?

Not really, the total number should come from aggregations so we could mock that but then really we are just testing whether when passed a number the value shows or not. I guess it could catch undefined case but I don't think achieves a huge amount (we already handled that same case with the howto useful button which the code was copied from).

Otherwise we could try test whether clicking the button updates the user object correctly, but that would involve mocking out the user store (and possibly firebase db) which again would be a fair amount of effort and not sure the reward. Would definitely be good to build out all these test areas, but I don't think this PR would be the best place to start as it's fairly time-sensitive and just a bit of a pain to work with generally

**Pull request merged**
