### PR TITLE
add link to login from comments

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

PR Type
- [x] New feature (non-breaking change which adds functionality)

## Description

- Turn the `login` text to a link to the sign-in page

## Git Issues

Closes

## Screenshots/Videos
**Before:**
image

**After:**
image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by davehakkens** [comment]
nice addition! Styling looks a bit weird in that screenshot though. But I guess that's another issue

**Review by davehakkens — APPROVED** [review]
neat

**Comment by chrismclarke** [comment]
Oh yeah, the arrow before just doesn't line up at all (designed more for when the comment box is there) and the link is a bit ugly. 
Updated and merging

image

**Comment by davehakkens** [comment]
perfect!

**Pull request merged**
