### PR TITLE
[feature request] Optimize mobile layout How-to and Research #2735

### LINKED ISSUE #2735: [feature request] Optimize mobile layout How-to and Research
### Description
It's getting busy in the headers and it could use some optimisation on mobile. As mention in issue #2191
This issue is a follow up from https://github.com/ONEARMY/community-platform/issues/2734

We want to add hide some more detailed information by default that can be shown on a click using the "accordion" style

### Page related

Will be used in :
[Research](https://dev.onearmy.world/research/more-draft-checking)
[How-to](https://dev.onearmy.world/how-to/test-title)

### Mockup
Example for the research module, same principle applies to how-to's
afbeelding

### Note
It contains the new stats from #2734 but also moves the contributors on mobile.

### PR DESCRIPTION
**Pull request by denyilm**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

- Add a button to ResearchDescription.tsx that will be visible in mobile layout
- Add a boolean state called showMoreOptions
- Add a function called handleMoreOptions that changes the showMoreOptions state on click

## Git Issues

Closes #2735

## Screenshots/Videos

Default State
image

Clicked State
image

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by davehakkens** [comment]
thanks for submitting a PR @denyilm!
However its a bit different from the original design made in the issue. https://github.com/ONEARMY/community-platform/issues/2735
Would you be able to implement it in that way? 
And while working on it it would be good to change the PR status to `Draft`

Note: keep in mind the stats/data in the issue comes from this PR https://github.com/ONEARMY/community-platform/pull/2737 which isnt merged yet)

**Comment by denyilm** [comment]
@davehakkens thanks for your comment! I can now see that the stat items (views, following, useful, comments..) should be listed at the bottom in the accordion style, I totally misunderstood the request. I will try to update it according to the original design in the issue #2735.

**Comment by davehakkens** [comment]
hey @denyilm sorry for the slow reply, was waiting for this PR to merge https://github.com/ONEARMY/community-platform/pull/2911

Now that is done and all the stats are shown. Would you be able to finish this PR?

**Comment by denyilm** [comment]
Hi @davehakkens, I'd be happy to do it, you can assign it to me :)

**Comment by davehakkens** [comment]
For some reason i'm not able to assingn you. This happend a few more times in the past but don't know why...

**Comment by thisislawatts** [comment]
@davehakkens, I think it is an anti spam measure. @denyilm, I think if you comment on the original issue we will be able to assign it to you.

**Comment by denyilm** [comment]
I've just commented on the original issue @davehakkens @thisislawatts

**Comment by davehakkens** [comment]
How is this going @denyilm, are you able to finish it up?

**Comment by denyilm** [comment]
Hello @davehakkens! I am planning to complete it tomorrow.

**Comment by denyilm** [comment]
Hello @davehakkens! Since this pull request the app got updated a lot, so instead of keep committing on this I sent a new request, I hope its fine! Here is the new pull request: 

https://github.com/ONEARMY/community-platform/pull/2952

**Comment by thisislawatts** [comment]
Closing as https://github.com/ONEARMY/community-platform/pull/2952 is intended to replace

**Pull request closed without merging**
