### PR TITLE
[Developer Experience] Update md-style-guide.md (Admontitions)

### PR DESCRIPTION
**Pull request by MIfoodie**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type
## Description

Updates md-style-guide.md to provide better information on admontitions and when they are used.

## Git Issues

This PR does not close any issues.

### CODE REVIEW

**Review by chrismclarke — CHANGES_REQUESTED** [review]
Thanks for adding the clarifications @MIfoodie 

In order to help us create automated release notes we impose a system of [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) messages, which means all commits need to be prefixed in specific ways depending on what they are aiming to address.

So in order to pass the check you will need to change the message on your previous commit to be something like `docs: update md-style-guide.md` instead. If you already know how to change a pushed commit message (via git rebase) then please feel free to change on this branch directly, otherwise an easier option might be to just close this pr and open a new one with the correct git message.

At the same time our automated [check](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/3577/workflows/4b87fd6f-157e-44c8-9862-027b14ee7637/jobs/22856) also picked up a few typos with the word `admonition`, so if you get a chance it would be good to correct these too

**Comment by MIfoodie** [comment]
Oh ok!

**Comment by MIfoodie** [comment]
Oh ok!

**Comment by MIfoodie** [comment]
Going to re-open this one when I fixed the problems :)

**Pull request closed without merging**
