### PR TITLE
feat: change research updates to use id for anchor

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix (fixes an issue)
- [x] Feature (adds functionality)

## What is the current behavior?

Research update anchors don't go to the correct update (if at all).

## What is the new behavior?

1. By using the update ids as the primary way to anchor, it ensures there's no issues with _deleted or unpublished updates meaning a count of the array will mean things link up wrong.
2. Also exposed this feature to users with a lovely new icon (pending) which copies the update URL to their clipboard. 
3. Ensures the scrolling to the anchor happens more gracefully than before.
4. Tidies up some slightly nuts styling.

Screenshot 2024-07-23 at 12 28 10

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Kind of. Notifications will have the old anchors, but they weren't linking up right anyway...

### CODE REVIEW

**Comment by benfurber** [comment]
Just waiting on a new icon.

**Comment by davehakkens** [comment]
Nice function.

But I get this when copy/paste the link in a new tab
image


url: `onearmy-next--pr3791-benfurber-feat-add-a-qgel6hb4.web.app/research/more-draft-checking#update_rdGrfmQwKCz5mkHC53Mt`

Preview-site problem?

**Comment by davehakkens** [comment]
And what happens when you click old notification links? -the breaking change

- Does it not scroll to the right update anchor (no issue)
- Or does it give a page error and not showing anything at all (this is more troublesome)

**Comment by benfurber** [comment]
@davehakkens I'm fairly confident that's preview site weirdness, I'll triple check locally though.

Option a on the breaking change, much like this url just shared [just now on the discord bot](https://community.projectkamp.com/research/how-can-we-protect-our-outdoor-wooden-structures-long-term#update_10)...

**Comment by benfurber** [comment]
@davehakkens Deffo working locally. When I release it I'll check on prod too.
https://github.com/user-attachments/assets/692c5285-835b-4624-a155-96f7f9719a58

**Pull request merged**
