### PR TITLE
chore: move classes into their own files

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [X] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Developer experience (improves developer workflows for contributing to the project)

## Description

* Adds an eslint rule to check for this behaviour
* Switch to interface for `AbstractDBClient` which better reflects
its usage
* Refactor AbstractDatabase to align with Abstract class conventions

### CODE REVIEW

**Review by chrismclarke — COMMENTED** [review]
Just checking, do you think anything requires testing or specific review?

I think if I understand correctly this PR replaces what was a an interface masquerading as a class (with accompanying .d.ts definition) for an actual abstract class?

I think at the time of creation the reason for doing so was just to copy how firebase managed code itself, but I expect a lot has changed since then (e.g. firebase now supporting tree shaking which I'm sure has involved a bunch of refactoring). But it makes pretty intuitive sense to me to use abstract classes for abstract classes.

So if there's any actual code you want me to look at/test let me know, otherwise I think it's mostly just refactoring so feel free to go ahead and merge if you've already tested and it is working.

**Comment by thisislawatts** [comment]
@chrismclarke, this should be a non functional change. I _think_ that interfaces may not have been available in Typescript when this code was originally introduced.

My expectation is that tests protect us entirely. Aside from a human validating that, a single class per file is preferable and eyeballing the file moves I defer to the automated tests to protect us.

**Comment by chrismclarke** [comment]
> @chrismclarke, this should be a non functional change. I think that interfaces may not have been available in Typescript when this code was originally introduced.

That's what I assumed. I'm pretty sure there were other reasons (alongside copying firebase maybe to do with not being able to re-implement private methods or similar), but these would have been purely functional (i.e. not able to do something wanted) and so given that this code works totally happy with the change. 

> My expectation is that tests protect us entirely. Aside from a human validating that, a single class per file is preferable and eyeballing the file moves I defer to the automated tests to protect us.

I've definitely used multiple classes in files before, sometimes I'd say very lazily/not great practice (e.g. when using class-based components if wanting to keep a few smaller ones together, so good to encourage the change), and other times for some reasonable level of utility (e.g. subroutines in a larger workflow) but never in such a way that separating causes harm (and there's always disable flags if last resort). 

So yeah, happy to go ahead with this. It's a shame we're using a json eslintrc file as might be nice to link to PR (so in future it's more clear to see it's a considered change and not just default that can be disabled when next seen as _inconvenient_)... unless it's one of those magic jsons where you can?

Agreed on the automated tests - one nice thing at least about tests that link up with an actual production-style environment.

**Review by chrismclarke — APPROVED** [review]

**Pull request merged**
