### PR TITLE
feat(platform): add loader to research page

### LINKED ISSUE #2808: [feature request] Loader or information about fetching research data in Research page
**Is your feature request related to a problem? Please describe.**
When I opened Research page I saw info about no results. After 1 second, results list jumped in. But first information was misleading.

**Describe the solution you'd like**
Loader. Or information about active fetching process.
Ideally, cache the list, because it's fetching after every page opening.

**Video with reproducing the problem**
[scrnli_26-09-2023_15-15-48.webm](https://github.com/ONEARMY/community-platform/assets/15144546/803ad93d-9156-49f0-8632-13adb1ed131f)

### PR DESCRIPTION
**Pull request by ajotka**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

I added loader in research page for initial fetching. 
My solution also can be ported to other stores which have `this.allDocs$.subscribe((docs: IResearch.ItemDB[])` method for fetching data.

## Git Issues

Closes #2808

## Screenshots/Videos

image

### CODE REVIEW

**Comment by thisislawatts** [comment]
Thanks @ajotka, can you introduce a test which verifies the loader is visible when the page renders and before the content has loaded?

**Comment by ajotka** [comment]
@thisislawatts Hello, sorry for replying so late, I was seriously ill.
I tried to write tests, but the test file for research page & store is copy-paste from "HowTo". So the tests for this page have to be written from scratch and cover more than just my changes. 
Can we therefore merge the loader and create a separate issue for tests?

**Comment by thisislawatts** [comment]
Sure thing @ajotka, I am aiming to get to a place where changes will not be merged unless there are tests but appreciate we are still missing some infrastructure to make that a low cost exercise.

**Comment by thisislawatts** [comment]
Can you raise the issue flagging the missing tests?

**Review by thisislawatts — APPROVED** [review]

**Comment by thisislawatts** [comment]
@all-contributors add @ajotka for code

**Pull request merged**
