### PR TITLE
fix: member type shows member profile

### PR DESCRIPTION
**Pull request by Kiebert**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Description

A 'Workspace' type should also show the 'SpaceProfile'. 

## Git Issues

https://github.com/ONEARMY/community-platform/issues/1506

### CODE REVIEW

**Comment by thisislawatts** [comment]
@Kiebert can we introduce a breaking test that recreates the bug before adding a fix? This will protect us against future regressions. At the moment the majority of our tests are in Cypress and this would be the specific suite to extend:
https://github.com/ONEARMY/community-platform/blob/master/packages/cypress/src/integration/profile.spec.ts

Let me know if you've got any issues writing/running the tests.

**Comment by Kiebert** [comment]
> @Kiebert can we introduce a breaking test that recreates the bug before adding a fix? This will protect us against future regressions. 
Hi @thisislawatts. You mean to recreate the scenario that the user hasn't choosen a profile type yet?

**Comment by thisislawatts** [comment]
Yep, that's right @Kiebert that would ensure we have the desired behaviour under test.

**Comment by Kiebert** [comment]
Ok. I will write a test for it.
I will make time for that this week.
If you want the profile to react as in the original state, you can merge the code changes of the PR her above.

**Review by davehakkens — APPROVED** [review]
Will merge for now so the profile looks correct.
But would be cool to see that test added!

**Comment by Kiebert** [comment]
@davehakkens @thisislawatts I wrote this simple profileType test, you can view it in this PR: https://github.com/ONEARMY/community-platform/pull/1979
Could you please check if it is sufficient?

**Pull request merged**
