### PR TITLE
Feat: replace display of tags by categories

### LINKED ISSUE #3337: Feat: Replace display of tags by categories
### Description

We want to replace the tags by categories on how-to's and research.
- Categories functionality is better intergrated in filters
- Categories will be used more with breadcrumbs coming https://github.com/ONEARMY/community-platform/pull/3333
- Safer for displaying without breaking design since you can only select one category but multiple tags

### Page related

Will be used in :
[Research overview](https://dev.onearmy.world/research)
[How-to Overview](https://dev.onearmy.world/how-to)
### Mockup
how-tos
research

### PR DESCRIPTION
**Pull request by saile515**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

This PR replaces the tag display with a category display on research and how-to. It also fixes some tests that broke due to the change.
*Note: I don't know what the story does, but I saw that every other component had it, so I tried to replicate it as best as possible.*

## Git Issues

Closes #3337 

## Screenshots/Videos

image

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by benfurber** [comment]
This is great @saile515, thank you. What's here is really good. 

Feedback
1. Please add categories to the questions list page. (`src/pages/Question/QuestionListing`)

Also, to add to the scope:
1. Please add (not replace) the display on individual research, how-to and questions
3. The ordering is a bit of a mess on mobile (see below) can you please have it so that's on a new line below the title. I think this can be done just with responsive flex stuff.

**Comment by saile515** [comment]
@benfurber The changes should be implemented now. For some reason, the how-to items doesn't load for me, so I designed that blindly. The questions categories also doesn't seem to work at all, not even filtering, but I think that is unrelated to this PR.

**Comment by benfurber** [comment]
Thanks for the extra work @saile515. 

1. I've added some how-tos now (more than one magically somehow). You should be able to see yourself too? Do how-tos not load for you locally? I can see there is a display issue:
Screenshot 2024-03-13 at 17 24 41

2. Weirdly I'm not see all of your recent changes on the preview branch. Maybe need to rebase master into your branch?

3. Something I could have thought on my first view. Do think the text feels a little squashed? Maybe push the padding to 0.5 or 1 vertically and 1.5 horizontally. What do you think?

**Comment by saile515** [comment]
I have rebased and increased the padding locally. Rebasing did fix the issue with the how-tos not showing up. However, the display issue is unrelated to this PR. Here is an image from the dev site showing the same issue: 
image

I have no idea how to fix the issue, since the entire page seems to use absolute positioning with lots of pixel calculations for some reason.

**Comment by benfurber** [comment]
> I have rebased and increased the padding locally. Rebasing did fix the issue with the how-tos not showing up. However, the display issue is unrelated to this PR. Here is an image from the dev site showing the same issue: image
> 
> I have no idea how to fix the issue, since the entire page seems to use absolute positioning with lots of pixel calculations for some reason.

@saile515 If you look on [prod](https://community.preciousplastic.com/how-to) thankfully no titles are three lines so we can continue to ~ignore~ accept the tech debt.

**Comment by saile515** [comment]
@benfurber it is still an issue with two lines now, since the category display is larger than the tags. Also, do you know what is causing the unit test to fail?

**Comment by benfurber** [comment]
Another one in! Thank you @saile515! Looks like you have some time/availablity at the moment?

**Comment by saile515** [comment]
@benfurber I got some time to spare while I finish my last year of upper secondary school. I don't know if I could make any strict time commitments to the project, although I should have at least a few hours a week.

**Pull request merged**
