### PR TITLE
Move discord webhook logic to seperate file

### PR DESCRIPTION
**Pull request by goratt12**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description
** tested  and working **
Refactored the notification logic by keeping only the Discord notification handling in `firebase-discord.ts` file. The `notifyPinAccepted` and `notifyHowToAccepted` functions have been separated into their respective files, `mapPinUpdates/index.ts` and `howtoUpdates/index.ts`.

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by goratt12** [comment]
Encountered Github automatic secret push block, resolved it by these steps:
https://docs.github.com/en/code-security/secret-scanning/working-with-push-protection#bypassing-push-protection-when-working-with-the-command-line
When merging my PR the maintainer will probably have to do the same to allow the secret to enter the code base

**Comment by mariojsnunes** [comment]
there are some conflicts. (probably due to the vite migration, sorry!)

**Comment by benfurber** [comment]
Seen the error @goratt12? Looks relevant.

**Comment by goratt12** [comment]
> Seen the error @goratt12? Looks relevant.

Yeah I don't know how I missed it, fixed it now.
The unit tests that are failing now are not related, Possibly flaky

**Pull request closed without merging**
