### PR TITLE
feat: add username to profiles

### LINKED ISSUE #1407: Add username to profiles
### Description

As we start using comments more, people will see usernames more. However, on the profile you can't see a username. Only the display name. This has been confusing to users.  We want to change three things.
1. Remove the label. This is redundant with the badge next to it.
2. Add username to the place of the label
3. Change the location of the country flag from `displayname` to `username` to stay consitent. 

The changes apply to all "space" profiles. (community point, machine shop, workspace, collection points)
### Page related

Will be used in :

- [Related page (profiles) ](https://community.preciousplastic.com/u/precious-plastic)

### Mockup

username to profile

### PR DESCRIPTION
**Pull request by jojudre**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Latest `master` branch merged

PR Type

- [ ] New feature (non-breaking change which adds functionality)

## Description

Add username to profiles

## Git Issues

Closes #1407

## Screenshots/Videos

Снимок экрана 2022-03-30 в 19 01 31

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by davehakkens** [comment]
Nice one! Only thing missing is that this should also be applied on our [member profiles](https://onearmy-next--pr1577-userprofile-2u8cqwt3.web.app/u/thisislawatts), they have a different design/template.
(You can find them on the map under "want to get started")

The flag should go up to the username.




afbeelding

**Comment by thisislawatts** [comment]
Always good to see a PR like this which removes more than it adds! Great work ✨ 

A screengrab showing number of lines added, compared to lines removed. There are more lines removed.

I will not approve yet as I think it would be good to incorporate the feedback from @davehakkens, the file you want is called `MemberProfile.tsx`.

In the meantime I recommend reviewing [our commit style guide](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide) to help resolve the failing **Lint Commits** check.

**Comment by jojudre** [comment]
Снимок экрана 2022-03-30 в 23 10 00

**Review by davehakkens — APPROVED** [review]

**Pull request merged**
