### PR TITLE
Add research update webhook

### PR DESCRIPTION
**Pull request by pizzaisdavid**
## PR Type
feature

## Description
Make message in Discord when a new Research Update is created.

## Git Issues
Doesn't close, but for: https://github.com/ONEARMY/community-platform/issues/3533

## Screenshots/Videos
demo:
https://www.youtube.com/watch?v=LD1Rj0OrHDg

### CODE REVIEW

**Comment by davehakkens** [comment]
very nice! :)

How will this go for Precious Plastic VS Project Kamp?
Since I think atm Project Kamp doesnt have a Discord webhook installed yet

**Comment by pizzaisdavid** [comment]
> How will this go for Precious Plastic VS Project Kamp?
> Since I think atm Project Kamp doesnt have a Discord webhook installed yet

Good question.

After reviewing the codebase, I think it would not work but not crash the backend generally.

I've added some checks, so if there is no Discord webhook, then to just exit that part safely. I am not totally sure what the config looks like on Project Kamp, so I had to guess (checking for empty string, null, and undefined.)

Summary: should work fine.

**Comment by pizzaisdavid** [comment]
changes applied, successfully rebased

**Review by benfurber — CHANGES_REQUESTED** [review]
Very easy to read, thank you @pizzaisdavid. Any test coverage we should add around this?

**Comment by pizzaisdavid** [comment]
@benfurber unfortunately there is no preexisting infrastructure for testing webhooks in an automated way, so... uh.. nope!

Anyone can feel free to add tests to any webhook and then I will copy what they did for this one here. 😉

**Review by benfurber — APPROVED** [review]

**Comment by pizzaisdavid** [comment]
> Perhaps a different issues for after this

I have made an issue: 
https://github.com/ONEARMY/community-platform/issues/3694

**Comment by pizzaisdavid** [comment]
I looked at the failed test, it seems to be un-related.

Siri, re-run the tests please.

**Comment by mariojsnunes** [comment]
the failing test looks like the same bug as https://github.com/ONEARMY/community-platform/issues/3691. Could be solved on another PR

**Pull request merged**
