### PR TITLE
fix: content updating when userImage changes

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix (fixes an issue)

## What is the current behavior?

Comments not updating `creatorImage` when `userImage` is updated.

https://github.com/user-attachments/assets/356e96b6-8ada-4b4a-bf77-5a67a732c149

## What is the new behavior?

Comments updating `creatorImage` when `userImage` is updated.

https://github.com/user-attachments/assets/25f60506-f5ff-49ef-a0e4-21afa9f3d3a7

### CODE REVIEW

**Comment by benfurber** [comment]
@mariojsnunes I'm not back working until Monday PM, if this looks fine to you can you please release it?

**Comment by benfurber** [comment]
(No point adding a test branch as this is entirely a functions change and they don't update with the preview branches...)

**Comment by benfurber** [comment]
Oh wait, found extra cases to fix.

**Comment by benfurber** [comment]
Done. Now also clears comment image if user deletes their image.

**Review by mariojsnunes — APPROVED** [review]

**Pull request merged**
