### PR TITLE
fix: reduced how-to heading padding for mobile

### LINKED ISSUE #1849: [mobile] Reduce header padding
Issue:
The hero header has a big margin that hides the first how-to, ux would be improved if the first how-to was more shown inviting the user to scroll. 

Link:
https://community.preciousplastic.com/how-to

Screenshots:
Screenshot_20220724-172748_Brave

Proposal:
Reduce top and bottom padding to 50px

css:
.css-144acuz {
  padding-top: 50px;
  padding-bottom: 50px;
}

Screenshot 2022-07-24 at 17 33 01

### PR DESCRIPTION
**Pull request by asheerrizvi**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Fixes padding for heading within how-to.

## Git Issues

Closes #1849 

## Screenshots/Videos

image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by thisismattia** [comment]
thanks for this @asheerrizvi will design review it asap

**Review by chrismclarke — APPROVED** [review]

**Comment by asheerrizvi** [comment]
@thisismattia some checks are failing here for some reason. :/

**Comment by thisislawatts** [comment]
@all-contributors add @asheerrizvi for code

**Comment by thisismattia** [comment]
Looks gooood ♡
thanks @asheerrizvi

**Comment by asheerrizvi** [comment]
👍

**Pull request merged**
