### PR TITLE
feat: change email functionality

### PR DESCRIPTION
**Pull request by jojudre**
PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

added email change functionality

## Git Issues

#1414 

## Screenshots/Videos

https://user-images.githubusercontent.com/42969746/151713218-7ab6c025-f288-4ce0-bc91-bdd0624cada9.mp4

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by davehakkens** [comment]
wauw fast. Looks nice! But I see some tests are failing  🤔

**Comment by jojudre** [comment]
@davehakkens hmm thats wierd because locally all tests passed

**Comment by thisislawatts** [comment]
Hey @jojudre and @davehakkens, the e2e tests do not automatically run against forks of the repository. This is a protective measure to prevent unneccessary usage on CircleCI/Cypress. I agree though that this messaging is a bit confusing. 

Tests are all green, great (and fast) work @jojudre!

**Review by thisislawatts — APPROVED** [review]

**Pull request merged**
