### PR TITLE
fix(emulators): seed data and dep updates

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description
Try to address issues recently identified with emulators ([discord thread](https://discord.com/channels/586676777334865928/1162919611696685146/1162919678117683241)), namely
- Update emulator seed data
- Update emulator project name to include `demo-prefix` (Relates to https://github.com/firebase/firebase-tools/issues/5170)
- Create new emulator build with updated dependencies
- Minor fixes for type issues
- Various additional fixes as noted in [comment below](https://github.com/ONEARMY/community-platform/pull/2971#issuecomment-1804944261)

## Review Notes
Should test if recent issues with emulators fixed. 

E.g. build docker image locally
```sh
yarn workspace oa-emulators-docker build
```
Run docker image
```sh
yarn start:emulated:docker 
```

Once merged the image should also be built and deployed to dockerhub via the CI actions (and available for other developers to use without local build, pulling from dockerhub, shortly after)

## Git Issues

Closes #

## Screenshots/Videos

Docker output should reflect updated version
image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by thisislawatts** [comment]
@chrismclarke What is the process you used to "Update emulator seed data"?

**Comment by thisislawatts** [comment]
Looks like we may have a circular dependency [here](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/6852/workflows/60d9dd49-d953-4f8d-acae-aa870403e60e/jobs/55831), the Cloud Functions tests are failing because they can not load the docker image. If I understand correctly that will only be available _after_ this has been merged.
```
Starting container onearmyplatform/community-platform-emulator:pp-2023-10-29
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading onearmyplatform/community-platform-emulator:pp-2023-10-29

Error response from daemon: manifest for onearmyplatform/community-platform-emulator:pp-2023-10-29 not found: manifest unknown: manifest unknown
```

**Comment by chrismclarke** [comment]
> @chrismclarke What is the process you used to "Update emulator seed data"?

There's currently automation that backs up the data daily. I can actually see multiple sources of backups (guessing some duplication or tidying to be done), but the one I used is the data that also gets populated to the associated firebase project storage bucket
image

Downloaded that data using gcloud cli and then dropped the corresponding folder into the `seed_data` folder. As part of the preparation script it automatically generates the corresponding tar archive. Then just a case of updating references and gitignore and good to go.

There used to be a github action to automate the process, but became unmaintained and stopped working. 

Taking a quick look at the data now I can see the newer backups include quite a lot more data that might be sensitive to include in the emulator (namely pending/processed emails which include addresses) - so I think will need to create a new manual export that excludes. There's some (outdated) docs on manually generating exports at https://docs.platform.onearmy.earth/Backend%20Development/firestore-backup, although will want to avoid the _entire database_ option and provide a list of collections to include instead

**Comment by chrismclarke** [comment]
> Looks like we may have a circular dependency [here](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/6852/workflows/60d9dd49-d953-4f8d-acae-aa870403e60e/jobs/55831), the Cloud Functions tests are failing because they can not load the docker image. If I understand correctly that will only be available _after_ this has been merged.
> 
> ```
> Starting container onearmyplatform/community-platform-emulator:pp-2023-10-29
> Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
>   image cache not found on this host, downloading onearmyplatform/community-platform-emulator:pp-2023-10-29
> 
> Error response from daemon: manifest for onearmyplatform/community-platform-emulator:pp-2023-10-29 not found: manifest unknown: manifest unknown
> ```

Yep, although if the image/system is working as expected it's possible to manually push the image to dockerhub from local and rerun which should then be able to load the tagged image

**Comment by thisislawatts** [comment]
> Taking a quick look at the data now I can see the newer backups include quite a lot more data that might be sensitive to include in the emulator (namely pending/processed emails which include addresses) - so I think will need to create a new manual export that excludes. 

I totally agree, is the updated seed_data required here to fix the Emulator problems or is it something we can address in a future PR?

**Comment by chrismclarke** [comment]
I've created a custom manual export without the emails collection and pushed the image to dockerhub. I'd recommend once tested working to merge this PR with a squash commit to clear the previous seed data commit.

Longer term we'll probably want to create a triggered function that calls the existing db backup function but passes a subset of collections required for emulators, and ideally submit to dockerhub on a more routine basis.
But hopefully now should at least make things workable again

Now just looking at tests which still seem to be failing (pull successful but can't find firebase command which is strange)

**Comment by evakill** [comment]
hey @chrismclarke ! i was going to look into 
>  fix test invalid doc path for function us-central1-emailNotifications-sendHowToSubmissionEmail
unless you're already working on a fix?

**Comment by chrismclarke** [comment]
> hey @chrismclarke ! i was going to look into
> 
> > fix test invalid doc path for function us-central1-emailNotifications-sendHowToSubmissionEmail
> 
> unless you're already working on a fix?

hey @evakill - I took a quick look at feels super weird, looks like when trying to get the howto _createdby user its passing an empty string but as far as I can tell all test and emulator data includes the uid so doesn't make full sense and getting a workflow for debug is a pain (you basically have to recreate the circle-ci workflow, loading the docker image, checking out the entire platform codebase into the container, copying files across, installing deps etc.)... I kinda gave up (workaround would be just adding more logs and waiting to see what's evaluated on circle-ci, which is also super tedious)

Although I'm also wondering if these errors are actually an issue (they're triggered as side-effects from tests, so a better workaround might even be to disable triggers when not explicitly required by tests). I'm not sure if these failures are what fails the test overall or not, or whether due to a separate issue that the firebase emulators don't exit gracefully

Working on the emulator exit issue right now, so if I can get that working will hopefully be able to know more about the importance of the other issue (but feel free to investigate if interested)

**Comment by chrismclarke** [comment]
Ok, looks like firebase emulators at least exiting now, so guessing the issue is either the notification document path one or there's also errors coming as function triggers try to send notification to slack/discord webhooks but these are fake urls... so again not sure how really we are meant to handle this or why they've only just started failing
```
 Error: getaddrinfo ENOTFOUND fake_slack_webhook.local
>      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
>    errno: -3008,
>    code: 'ENOTFOUND',
>    syscall: 'getaddrinfo',
>    hostname: 'fake_slack_webhook.local'
>  }
```
I'm guessing options here might be either adding a function running on the emulator endpoint (`functions\src\emulator\index.ts`) just to accept the webhook requests and use localhost api endpoint, wrap requests in some sort of try-catch, or find a way to disable the trigger during tests

In either case happy to hand over for now in case anyone else can figure any of this out

**Comment by chrismclarke** [comment]
@thisislawatts 
functions tests are now passing with updates noted in comment above, you'll also see a few extra ci changes from #2994 (including ci runner size increase). I'm not sure what needs to be done to get the codecov tests passing, but otherwise I think this should be about good to go

**Review by evakill — APPROVED** [review]
LGTM! thanks for the work on this @chrismclarke 🙌

**Comment by thisislawatts** [comment]
Thanks @chrismclarke and @evakill 🥳

**Pull request merged**
