### PR TITLE
fix: adjust margin and width of elements in HowToComments

### LINKED ISSUE #2118: Align how-to CTA component
At the bottom of how-to page the CTA component is misaligned. See screenshot below.

https://community.preciousplastic.com/how-to/coaster-from-coffee-waste

Screenshot_2023-02-22_at_14_16_43

Would be great to simply align it with comments module. 
Thanks!

### PR DESCRIPTION
**Pull request by ronaldpaek**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Adjust the margin and width of elements in the HowToComments component so they are consistent 

## Git Issues 

Closes #2118

## Screenshots/Videos
ezgif com-video-to-gif (6)

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by ronaldpaek** [comment]
Not sure why one test failed.

**Comment by davehakkens** [comment]
thanks for the PR!
The chrome test can be a bit buggy. Let me re-run to see if it works 🤞

**Comment by davehakkens** [comment]
@thisismattia give it a test (on a few devices) to see if its good now:
 https://onearmy-next--pr2120-fix-align-how-to-cta-75oi7nel.web.app

**Comment by thisismattia** [comment]
@davehakkens could you make some comments on the first how-to? Don't have logins to dev site

**Comment by ronaldpaek** [comment]
@thisismattia sorry I made a gif showing the changes, I was able to just use an email an created an account on the dev server as well.

**Comment by thisislawatts** [comment]
@thisismattia you can use this link to test it out with:
https://onearmy-next--pr2120-fix-align-how-to-cta-75oi7nel.web.app/how-to/testing-comments

**Review by thisislawatts — APPROVED** [review]

**Comment by thisismattia** [comment]
Yes perfect!
Thanks guys ♥️

**Pull request merged**
