### PR TITLE
feat: update reply to comment button text and icon

### LINKED ISSUE #3652: [feature request] ButtonShowReplies minor adjustments
> This ticket is part of series of 7 tickets concluding a design task focusing on improving design and usability of comments feature. Here you can find the [Figma file](https://www.figma.com/board/GfQPMs7PyC7jbkymDTco2D/CP-%2F-Nested-Comments-Improvements?node-id=0-1&t=7sgMA4ZPYXAMb03A-1) for more context.

### **3/7 - ButtonShowReplies minor adjustments**
---

**Is your feature request related to a problem? Please describe.**

1. First and major problem is the visual dominance of the button. This is talked about in a separate ticket #3655 and is therefore not in the scope of these adjustments.

2. The second issue is the text that makes the button too long, since it includes the username.

3. The third issue is with the arrow icon not being centred and being too thick

image

**Describe the solution you'd like**
_Must Have:_ Make it say “Show X replies” and “Hide X replies” if it has replies.
If it doesn’t have replies it can say “Reply” and then “Hide replies”

_Should Have:_ Adjustment to the icon, consider making it into a chevron, making it centered and the stroke thickness balanced.

image

Additionally, there is the proposal to have the button without the border, but it is in the scope of another ticket, mentioned also above #3655 . Below is how it should look after removing the border as well, also with the hover state.

image

**Describe alternatives you've considered**
The issue of creating less dominant variant of the button component is prominent on several places throughout the platform and is discussed in this ticket #3655 . Could there be a common solution for creating a button variant without border?

**Additional context**
See the milestone

### PR DESCRIPTION
**Pull request by onim-at**
## PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix (fixes an issue)
- [ ] Feature (adds functionality)
- [X] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?
The reply button text is too long and the icon is too thick
<details> 

image
</details>

## What is the new behavior?
The reply button text is updated to not include the username and the icon has been changed to a chevron
<details> 

image
</details>

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Git Issues

Closes #3652 

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by onim-at** [comment]
Hello @dalibormrska! I've one concern about the changes, I saw that there's already a chevron icon used in the mobile version of the question page

image

I didn't reuse it for the reply button since it seemed a bit too thick, however it is a bit strange to have two different chevron. Is this ok for you? Should we use only one of the two?

**Comment by davehakkens** [comment]
Nice!

What do you @onim-at @dalibormrska think about giving the button a margin from the left on desktop?
Specially if comments gets long its looks a bit strange that the button is aligned with the avatar, feels more logical to align with the comment.
image

So like this
margin

**Comment by dalibormrska** [comment]
Heyyy! Yeah, I agree with you @onim-at, that we would want the chevrons to be consistent, and I also see the issue with that one being too thick. I would propose a chevron that would fit both cases. What do you think?

image

**12x12px New Chevron SVG**
```<svg width="12" height="13" viewBox="0 0 12 13" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M2 4.04639L6 8.04639L10 4.04639" stroke="black" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

**16x16px New Chevron SVG**
```<svg width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M2.66406 5.37988L7.9974 10.7132L13.3307 5.37988" stroke="black" stroke-width="1.77778" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

**Comment by dalibormrska** [comment]
@davehakkens makes sense as well!

**Comment by onim-at** [comment]
@davehakkens I'd propose to have the margin left only on the desktop view, otherwise it would be too cramped on mobile. What do you think?

**Comment by dalibormrska** [comment]
@onim-at Fixed, try to copy the SVGs now. It was a formatting issue with the codeblock in the comment.

**Comment by davehakkens** [comment]
> @davehakkens I'd propose to have the margin left only on the desktop view, otherwise it would be too cramped on mobile. What do you think?

agree. thanks for thinking about mobile!

**Comment by benfurber** [comment]
Awesome, thanks for this @onim-at. Looks like [you've got one test failing still](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/10248/workflows/2f5aca20-6a8a-4700-93f1-ecb35fccff37/jobs/91627). Not 100% sure yeah from the error message but maybe because you're expecting it exactly which might not work due to the icon in the span.

**Review by benfurber — CHANGES_REQUESTED** [review]
Awesome, thanks for this @onim-at. Looks like [you've got one test failing still](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/10248/workflows/2f5aca20-6a8a-4700-93f1-ecb35fccff37/jobs/91627). Not 100% sure yeah from the error message but maybe because you're expecting it exactly which might not work due to the icon in the span.

**Comment by onim-at** [comment]
thanks for the tip @benfurber! I'll try to update the PR next week along with the requested changes

**Comment by davehakkens** [comment]
Are you able to wrap this one up @onim-at? Would be a nice one to merge :)

**Comment by onim-at** [comment]
hello @benfurber, I'm still struggling with that unit test, I've tried the following solutions, most of them posted in https://github.com/testing-library/dom-testing-library/issues/410, but none of them worked
```js

const replyButton = screen.getByText('Show 2 replies')

const replyButton = screen.getByText('Show 2 replies', { exact: false })

// check inner text
const replyButton = screen.getByText((content, node) => {
  const hasText = (node: Element | null) =>
    node?.textContent === 'Show 2 replies'
  console.log(node?.textContent)
  const nodeHasText = hasText(node)
  const childrenDontHaveText = Array.from(node?.children).every(
    (child) => !hasText(child),
  )

  return nodeHasText && childrenDontHaveText
})

const replyButton = screen.getByText(/.*Show 2 replies.*/)
```

I've also tried to remove the button icon but the issue still occur. Do you have any suggestion?

@davehakkens I've updated the PR with the new icon, it's missing the comment alignment and the unit test fix
If it's urgent we can merge it once the unit test is passing and I'll create a new PR for the alignment :)

**Comment by benfurber** [comment]
@onim-at I had a play. I think it was just because the act wrapper wasn't right. My change seems to have everything passing now.

**Pull request merged**
