### PR TITLE
feat: most relevant sort option only present if search value entered

### PR DESCRIPTION
**Pull request by iSCJT**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Most relevant sort option only present if search value entered.  If search value deleted then it will return to the sort option chosen before the search value was entered.

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by iSCJT** [comment]
@davehakkens this should address your concerns.

**Comment by davehakkens** [comment]
thanks for the quick "fix"
This seems more logical to me.
But still not sure if I fully get:

Because if you search "upload images" it shows 3 results
afbeelding

From here I could sort those results on "most useful"
afbeelding

Or "Most updates"
afbeelding

That works pretty neat. Dont see how/when you would use the "Most relevant"
That said happy to merge it. Just trying to make sure I understand it for future use.

**Comment by iSCJT** [comment]
Go onto precious plastic how to's and search for something like climbing brush or solar. Should demonstrate the problem a bit better.

https://discord.com/channels/586676777334865928/1192524295172264086

**Comment by davehakkens** [comment]
I see what you mean @iSCJT 
Is it right to describe the function of "Most relevant" as "Search results"?
Or am I missing another function it does?

**Comment by iSCJT** [comment]
@davehakkens "Most Relevant" made sense to me at the time as it orders by the most relevant items to your search based on the weighting we use for the fields we search. In the background every item gets assigned a score from 0.00 - 1.00. If you think "Search Results" or another label would make more sense I'm happy to change it over.

I could also look at maybe cutting off the results so any items with a score below x (would need to test to see what looked sensible) didn't get displayed.

**Comment by davehakkens** [comment]
I would think search always implies its sorted by "most relevant" since that is its job.
Would be up for changing the label to "Search Results" to avoid confusement. 

Cut of sounds nice. But that function might already be somewhat there? 
At least it looks like that on PK research. Like the example above only shows 3 results when searching "upload images"

**Review by benfurber — APPROVED** [review]
LGTM. One thought, as preSearchSorter is going into most of the stores, should it go into the module store instead?

**Comment by benfurber** [comment]
Oh and, no tests around `src/pages/common/SortFilterHeader/SortFilterHeader.tsx`...?

**Comment by iSCJT** [comment]
> LGTM. One thought, as preSearchSorter is going into most of the stores, should it go into the module store instead?

Good point, there's quite a lot of duplication across the stores that could be refactored out I think.  I'll look into it under a separate pr along with some tests.

**Pull request merged**
