### PR TITLE
feat: add upload to question

### PR DESCRIPTION
**Pull request by Robert-LC**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Add image upload to questions

## Git Issues

Closes [#3321](https://github.com/ONEARMY/community-platform/issues/3221)

## Screenshots/Videos
image
image

### CODE REVIEW

**Comment by benfurber** [comment]
Hey @Robert-LC thanks so much for your first contribution! 

I've just merged into master a refactor this directly impacts this PR so worth having a look (and probably worth making some changes to your code to incorporate that style before rebasing into your branch). 

That OK? 

(I'd done the refactor because this was going to be soon up on my to-do list so it's fantastic you've been able to pick this up.)

**Comment by Robert-LC** [comment]
Sure I'll take a look and work my changes into the new style

**Comment by davehakkens** [comment]
Good point @benfurber . But would prefer to keep it like this for now (basic)
See what content comes in and later iterate on the design/layout as we will focus more on design.
Since changing now will add some complexcity
- Not everyone adds an image
- We want to make sure it doesnt look the same as a how-to

**Comment by Robert-LC** [comment]
Closing this and reopening a new one, as it was easier to start fresh on a new branch than just rebasing for me

**Pull request closed without merging**
