### PR TITLE
Feat/add questions webhook

### PR DESCRIPTION
**Pull request by pizzaisdavid**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] New feature (non-breaking change which adds functionality)

## Description

~Depends on:~
~- https://github.com/ONEARMY/community-platform/pull/3598~
~- https://github.com/ONEARMY/community-platform/pull/3610~

Adds a webhook for when a new question is posted.

For this ticket: https://github.com/ONEARMY/community-platform/issues/3533#issuecomment-2145761784 but does not close it.

The easiest way to be able to test this is with the emulator + local webhook server.

But we could also just take the changes of the latest commit and apply to master, harder to test that way, though.

## Screenshots/Videos

fox_say

## Open questions

1. It technically uses the Slack webhook, but I imagine on production that has been changed to use Discord? Otherwise some other webhooks are disabled too.

2. I have no idea if the formatting of the message is good. I didn't test it.

### CODE REVIEW

**Comment by pizzaisdavid** [comment]
Can anyone with access to the Firebase Functions config confirm that `slack_webhook` is being also assigned the same value as `discord_webhook`?

**Comment by benfurber** [comment]
> Can anyone with access to the Firebase Functions config confirm that `slack_webhook` is being also assigned the same value as `discord_webhook`? Otherwise, I estimate new howtos and new pins are not being notified in Discord.

Can you answer this @davehakkens?

**Comment by pizzaisdavid** [comment]
How to test:
```
1) yarn run frontend:for-emulated-backend:watch
2) yarn run backend:emulator:watch // in a different terminal.

3) login
http://localhost:4000/sign-in
email: normal_jim@example.com
password: thanks_emulator_man

4) post a question.

5) check the terminal for the backend emulator:
[docker-compose] simulated-webhook-receiver  | Request received!
[docker-compose] simulated-webhook-receiver  | Details:
[docker-compose] simulated-webhook-receiver  | URL: /slack
[docker-compose] simulated-webhook-receiver  | method: POST
[docker-compose] simulated-webhook-receiver  | params: {"0":"/slack"}
[docker-compose] simulated-webhook-receiver  | body: {"text":"❓ normal_jim has a new question: what_?????????????ddddddddddddd???????\n Help them out and answer here: http://localhost:4000/questions/what_ddddddddddddd"}
```

**Comment by pizzaisdavid** [comment]
Questions from normal users don't need moderation. making this listener function kinda different from the Discord ones.

This is ready to be merged.

**Comment by davehakkens** [comment]
> > Can anyone with access to the Firebase Functions config confirm that `slack_webhook` is being also assigned the same value as `discord_webhook`? Otherwise, I estimate new howtos and new pins are not being notified in Discord.
> 
> Can you answer this @davehakkens?

Not sure where to check this?

But from what I know that is currently running:
#1 **Slack** is (was) used to trigger a notification when a new how-to or mappin is made on devsite. This can be removed.
afbeelding
#2 **Discord** is used the trigger a notification when a new how-to or mappin is made on Precious Plastic
afbeelding

**Pull request merged**
