### PR TITLE
Feat/start admin dashboard

### PR DESCRIPTION
**Pull request by pizzaisdavid**
PR Type

- [ ] New feature (non-breaking change which adds functionality)

## Description
Add an admin page... for admin things.

Go to:
http://localhost:3000/admin

gif demo:
admin2

### CODE REVIEW

**Comment by davehakkens** [comment]
Thanks for looking into this.
Altough it makes total sense to have this, we already used to have this but it got removed
https://github.com/ONEARMY/community-platform/pull/2689
The PR also has some background information on the reason why

**Comment by pizzaisdavid** [comment]
Hmm.. Thanks for the quick feedback.

**Comment by davehakkens** [comment]
sorry for being the party pooper.

**Comment by pizzaisdavid** [comment]
Ha. It's no problem. Not sure how the integration of academy would happen without an admin interface. But maybe it would need to be more scoped to the academy specifically, Referring to: https://github.com/ONEARMY/community-platform/discussions/3233

But maybe also the academy thing is low priority at the moment / still being defined.

**Comment by davehakkens** [comment]
Good point. Yeh i imagine the admin panel coming back at some point when we're done prototyping it in Retool.

**Pull request closed without merging**
