### PR TITLE
chore: add circular dependency test to scripts

### PR DESCRIPTION
**Pull request by AlfonsoGhislieri**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

After seeing the circular dependency issues in #2194 by @thisislawatts, I thought it could be good to add a test script to prevent circular dependencies issues from surfacing.

Could be a good idea to add it to the pipeline as well to prevent any circular dependencies from sliping into production.

### CODE REVIEW

**Comment by thisislawatts** [comment]
Good shout catching this @AlfonsoGhislieri, maybe we get this to run alongside the test suites and make it hard dependency before starting the e2e

Screenshot 2023-04-04 at 20 44 56

**Comment by AlfonsoGhislieri** [comment]
Yeah @thisislawatts I think that would be a good idea, I'll try and implement that on the `config.yml`!

**Comment by AlfonsoGhislieri** [comment]
@thisislawatts voilà

image

**Comment by AlfonsoGhislieri** [comment]
@thisislawatts is this good to be integrated?

**Comment by thisislawatts** [comment]
@AlfonsoGhislieri it looks good to me, but I haven't got maintainer access to approve these PRs

**Review by thisislawatts — APPROVED** [review]

**Pull request merged**
