### PR TITLE
feat: init fixing fashion theme

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

## Git Issues

Closes #

## Screenshots/Videos

Reference: 

FF-Example

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by davehakkens** [comment]
Already gave this draft a little spin. All looking good!
Only thing I noticed is that the button :hover is still Project Kamp Green
button

**Comment by thisislawatts** [comment]
@davehakkens 

The `Join our chat` button in the screenshot below demonstrates a closer to brand  _:hover_ colour. Let me know if there's a specific hex code I should be using here:

Screenshot 2022-04-26 at 22 06 56

**Comment by davehakkens** [comment]
that looks good!

**Review by davehakkens — APPROVED** [review]
Works for me!

**Pull request merged**
