### PR TITLE
feat(platform): remove beta wrapper for 'pay as you can' feature

### LINKED ISSUE #3726: [feature request] Remove beta-wrapper for 'Pay what you can' feature
It's time to release the '[Pay what you can](https://github.com/ONEARMY/community-platform/pull/3493)' feature.
Currently its only visible for beta-tester as its behind the auth-wrapper.

This needs to be removed so it's available for everyone.

NOTE: Create the PR but don't merge yet. We will send an email to the creators at the same time
afbeelding

### PR DESCRIPTION
**Pull request by leoasimon**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

This PR displays to any logged-in users, not only beta testers anymore, the "pay as you can" modal whenever they click a download button.

## Git Issues

Closes #3726

## Screenshots/Videos

image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by benfurber — CHANGES_REQUESTED** [review]
Hey @leoasimon, thanks so much for picking this up! As we don't need the auth wrapper in `src/common/DownloadWithDonationAsk.tsx` it can just be removed! :)

Same point for the test, as this beta-tester behaviour has been removed from the component, no need to have a test case for it. 

I think a feature test for this can be changed to. In "Presents the donation request before opening of attachments" on `packages/cypress/src/integration/howto/read.spec.ts` In fact looking at "Allows opening of attachments" in the same file looks like duplicate/misleading testing too.

**Comment by davehakkens** [comment]
Also ready to release when its ready to merge! @benfurber 🔥

**Comment by benfurber** [comment]
@leoasimon As the Precious Plastic team are ready for this to be released I'm going to finish this off now. Have any other issues piped your interest?

**Comment by benfurber** [comment]
@all-contributors please add @leoasimon for code

**Pull request merged**
