### PR TITLE
feat: update title of question page

### LINKED ISSUE #3409: Questions: Page title should update with question title
At the moment, the title of the page doesn't change when viewing an individual question.

Please add this. 

Nice easy thing to cover in the 'Individual questions' cypress feature test for question/read too.

### PR DESCRIPTION
**Pull request by ADTmux**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Clicking a question's title changes the name of the tab to reflect that question.

## Git Issues

Closes #3409 

---

### CODE REVIEW

**Comment by ADTmux** [comment]
Please let me know if a different workaround was required, or a different approach was expected! I'd be happy to work on that as well!

**Review by benfurber — CHANGES_REQUESTED** [review]
Thanks for this @ADTmux. I think it's better to set it on `QuestionPage` though and I'd love to see it tested in the cypress test for `questions/read`.

**Comment by ADTmux** [comment]
hey @benfurber , tested on Cypress and did the requested change. Please let me know what next is required! :)

**Comment by benfurber** [comment]
@ADTmux Sorry to request another change on a tiny commit(!) but I think it should be set during the useeffect rather than the render. Let's go with just after `setQuestion(foundQuestion)`

The branch is also failing the linting right now. That's easiest to fix by running `yarn format`.

**Comment by ADTmux** [comment]
Hi @benfurber could you test it now?

**Comment by benfurber** [comment]
Awesome. Thanks @ADTmux. 

So I think that updating the commit messages to our style will fix the linter plus a rebase with master and we're good to go.

**Comment by ADTmux** [comment]
@benfurber Done!

**Comment by benfurber** [comment]
Hey @ADTmux. Thanks for making that change. Looks like you've pulled in some unrelated (and wrong) changes too? The stuff `incrementViewCount` on `src/pages/Question/QuestionPage.tsx` shouldn't be included. I think then the failing unit test will pass.

**Comment by benfurber** [comment]
Just checking in @ADTmux. Have you seen my last comment? :)

**Comment by benfurber** [comment]
Closing this as I've sorted it in #3623

**Pull request closed without merging**
