### PR TITLE
Feat/update map pin clusters

### LINKED ISSUE #3855: feat: update map pin clusters
### Description

Add a shadow effect to the map pin clusters which changes based on the size of the cluster

### Mockup and design requirements

Clusters use the primary color of the instance (Project Kamp, Precious Plastic and Fixing fashion). The range of the size for the cluster shadow ranges from 2 (where the shadow is small) to 50 (where the shadow is bigger). Even if the number grows above 50, the shadow should not exceed the maximum spread, otherwise I imagine that on a low zoom level.

image

I have applied the following box-shadow properties (X: 0, Y: 0, blur: 2px, spread varies from 4px to 24px). The color is the main color with 50% opacity. The color of the pins should be configurable and can change if a future decision will be made for the color schemes of the map.

image
### Build suggestion

The function to update is `createClusterIcon` and `getClusterSizes` in `src/pages/Maps/Content/MapView/Sprites.tsx`

### PR DESCRIPTION
**Pull request by johannes-ross**
## PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [X] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix (fixes an issue)
- [X] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?
No Ring around Pin.

## What is the new behavior?
When there is a cluster of people (a pin with a number in it) there will be a ring around it, with the corresponding theme colour.

image

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Git Issues

Closes #3855

### CODE REVIEW

**Comment by mariojsnunes** [comment]
I'd rather not have that test, tbh.
@benfurber, thoughts?

**Comment by davehakkens** [comment]
@dalibormrska have a look on the preview link for any visual remarks https://community-platform-pr-4012.fly.dev/academy/intro.html

**Comment by benfurber** [comment]
Thanks for your first time contribution @johannes-ross! 

Yeah, I agree with @mariojsnunes about the test. 

I believe part of the issue is to use the right theme colour for the cluster too. Can you add that please.

**Comment by johannes-ross** [comment]
As requested, I've removed the Test and added another functionality. The pin clusters now change colour based on theme.

I'm guessing, that the assets folder is managed by Designers and not by developers. I've made it as dynamic as possible without changing the actual `map-cluster.svg` file.

**Comment by dalibormrska** [comment]
I had a look, wow, really nice work! Even though I can only see the PP instance through the preview link, from me it's good to go.

**Comment by benfurber** [comment]
Fantastic! Thank you so much for your first contribution @johannes-ross!

**Comment by benfurber** [comment]
@all-contributors add @johannes-ross for code

**Comment by benfurber** [comment]
Also rather belatedly!

@all-contributors add @dalibormrska for design

**Pull request merged**
