### PR TITLE
feat: add banner for users with incomplete profile

### LINKED ISSUE #1588: Add banner for users with incomplete profile
### Description

We want a notification bar for users that **have not** filled in any profile information. ([example](https://community.preciousplastic.com/u/argentech), [example](https://community.preciousplastic.com/u/joel-tovar), [example](https://community.preciousplastic.com/u/aireverde), [example](https://community.preciousplastic.com/u/william-kadima-sakwah))
Specially with comments enabled more users will sign up. However having incomplete profiles is not good for the platform and doesn't show that nice little flag. This would remind people to fill in their information

### Behaviour
If no profile details filled in -> show banner
If profile is filled in -> remove banner

The entire red banner links to [profile page](https://dev.onearmy.world/settings)

### Page related

Will be shown in all pages

### Mockup
Fill in Profile

### PR DESCRIPTION
**Pull request by jojudre**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Latest `master` branch merged

PR Type

- [ ] New feature (non-breaking change which adds functionality)

## Description

add banner for users with incomplete profile

## Git Issues

Closes #1588

## Screenshots/Videos

Снимок экрана 2022-04-06 в 21 12 12

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by davehakkens** [comment]
looks good. Two things missing
1. The banner needs to link to the `/settings `page ([example](https://dev.onearmy.world/settings)) so users can easy acces there
2. When does the banner go away? I've just tried to create an account and filled in my profile details. But the banner is still there.  (image below) If profile details are added the banner should go away.
afbeelding

**Comment by jojudre** [comment]
@davehakkens  oops yes, need to add link, and this banner goes when all user info filled and map pin was added. map pin is not required?

**Comment by davehakkens** [comment]
It's only needed for these mandatory fields panel. (Not very easy to see)
So indeed, map pin not required
mandatory fields

**Comment by jojudre** [comment]
@davehakkens yes,  i fixed it)

**Comment by davehakkens** [comment]
Perfect. Looks good to me!

**Comment by thisislawatts** [comment]
👋🏻 Hey @jojudre, it looks like there is a failure here due to the code not matching our newly introduced styleguide. If you run `yarn format` on your machine and commit the changes this should fix the failure. Let me know if you have any further questions!
https://app.circleci.com/pipelines/github/ONEARMY/community-platform/1933/workflows/d0e2e3ee-2893-465d-b83a-b038222a7408/jobs/10305

**Review by thisislawatts — APPROVED** [review]

**Pull request merged**
