### PR TITLE
chore: update yarn 3.0.2 to 3.1.1

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## TODO
- local install failing due to some issues with Uppy. Will resolve these first before opening pr

## Description

Upgrade yarn 3.0.2 to 3.1.1. A few useful updates:
- adds support for typescript 4.5 if we ever swap to pnp.
- faster installs with better hoisting optimisations
- ways to operate only on workspaces that have changed since a particular commit (might be a nice future ci optimisation, but for now a bit experimental)

Yarn changelog: https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#311

## Review Notes
I assume everything should be fine in CI (all installs/build working fine locally), but if any errors come up might be easier to just clear the CI cache by changing cache names from `yarn-packages-v10-...` to  `yarn-packages-v11-...` (or any other naming convention)

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Review by thisislawatts — COMMENTED** [review]
**question:** do we need to manually increment the cache version in CircleCI config.yml as the lock file hasn't changed?

**Comment by chrismclarke** [comment]
> **question:** do we need to manually increment the cache version in CircleCI config.yml as the lock file hasn't changed?

I _think_ the answer should be no, although there are errors currently linked to uppy (fixed in #1443) . But wouldn't be the first time I thought node_modules should behave one way and turns out they just didn't... so I reserve the right to change my mind if the build fails 2-3 more times...

**Comment by chrismclarke** [comment]
Looks all to be working with the other PR merged in, without need for cache-busting. So that's good.
I'll mark as ready for review, and make a mental note to try not get sooo side-tracked tomorrow!

**Review by thisislawatts — APPROVED** [review]

**Pull request merged**
