### PR TITLE
feat: add catergory vertical list to how-tos

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Feature (adds functionality)

## What is the current behavior?

A SO BORING drop-down to select a category filter for a content type.

## What is the new behavior?

1. A beautiful shiny vertical scroll with icons.
2. Adds back in some filtering e2e specs, including changing test DB data.
3. Tidy-up of the how to list display styling.
4. A generic category icon is shown if a specific glyph isn't present.

Screenshot 2024-12-17 at 11 32 26
Screenshot 2024-12-17 at 11 31 55

All the icons added:
Screenshot 2024-12-17 at 15 53 16

## Does this PR introduce a breaking change?

- [x] No

## Git Issues

Part of #4003

### CODE REVIEW

**Comment by benfurber** [comment]
Actually, I'll keep this PR just to how-tos.

**Comment by davehakkens** [comment]
nice component!
Can we change the order of the categories?
And how do we add a new ones.
In retool, ask dev?

**Comment by benfurber** [comment]
@davehakkens Still update through retool. Currently the order is essentially just what's in the database. 

I was planning to make the order alphabetic in my next PR, does that work for you? 

Other options:

1. Loads more work - add an order field to the DB.
2. mini-hack - Use the created date order and make that editable on retool.

**Comment by davehakkens** [comment]
alphabetical doesnt do the trick.
Creation date sounds good!

**Comment by davehakkens** [comment]
And is the category image also added in retool, or a dev-thing?

**Comment by benfurber** [comment]
Dev thing. For ease I updated the existing icon list.

**Pull request merged**
