### PR TITLE
Fix #2315 - Possible to reuse previous slugs causing old links to break

### LINKED ISSUE #2315: [bug] previously used how to & research slugs not prevented from being used
**Describe the bug**
If the title of a how to or research item is updated then the slug is also updated, previously used slugs are saved for that item so that old links can be maintained however nothing prevents a new item from being created with a previously used slug.

**To Reproduce**
Steps to reproduce the behaviour:

1. Edit how-to / research item and change title
2. Open item using original and new slugs to confirm that accessible using both
3. Create how-to / research item and use the old title of the previous item
4. Complete details of item and submit
5. Observe that new item uses original slug and loads correctly but that it is not possible to access the edited item using the original slug.

**Expected behaviour**
That current and previous slugs are globally unique across item type.

**Screenshots**

**Additional context**
My suggestion is a global lookup table of slugs and corresponding document id's which is checked before assigning a slug.  If a slug is in use then either return the existing error about the title not being unique or auto append an incrementing number.

### PR DESCRIPTION
**Pull request by benkelaar**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Adds a check on previousSlugs on title validation.

## Git Issues

Closes #2315 

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by evakill — APPROVED** [review]
good stuff, thanks @benkelaar! really appreciate the comments and testing 💪

**Comment by benkelaar** [comment]
@evakill Thanks!  That was quick!  You don't think the concern [I describe here](https://github.com/ONEARMY/community-platform/issues/2315#issuecomment-1694488376) is an issue?

**Comment by evakill** [comment]
> So I do have a concern, coming out of the tests as well. The test data for the research items did not contain previousSlugs arrays at all, does this mean that there might be how tos or research items in production databases that don't have this property either?

oops, wasn't following the thread on the issue! let me look into this first thing, i believe the research and howto both track previous slugs in the prod db

> Do you guys do database migrations? Because I couldn't find any so far, but that might be a good mechanism to fix this.

i wish 😅 I'm not aware of migrations frameworks that work w firebase. if you have experience here would love to hear it. absolutely agree we could improve our database hygiene generally - it is hard to keep track of schemas, especially with the multiple database instances

**Comment by evakill** [comment]
@benkelaar yeah, it seems it's just that the research test data was missing the previous slugs - confirmed that the howtos and research both use that field in the DB. 

thanks for modifying the research mocks, and for better test coverage we should add a similar test to research as you did [here](https://github.com/ONEARMY/community-platform/pull/2724/files#diff-b04f255b1accab30e685dcb0eb02e7cbb3edb8cf6f40571d9deacb914a93df4aR179-R187). let me know if you'd like to do that, or i can make an issue for someone else to pick up.

sorry for not reviewing the tests thoroughly enough and thanks for bringing up this concern!

**Comment by benkelaar** [comment]
Since it was just a variant of the already existing "Title already exists" use case I thought it might not be necessary to add another e2e test in both variants (Especially since they use the same code).

I did actually get a unit test to work just now, so would it be acceptable if I cover all variants with unit tests instead?

**Comment by benkelaar** [comment]
> i wish 😅 I'm not aware of migrations frameworks that work w firebase. if you have experience here would love to hear it. absolutely agree we could improve our database hygiene generally - it is hard to keep track of schemas, especially with the multiple database instances

On this, I haven't seen it on a firebase-backed application either.  Theoretically shouldn't be too hard to roll your own though, you just need to store a version in the database somewhere and then keep an index of migrations against version number.  But the devil's in the details of course and I'm not sure how high up the priority list that would be for you.

Quick google gets me via https://stackoverflow.com/questions/35147780/firebase-database-migration to https://github.com/kevlened/fireway , but that seems to have support issues, but API design seems solid (Love flyway).  There is a more recently updated fork here https://github.com/dev-aces/fireway but that's once again only supported by one person so you'd basically have to adopt the library if you want to be dependent on it.

**Comment by evakill** [comment]
> I did actually get a unit test to work just now, so would it be acceptable if I cover all variants with unit tests instead? 

yep definitely, i tend to prefer the unit tests, the cypress tests can be super slow

**Comment by benkelaar** [comment]
@evakill Here's the promised unit tests: https://github.com/ONEARMY/community-platform/pull/2730

**Pull request merged**
