### PR TITLE
feat: add wrapper to settings form

### PR DESCRIPTION
**Pull request by benfurber**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] New feature (non-breaking change which adds functionality)

## Description

So this is a slightly clunky stepping stone. This uses the new settings form wrapper, but with the existing form setting/structure. It's essentially the fundations to then move out sections of the form into other tabs.

## Git Issues

Part of #3724

## Screenshots/Videos

Screenshot 2024-07-05 at 13 18 09

### CODE REVIEW

**Comment by benfurber** [comment]
@davehakkens Please have a play. I've tweaked a couple of bits that felt too weird for this interim step. Of course happy to change things in this PR but setting up the tabs won't take long (a few days next week).

**Comment by davehakkens** [comment]
Seems like it needs a max-width. But perhaps it will be better when sidebar is there
afbeelding

Regarding the merge, would be nice to only merge if we know the other bits will be picked up soon because
- The design doesnt look very finished (specially messy when signing up as a new user)
- Some functions are gone (like the sidebar with community program)
- Could see some bugs coming up in this transition period.

**Comment by benfurber** [comment]
Good idea about a max width - would be a quick fix for instant less messiness.

**Comment by benfurber** [comment]
@davehakkens Have another look now? Looks like 850px is the sweet spot.

> Some functions are gone (like the sidebar with community program)
Of course the main sidebar is gone as per the design, what do you mean about the community program sidebar?

**Comment by davehakkens** [comment]
> Have another look now? Looks like 850px is the sweet spot.

Looks good to me


> Of course the main sidebar is gone as per the design, what do you mean about the community program sidebar?

wasnt sure if the items on the sidebar are covered somewere else (if we delete it)
but looks like it actually is: 
- Profile guideliness are on top
- Community Program guidelines are still there when creating a map pin for 'spaces"
- Contact is now there in the new 'problems?' button

So nevermind my orignal comment on this 🫣

**Pull request merged**
