### PR TITLE
feat(platform): migrate from react-image-lightbox (deprecated) and include more unit tests

### LINKED ISSUE #2633: [test] add tests to validate functionality of ImageGallery component
ImageGallery.test.tsx needs to be updated to add tests that validate the current functionality of the ImageGallery component.

- Clicking through the thumbnail images changes the main image displayed
- Clicking on the main image displayed opens that specific image larger within the lightbox
- Clicking the previous and next arrows within the lightbox changes the image displayed to the correct previous and next images.

### PR DESCRIPTION
**Pull request by BeeMargarida**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

This PR includes:
- Migrate `ImageGallery` from the deprecated package `react-image-lightbox` to `photoswipe`
- Include unit tests for the functionalities of ImageGallery (including lightbox functionality)

## Git Issues

Closes #2633

## Screenshots/Videos

| Before  | After |
| ------------- | ------------- |
| <video src="https://github.com/ONEARMY/community-platform/assets/25725586/b1d0637d-59d1-4ca8-b502-7e7291bee086" />  | <video src="https://github.com/ONEARMY/community-platform/assets/25725586/5535e017-6386-4b1b-ad6b-60c697f36697" />  |

### CODE REVIEW

**Comment by thisislawatts** [comment]
Welcome @BeeMargarida, thanks for taking the time to raise this PR 💚 

We are using a monorepo format with `packages/components` being it's [own workspace](https://yarnpkg.com/features/workspaces). To manage dependencies for this workspace you should navigate into the directory and run `yarn add photoswipe`.

I am a bit confused how it ever worked given `react-image-lightbox` wasn't installed in the `packages/components` directory 🤔

**Comment by BeeMargarida** [comment]
Hey, sorry, I've been a bit busy these last few days. I've fixed the build issues and moved the package, and I'll try to fix the failing CI today, see what's causing the issue

**Comment by BeeMargarida** [comment]
@thisislawatts Hey, it seems like it's related to missing declaration of modules for the unit tests. I declared the modules with a global type, but it seems like this is not being used for the unit tests.
Since I have no experience with craco, could you help me or point me in the right direction regarding this, if you can? Thank you

**Comment by BeeMargarida** [comment]
Oh wait, I think I found the solution!

**Review by thisislawatts — APPROVED** [review]

**Comment by thisislawatts** [comment]
@all-contributors add @BeeMargarida for code

**Pull request merged**
