### PR TITLE
Feat: updated user settings tweaks

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix (fixes an issue)

## What is the new behavior?

Screenshot 2024-08-08 at 13 29 06
Screenshot 2024-08-08 at 13 29 18
Screenshot 2024-08-08 at 13 29 24

### CODE REVIEW

**Review by mariojsnunes — APPROVED** [review]

**Comment by davehakkens** [comment]
image
Just saw this now. But doest seem like the right error message

**Comment by benfurber** [comment]
@davehakkens Fixed the display name field label (and added the description).

ALSO. Thoughts on adding this? Makes the difference even clearer:

https://github.com/user-attachments/assets/4314ec61-9cf2-4708-a82d-036690f3ab42

**Comment by davehakkens** [comment]
No strong opinion. What do you think @dalibormrska?

**Comment by dalibormrska** [comment]
> No strong opinion. What do you think @dalibormrska?

Makes sense to me. Adds clarity.

**Pull request merged**
