### PR TITLE
#946 hide map pin when profileType is change to member

### PR DESCRIPTION
**Pull request by prolland006**
PR Type

- [x] Bug fix (non-breaking change which fixes an issue)

PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)
- [x] - Passes Tests

## Description

_What this PR does_

## Git Issues

_Closes #946_

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

### CODE REVIEW

**Comment by chrismclarke** [comment]
This makes sense to me, I think there are longer-term plans to bring back member/want-to-start pins but for now probably best to just hide the pin when a user swaps back to member.

Just to quickly check with @davehakkens - does this sound right to you?
**Before** - profiles that change from workspace to member end up with a member pin
image

**After** - member pin hidden (but will come back if they change back again)
image

**Review by chrismclarke — APPROVED** [review]

**Review by davehakkens — APPROVED** [review]
nice. Yes this is good for now, keeping the map clean!
Indeed in the future it might change, but that would still take some time..

**Comment by phubcat** [comment]
@davehakkens , @chrismclarke - looks like you guys really don't understand a **** 

as always, the only thing you #$%#$% can come up is utter garbage & crap followed by shitty fascisms to cover it up - no wonder anyone is laughing at you guys - til a degree we have to apologize for you - on a weekly base - since years

what's next, hail dave gang ? 

thanks btw. for getting our github account down - that wont be forgotten - I hope you have the money sometime to pay for the damages !

**Comment by phubcat** [comment]
fascists wanker punks at work - go f** your self - you ridicules piece of useless shame !

**Comment by phubcat** [comment]
@davehakkens - you and this miserable useless fag fuck Mattia; when the fuck are you leaving ? No seriously - when the heck you gonna die actually ? My cat or worst, my sister is gonna clean the floor after your wish washy nonsense ; Hitler would be so proud of you !

**Comment by phubcat** [comment]
@chrismclarke - seriously ? are you really leaving the project to this pile of on-maintainable react garbage ? 

in case you fucking live on the moon : THIS IS ABOUT PLASTIC RECYLCING !!!! Not some goofy girly Mattia  bullshit shitshow which could even escape your poor imagination 'properly'

**Comment by phubcat** [comment]
@davehakkens - at least this poor retarted fuck as CitizenSShitShop seems to fit you well - see you soon

**Comment by withthebackatthewall** [comment]
in case you're still on this earth : yes - you little shitty morons just replace at least something you could call 'culture, networks, friendships' with your cheap shitty little poor usual-runaway attempts whilst trying to get out on top.

now you little sick fucks : how do we contact our buddies on the forum ? how the f** we can write proper content ? ... 

you seem always so full of ideas - nah ! just shit - try harder

**Comment by withthebackatthewall** [comment]
'nice. Yes this is good for now, keeping the map '''clean'' '! - Say Hi Hitler as next to some dumb fucks ups in a van, dictating others   ... lol

Please take your garbage - and die slowly

**Comment by withthebackatthewall** [comment]
@davehakkens - we understand since long that other people don't mean shit to you nor or simple laws don't apply to you - but again - unveiling private details in public without my consensus is again prove of your incompetent's childish and poor appearance - something we have to rectify and explain to users on a daily base. 

And just for the record, we and others are the folks cleaning up after your goofy and irresponsible nonsense - 

You should really put a entry filter on your mafia club's door : under 12 only ! Luckily you have at least a few left dumb folks who like your gibberish :-)

**Comment by withthebackatthewall** [comment]
image

but thanks for the non-sense and defamation again - we had a good laugh !

**Pull request merged**
