### PR TITLE
refactor: e2e best practice #3475

### PR DESCRIPTION
**Pull request by tuliobluz**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Following the issue https://github.com/ONEARMY/community-platform/issues/3475

- It was removed unnecessary `cy.wait` then it can save some test running time
- move `cy.deleteCurrentUser` to `beforeEach` instead of after as best practice
- Removed duplicate `generateId` code as best practice

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by mariojsnunes** [comment]
This looks great!
Do you want to make any other changes for this PR?

**Comment by benfurber** [comment]
Thank you so much for this @tuliobluz! Yes, it could probably do with a squash but it looks like this will reduce flakiness on a couple of tests that are annoying in other branches so I'm going to merge this now.

**Comment by benfurber** [comment]
@all-contributors please add @tuliobluz for code

**Comment by tuliobluz** [comment]
Thanks for merging it, I will try to solve most of the flaky now, haha

**Comment by tuliobluz** [comment]
@mariojsnunes now I just realized what you mean with squash, sorry. I should have done it before. I will pay attention for the next ones.

**Pull request merged**
