### PR TITLE
2550 sort research by moderation status

### LINKED ISSUE #2550: [feature request] pin draft / awaiting moderation / rejected research created by the logged in human to top of listing
**Is your feature request related to a problem? Please describe.**
If a human using the platform adds a draft research item then they can lose visibility of it.

**Describe the solution you'd like**
If the logged in human has any draft, awaiting-moderation or rejected status research created by them then they should be pinned to the top of the research list so they see can always find them.

**Describe alternatives you've considered**
N/A - Agreed at June meetup

### PR DESCRIPTION
**Pull request by maxbethke**
PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Research that is a draft, awaiting moderation or rejected should be displayed on the top of the list of researched regardless of the chosen sorting option, because it can otherwise easily get lost further down the list.

## Git Issues

Closes #2550 

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by iSCJT** [comment]
@maxbethke thanks for this.  The requirement is a bit more complicated than implemented.  I should have made the issue more explicit, sorry.  The sort logic required is that the logged in user should only see their own items awaiting moderation at the top of the list and then all of the others next, so...

show first: _createdBy === logged in user AND moderation !== 'accepted'.  Then for anything not meeting that requirement use whichever sort option has been chosen.

Hope that makes sense and sorry the issue ticket wasn't more descriptive.

**Comment by maxbethke** [comment]
Thank you for making that clear @iSCJT. My understanding was (Like you can see here https://github.com/ONEARMY/community-platform/issues/2571#issuecomment-1622954402), that the visibility is already set up according to authentication, so only the creator (and moderators) see non-accepted items in the first place.

If thats not the case, I agree with the need to filter by auth like you described above.

I do want to make the case though that this would be non-intuitive to me as a user, as I would expect my research in draft state to not be publicly shown (hence the 'publish') button to proceed in the workflow. To me, this state would rather be called 'Work in Progress', as it is already public but indicated to not be finished. 
Secondly, why have a moderation (in later stages of the platform) if the drafts are already published?

I will rework the feature to take ownership into account but would advise to rethink that system.

**Comment by iSCJT** [comment]
@maxbethke you're right that the visibility is set up according to the authentication and it should stay that way, we don't want to change anything to do with the visibility just the order that things are displayed.

The original request came from the moderation team in relation to the how-to's, they felt as a normal user of the system that there is nowhere that surfaces the non-accepted items easily.  The research and how-to lists are the most visible/frequented related pages so for the user that created the item (and only that user) they wanted the non-accepted items to appear first in the list.  As a logged in moderator they don't want anything to change and the non-accepted items should appear in the list as they do currently.

Another option would be to have a separate panel at the top which showed any of your own items that weren't accepted but we wanted to keep it as simple as possible / least work to implement.

**Comment by evakill** [comment]
hey @maxbethke - are you interested in continuing work on this one? otherwise will open it back up to contributors

**Comment by maxbethke** [comment]
> hey @maxbethke - are you interested in continuing work on this one? otherwise will open it back up to contributors

Hi, even though I'd really like to, I am not able to find the time in the last weeks and it does not seem to change soon.
Maybe someone else can take it from here. From the conversations in on #2550 any contributor should be able to pick up the task. If required, I can write a handover to make clear what still has to be done. If there should be any questions, just mention me and I will see what I can do.

**Comment by AlfonsoGhislieri** [comment]
Closing this as I've taken over the issue and raised a PR: #2739

**Pull request closed without merging**
