### PR TITLE
Feat/email automation

### LINKED ISSUE #890: [feature request] - Email System
**Is your feature request related to a problem? Please describe.**
As part of monitoring a profile wipe issue it would be good to have a system that can send specific alerts or notifications on demand (not limited to specific slack or discord channel)

**Describe the solution you'd like**
A mailing system to trigger email notifications. Likely at first using firebase's mailing extension and existing gmail account for smtp, later possibly service such as sendgrid/sendinblue etc.)

**Describe alternatives you've considered**
Additional slack channel for dev/temporary notifications

**Additional context**
A feature planned for use in the longer term anyway (current firebase email templates very limited) so would have additional benefit when implemented.

### PR DESCRIPTION
**Pull request by chrismclarke**
NOTE - This PR builds on top of #889 and should only be merged after.
closes #890 

## Done
- Enable firebase email extension and configure with platform@onearmy.world email
- Documented required setup: https://github.com/ONEARMY/community-platform/wiki/Email-Automation
- Added demo which sends an automated email to a named user on a specific profile edit (to support debugging of #883)

## Screenshots
image
_Example email sent to notify of profile change_

Includes note at bottom to suggest viewing at http://www.jsondiff.com to allow easier visualisation of difference

image
_Differences viewed at jsondiff_

## Todo
- The test notification system has been configured to send me an email when the PP profile is edited, so once in production it would be good to make a small test to confirm
- Communicate with core team to see how else automated email notifications could/should be used (e.g. custom sign-up confirmation templates etc.)

### CODE REVIEW

**Comment by BenGamma** [comment]
Looks good to me, althought if I understand well this PR is only for debuging purpose of the profile wipe bug ?

**Comment by chrismclarke** [comment]
No it's also to put in an automated email system. We had wanted one a while back to send out custom emails on user signup but didn't have the time to put it together. So now this PR includes one, which I'm using mostly as a demo with the profile wipe bug.

**Comment by BenGamma** [comment]
Should I merge now or you are still working on this PR @chrismclarke ?

**Comment by BenGamma** [comment]
I'm merging because the build is failing in dev env and so probably in production too.
Nothing seems too critical anyway with this PR, and it adds a few improvements we will benefit to merge anyway

**Pull request merged**
