### PR TITLE
feat: use OSM instead of Algolia Places

### LINKED ISSUE #1177: [feature request] - Replacement for Algolia Places Required
**Is your feature request related to a problem? Please describe.**
We currently use algolia places to autocomplete location search on map and user profile pages, however Algolia have announced they are _sunsetting_ the project and will no longer be supporting after May 31st 2022 (and have already ceased new signups)
https://www.algolia.com/blog/product/sunseting-our-places-feature/

**Describe the solution you'd like**
Ideally we want to find either a similar commercial solution that has a decent free tier, or an open-source solution that could be self-hosted (or paid as a service temporarily). Ideally it will continue to use Open Streets Map data for consistency with the data that already exists (and avoiding google map lockin). A couple platforms Algolia mentions are:
- [Mapbox](https://www.mapbox.com/)
- [Google Places](https://cloud.google.com/maps-platform/places)
- [Geocode Earth](https://geocode.earth/)

A couple others that came up with a quick search on github include:
- [Photon](https://photon.komoot.io/)
- [OSM Names](https://osmnames.org/)
- [Pelias](https://pelias.io/)

Not sure if anybody has used any of these before or has any other suggestions?

**Additional context**

_Example of Algolia Places used on the map page_
image

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [X] - Latest `master` branch merged
- [X] - PR title descriptive (can be used in release notes)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Removes all instances of deprecated Algolia Places product in favour of OSM. This covers:

* Workspace Pins
* Map Search
* Event creation

## Git Issues

Closes #1177

### CODE REVIEW

**Comment by davehakkens** [comment]
wauw nice one!! Two remarks
1. On mobile it has a weird overlap
Screenshot 2022-01-18 at 11 15 38
 2. This one is mostly weird on the events section (because you don't see a map). When you select your location you don't see what you selected which makes it a bit confusing. So you don't really see what you will publish. Ideally the location you've chosen stays in the box.
 
events location

**Comment by thisislawatts** [comment]
Ready for a re-review @davehakkens

**Review by davehakkens — APPROVED** [review]
works very nice now!

**Pull request merged**
