### PR TITLE
Reintroduce "fix: map page missing flags"

### PR DESCRIPTION
**Pull request by thisislawatts**
Reintroduce changes, reverted in ONEARMY/community-platform#2209

Originally these changes were reverted in attempt to resolve test failures in an `events.spec.ts`. However, we ended up skipping the failing test (0e49c907f71f00f3ae60be3c67358d9c32776f71) as it consistently failed _after_ the revert was applied.

### CODE REVIEW

**Comment by thisislawatts** [comment]
@AlfonsoGhislieri would you be able to take a look at this revert of a revert? 🙈

**Comment by AlfonsoGhislieri** [comment]
@thisislawatts I can absolutely re-review the revert of the revert! However, just at a glance it does seem that this will reintroduce flakiness for the maps e2e tests though, are we okay with this?

**Comment by thisislawatts** [comment]
My understanding of the issue @AlfonsoGhislieri is that the flakey tests were in events.spec.ts which have now been skipped.

**Comment by AlfonsoGhislieri** [comment]
@thisislawatts I noticed that in these old PR's the map spec was having flaky results and even failing outright:
- #2207 
- #2206 
- #2205

**Comment by thisislawatts** [comment]
Good catch @AlfonsoGhislieri, I am being a too lazy here and made the assumption that the test failures all shared a common route. I had missed the failures in `map.spec.ts`

Closing in favour of lightweight #2221, I will raise the various refactors made here as separate PRs later on to nudge things in the right direction. Hope this doesn't put anyone off refactoring.

**Pull request closed without merging**
