### PR TITLE
fix: adds category to IHowto save

### LINKED ISSUE #2725: [bug] category does not prepopulate when editing a how to post or draft
**Describe the bug**
The category field appears empty when editing an existing how to that has a category selected.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a how to, select a category tag, save as draft or publish
2. Return to edit this how to
3. Category is not present in fom

**Expected behaviour**
Category should persist when saved and appear in the form when in edit mode.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by jwjacobs88**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Adds `category` back to the `IHowto` database update.

## Git Issues

Closes #2725

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by evakill** [comment]
tried this out locally and looks good! as for the test, it looks we're using the factory draft method in the [howto store test](https://github.com/ONEARMY/community-platform/blob/master/src/stores/Howto/howto.store.test.ts#L86) - which doesn't define a category. if we switch this to the [regular factory how to](https://github.com/ONEARMY/community-platform/blob/master/src/test/factories/Howto.ts#L4) i think we'll have more complete test coverage. 

could you give that a try? lmk if you run into problems

**Comment by jwjacobs88** [comment]
> tried this out locally and looks good! as for the test, it looks we're using the factory draft method in the [howto store test](https://github.com/ONEARMY/community-platform/blob/master/src/stores/Howto/howto.store.test.ts#L86) - which doesn't define a category. if we switch this to the [regular factory how to](https://github.com/ONEARMY/community-platform/blob/master/src/test/factories/Howto.ts#L4) i think we'll have more complete test coverage.
> 
> could you give that a try? lmk if you run into problems

It didn't look like the regular How To factory used category either, so I added it to the main factory.

I see I had some integration test failures, but I'm having a tough time finding out why. I might have to look into Cypress a bit as I've never used it.

**Comment by evakill** [comment]
thanks @jwjacobs88 - so the error in cypress is 
```
Error: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in field category in document 6xqYo_v3_howtos/kFG6c0MM0kK3x2k50FRN)
```
this popped up because of your change [here](https://github.com/ONEARMY/community-platform/pull/2729/files#diff-a2437a58b8d602deb7c8d0b921e348a6c2c561c7af93bcaeb0a13833b0e9541eR588) - `category` does not have to be defined if we are saving a draft, which is part of what is tested in cypress (and what i did not check - oops). i would recommend following the pattern on [this line](https://github.com/ONEARMY/community-platform/pull/2729/files#diff-a2437a58b8d602deb7c8d0b921e348a6c2c561c7af93bcaeb0a13833b0e9541eR603), which will avoid this error.

i also saw in cypress that we don't test the category input. since you're still new to cypress and this is an active bug, i would be more comfortable getting this change in and following up with better coverage! thanks for looking into it though :)

**Comment by jwjacobs88** [comment]
> thanks @jwjacobs88 - so the error in cypress is
> 
> ```
> Error: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in field category in document 6xqYo_v3_howtos/kFG6c0MM0kK3x2k50FRN)
> ```
> 
> this popped up because of your change [here](https://github.com/ONEARMY/community-platform/pull/2729/files#diff-a2437a58b8d602deb7c8d0b921e348a6c2c561c7af93bcaeb0a13833b0e9541eR588) - `category` does not have to be defined if we are saving a draft, which is part of what is tested in cypress (and what i did not check - oops). i would recommend following the pattern on [this line](https://github.com/ONEARMY/community-platform/pull/2729/files#diff-a2437a58b8d602deb7c8d0b921e348a6c2c561c7af93bcaeb0a13833b0e9541eR603), which will avoid this error. also looks like this branch needs a rebase on master.
> 
> since you're still new to cypress and this is an active bug, i would be more comfortable getting this change in and following up with better coverage! thanks for looking into it though :)

I've made the suggested changes and rebased.

**Review by evakill — APPROVED** [review]
thanks @jwjacobs88!

**Comment by evakill** [comment]
here is the follow up issue to improve test coverage https://github.com/ONEARMY/community-platform/issues/2743

**Pull request merged**
