### PR TITLE
feat: increases max length for a Research introduction

### PR DESCRIPTION
**Pull request by davehakkens**
Increase the max length of characters for a research introduction. 

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

### CODE REVIEW

**Comment by thisislawatts** [comment]
@davehakkens, can you change the commit to introduce the prefix `feat:`. Also consider a more descriptive message, such as:

`feat: increases max length for a Research introduction`

**Comment by davehakkens** [comment]
Ah, I added something to the title.
But should be in the body text?

**Comment by thisislawatts** [comment]
Almost, but not quite. We need to update the commit message rather the title/description of the PR. 

What tool are you using to generate a commit? 

If you are using the terminal you can run `git commit --amend` to edit the message of your latest commit.

**Comment by davehakkens** [comment]
I use the Github desktop.
I can leave a summary (title) + description.
But sounds like it should be somewhere else? 🤔

afbeelding

**Comment by thisislawatts** [comment]
Aha, gotcha. In that context it is the Summary which needs to be formatted as `feat: increases max length for a Research introduction`.

I've adjusted the commit message on your behalf and pushed into the branch. So now we wait for CircleCI ⏳

**Review by thisislawatts — APPROVED** [review]

**Comment by chrismclarke** [comment]
@thisislawatts - If we have more PRs coming through in future that don't meet message lint (very likely with some older PRs, possible with some PRs from forks/direct edit attempts) I _think_ we can just squash merge and provide a tidier name ourselves instead of trying to get the commits edited. Although also happy to make a serious coder out of Dave.

**Pull request merged**
