### PR TITLE
feat: add tablet up responsive elements for new map

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix (fixes an issue)
- [ ] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the new behavior?

_Describe the new behaviour_
_If useful, provide screenshot or capture to highlight main changes_

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Git Issues

Closes #

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by benfurber** [comment]
@dalibormrska @davehakkens I'm obvs still working on this (e.g. the display of the toggle the list view) but thought I'd let you see the progress so far as it's essentially already what the user interaction will be.

**Comment by davehakkens** [comment]
I have a hard time seeing how this interaction will be once filters are in there as well.
But as long as you see it i'm good!

And would lean towards making map default, not list view

**Comment by benfurber** [comment]
Painful day working on this!

Had to rebuild part of the main website templating to deal with the issue of the max-height being more than the max-height on a screen. The improvement is tiny and I'm still dealing with the side-effects now.

I'll decide on Monday morning but I might just scrap off all of today's work. :/

Also might need to change approach to deal with the map only display being the default for mobile/tablet. Due to how the responsive display stuff works, it'll be a little awkward to deal with without rendering multiple maps (which should be avoided, obvs.). I'll think on it.

**Comment by benfurber** [comment]
I'm going to scrap this branch and start again. 

New approach: 
* Just put the show/hide button at the top so I don't have to restructure the whole layout templates/side effects.
* Render different list view for mobile so that the map for mob can default to map view and I don't have to think about the complexity of conditional list views based on viewpoints.

**Pull request closed without merging**
