### PR TITLE
fix: saving a research article as a draft does not trigger webhook

### LINKED ISSUE #3740: [bug] Saving a new Research Article Update as Draft triggers the webhook
**To Reproduce**
Steps to reproduce the behaviour:

1. Start emulator backend.
2. Start frontend for emulator.
3. Login as precious plastic.
4. Edit the existing Research Article.
5. Create a new Update.
6. Create a title, description, and add a photo.
7. Press save as draft.
8. Check in the command line that the webhook was triggered.

Link to  emulator: https://github.com/ONEARMY/community-platform/blob/master/packages/documentation/docs/Backend%20Development/firebase-emulator.md#commands

**Expected behaviour**
The webhook should not be triggered.

Also, as Ben has pointed out in the comments, that if the article is a draft, it is currently also possible to trigger the webhook, which is bad mm'kay.

### PR DESCRIPTION
**Pull request by onim-at**
## PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [X] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix (fixes an issue)
- [ ] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?
Saving a research article as a draft triggers the discord webhook

## What is the new behavior?
Saving a research article as a draft does not trigger the discord webhook

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Git Issues

Closes #3740

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by pizzaisdavid** [comment]
Looks great to me, even with a corresponding unit test!

**Comment by pizzaisdavid** [comment]
I don't have merge permissions.

**Comment by pizzaisdavid** [comment]
🎉 🍰 🥳

**Comment by davehakkens** [comment]
> Looks great to me, even with a corresponding unit test!

Thanks for reviewing!

**Review by davehakkens — APPROVED** [review]

**Pull request merged**
