### PR TITLE
feat(seo): Update headings for research section

### LINKED ISSUE #3424: Quick SEO wins
There's a few quick wins we can do from a search and social prospective.

1. Use heading tags correctly.
2. Ensure all images have alt tags.
3. Set more/better open graph tags.

### Heading tags
The research, how-to and question titles should definitely be h1s rather than h2s. There might also be more semantic heading considerations.

### Image alt tags
At the moment we don't ask users to provide alt tags for the images that upload. As a short-term fix, we should apply alt tags to research updates, how-to steps and questions which follow some kind of dynamtic structure, e.g. '<research update title> - <image index>'

### Better open graph tags
At a minimum we need 'og:type' set to website in the `postCraBuild.ts` script, but there's probably [more improvements we should make](https://docs.prerender.io/docs/open-graph)

### PR DESCRIPTION
**Pull request by codisart**
Refactoring upload submit modal to remove some duplication

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

This PR update some Headings components to a specific html heading tag from the default h2. There is some debate to have to some choices. Like for the upload status modal, I chose "p" but h2 or h3 could be valid. 

## Git Issues

Helps to close #3424 

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by benfurber — CHANGES_REQUESTED** [review]
@codisart Thank you so much for this! SEO is one of those things that should be prioritised more highly but always hard to do so. Looks like there's a linting and merge issue but should be good to go after that.

**Comment by codisart** [comment]
Thank you @benfurber !

As asked I ran eslint and prettier and rebased my PR. 
But one unit test is failing and I have no idea why it fails on my PR.
Do you have an idea ?

**Comment by benfurber** [comment]
@codisart The failure relates to `BackToResearchButton` which is a component you've changed. As that's an issue and not strictly part of issue #3424, I'd say let's revert those changes so that the SEO wins can get released sooner.

**Comment by codisart** [comment]
Ok I will open a separated small PR for this breakdown.

**Comment by benfurber** [comment]
@codisart The tests are now rightly failing as the component snapshots need updating. Running `yarn test:unit --updateSnapshot` ...or maybe it's `yarn test:components --updateSnapshot` should sort that out and then those changes can also be committed.

**Comment by benfurber** [comment]
Or this way: https://jestjs.io/docs/snapshot-testing#interactive-snapshot-mode

**Comment by codisart** [comment]
On it

**Comment by codisart** [comment]
So I add to run `yarn run test -u` in the `package\components` folder

**Comment by benfurber** [comment]
@codisart We've there with this one! Nice one, thanks!

**Comment by benfurber** [comment]
@all-contributors please add @codisart for code

**Pull request merged**
