### PR TITLE
Fix/seed scripts

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Breaking Changes
- New deps require `yarn install`
- Seed data updated (should auto-load latest zip on start)

## Description
NOTE - one issue kept leading to another resulting in a pretty messy diff (partial seed data fixes mixed with route access fixes)

Whilst trying to update testing methods for user roles a new set of seed data needed to be generated. Whilst trying to do this various issues between, windows, linux and WSL came up requiring various updates to emulator scripts and documentation. 

- Add shared mock users
- Update seed generation methods
- Refactor some script code out of functions into oa-scripts
- Refactor shared paths to oa-shared
- Add seed export zip function
- Add shared user seed methods
- Update docs

## Git Issues

Closes #

## Screenshots/Videos

**Updated seed data matches live site as of 1/10/2021**
image

**New default auth users populated**
image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by chrismclarke** [comment]
@patrycjapraczyk - It would be awesome if you'd be able to test/check this one (have sent a message on slack), but no worries if not.

**Comment by patrycjapraczyk** [comment]
@chrismclarke the emulator is not starting for me due to **_Did not find a Cloud Firestore rules file specified in a firebase.json config file._** error [](ur
Screenshot from 2021-10-04 22-33-48
l)

**Comment by chrismclarke** [comment]
Unsure what state this was left at and don't have time to resolve right now (hopefully can revisit with discussion of using docker for emulators which will likely resolve issue of incompatible os seed)

**Comment by chrismclarke** [comment]
Closing here as majority of changes included/improved on in https://github.com/ONEARMY/community-platform/pull/1501 and elsewhere

**Pull request closed without merging**
