### PR TITLE
feat: enforce character limits for how to steps (100 < 700)

### LINKED ISSUE #2511: feat: enforce character limits for how to steps (100 < 700)
Add validation to the how to steps when adding or updating a how to item.

- description minimum character length 100 characters
- description maximum character length 700 characters

Hint text should be updated accordingly.

Add a character counter to the description text in the step.

### PR DESCRIPTION
**Pull request by aaronguernsey**
PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

- Added validation to the how to steps when adding or updating a how to item.
  - Description minimum character length 100 characters
  - Description maximum character length 700 characters
- Hint text should be updated accordingly.
- Added a character counter to the description text in the step.

## Git Issues

Closes #2511

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by AlfonsoGhislieri** [comment]
Thanks for this @aaronguernsey, just jumping to say that we would prefer if contributors use `rebase` over `merge` in order to keep a cleaner history. 
https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase#:~:text=Rebase%20is%20one%20of%20two,has%20powerful%20history%20rewriting%20features.

**Comment by aaronguernsey** [comment]
> Thanks for this @aaronguernsey, just jumping to say that we would prefer if contributors use `rebase` over `merge` in order to keep a cleaner history. https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase#:~:text=Rebase%20is%20one%20of%20two,has%20powerful%20history%20rewriting%20features.

Absolutely, thanks for the heads up! I was mindlessly clicking the update branch without thinking to select `rebase`.

**Comment by aaronguernsey** [comment]
> Thanks for working on this @aaronguernsey and for adding the tests. I've made a few suggestions below, mainly ones that I think would aid readability.
> 
> Also, I was wondering whether you'd be up for maybe splitting the TextLimitIndicator / CharacterCount into a separate component so that we can reuse it with other text based fields? I think that would be really useful. If not then no worries and I'll add a new issue for that to our backlog.
> 
> Thanks again, it's great to have new contributors on board 🥇

@iSCJT Thanks for the comment and suggestions! I'd be happy to take a stab at splitting the `CharacterCount` into a separate component, and I will update according to your suggestions above.

Quick follow-up question: 

Much of the `TextLimitIndicator` / `CharacterCount` logic came from the `FieldInput` component. Should I update that component with the new `CharacterCount` component? Or would that be a separate task?

**Review by iSCJT — APPROVED** [review]
@aaronguernsey awesome, thank you for making those changes.  Refactoring the FieldInput component to use the new CharacterCount component would be great 👍  I'll create a new issue and assign it to you.

**Comment by iSCJT** [comment]
@aaronguernsey I can't assign you unless you interact with the issue in some way but here it is: https://github.com/ONEARMY/community-platform/issues/2598

Thanks again!

**Pull request merged**
