### PR TITLE
feat: add unsubscribe link in emails

### LINKED ISSUE #2863: [feature request] Easy unsubscribe from notifications emails
**Is your feature request related to a problem? Please describe.**
We want to make it easy to unsubscribe from notifications (without logging in)

**Describe the solution you'd like**
Add unsubscribe to bottom of email 

**Layout** 
afbeelding

**Notes** 
Pr is already submitted. 
https://github.com/ONEARMY/community-platform/pull/2783

### PR DESCRIPTION
**Pull request by evakill**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description
we want an unsubscribe link in the emails we send out to users to avoid spamming them unwantedly. this should ideally not require users to log in, in case they've lost their login info and don't want to reenter the platform.

the "quick and easy" solution i came up with is creating a new unsubscribe page that pulls the username from the URL and updates the user's profile to set their emailFrequency to "never". this will stop them from getting any more emails from the platform. 

this is not a high-security solution, but the risk of malicious users going around and unsubscribing people is... small. hopefully.

added a cypress test for the new page.

cc @davehakkens 

## Git Issues

Closes #2863

## Screenshots/Videos

unsubscribe page:
Screen Shot 2023-09-13 at 5 29 18 PM

new email template:
Screen Shot 2023-09-13 at 5 44 17 PM

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by davehakkens** [comment]
Works here!

**Comment by thisislawatts** [comment]
Given the security concerns you mentioned here I am reluctant to introduce this technical debt. I am wondering instead if there is a relatively small tweak we can make here that would greatly improve the security posture.

For example looking into `handlePendingEmailEntry`, we could make the following additions:

```ts
const uniqToken = uuid(); // or nano id 

// Adding emails to this collection triggers an email notification to be sent to the user
const sentEmailRef = await db.collection(DB_ENDPOINTS.emails).add({
  to: toUserEmail,
  message: getNotificationEmailTemplate(toUser, pendingNotifications, /* New argument */ uniqToken ),
  // New attributes
  userId: toUser.userName,
  uniqToken, 
})
```

The unsubscribe link could then be formatted as `https://community.preciousplastic.com/unsubscribe/{uniqToken}`

Application logic would then be:
1. Load unsubscribe view providing uniqToken in route param
1. Query `emails` collection filtering on uniqToken fetched from route
1. If matching email document found update associated user record based on userId.  

Open questions:
1. How long do messages persist in `emails` collection for?
1. Can we add additional attributes to documents in the emails collection or will it cause the extension to throw an error 🤔

**Comment by evakill** [comment]
ok, fair enough @thisislawatts. you can count on the security guy to not take shortcuts ;) 

> Can we add additional attributes to documents in the emails collection or will it cause the extension to throw an error?

not sure - docs don't say either way. i don't think we should deviate from the suggested schema, however, as the collection is tied to this extension. even if it works now, an update to the extension could possibly break it. i would rather update the user object with the unique token. the lookups would also be simpler, as we can still use the user store on the FE to get the token. 

i can make this update. i'm almost done with #2379 so will finish and put up a PR for that first then come back to this.

**Comment by evakill** [comment]
@thisislawatts ready for re-review

**Review by thisislawatts — APPROVED** [review]

**Pull request merged**
