### PR TITLE
add functions to manage user.stats.userCreatedComments

### LINKED ISSUE #3451: Discussions: Add user comments to the user.stats field
The ids of howtos and research created by a user are added to the user object (`user.stats.<something>`), please add comment ids from Discussions to a user.

### PR DESCRIPTION
**Pull request by goratt12**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Using Firebase Functions

* Add user created/edited comments to user.stats.userCreatedComments
* Remove on comment deletion

## Git Issues

Closes #3451

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by mariojsnunes — COMMENTED** [review]
looking good!

**Review by benfurber — APPROVED** [review]

**Comment by benfurber** [comment]
Nice one. Same comment about manual testing as the other one.

**Comment by goratt12** [comment]
Tested manually and working :)
image
image

**Comment by benfurber** [comment]
@goratt12 Now I've merged in your other branch, I think you've got some fun merge conflicts here now?

**Pull request merged**
