### PR TITLE
fix: spaceprofile visible tablist

### PR DESCRIPTION
**Pull request by Shalankwa**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix (fixes an issue)

## What is the current behavior?
SpaceProfile shows both 'Contributions' and 'Impact' tabs when empty

## What is the new behavior?
Both tabs are hidden if contributions haven't been made

image

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Git Issues
https://github.com/ONEARMY/community-platform/issues/3871

### CODE REVIEW

**Comment by Shalankwa** [comment]
Apologies but I'm not entirely sure which test module I should update for these changes.

**Comment by benfurber** [comment]
@Shalankwa Welcome! Thank you for the PR!

Yes please for the tests. 

Have a look at the 'Focus Workplace' spec on `packages/cypress/src/integation/settings.spec.ts` for the impact tab.

Have a look at the 'Create research article' spec on `packages/cypress/src/integation/research/write.spec.ts` for the impact tab.

**Comment by Shalankwa** [comment]
@benfurber

Are you away of any accounts within the test enviornment that has impact data I can reference?

I noticed that the issue requirements make it sound like 'contributions' and 'impacts' should be evaluated off the same logic (research+howto > 0), but impacts should be evaluated differently

**Comment by Shalankwa** [comment]
Test have been implemented.

I felt the 'profile.spec' was a better fit for testing this. To ensure all cases were covered I needed to add  some additional mock data.

If I didn't follow the proper approach to do so please let me know.

**Comment by benfurber** [comment]
Amazing, thank you @Shalankwa! Anything else on the board take your fancy? :)

**Comment by benfurber** [comment]
@all-contributors add @Shalankwa for code

**Pull request merged**
