### PR TITLE
Fix #964 "Create How-to" button for not-logged in

### LINKED ISSUE #964: "Create How-to" button for not-logged in
Hello,

Currently, as a not-logged-in user the user does not see the "Create How-to" button. 
image

I think this is a missed opportunity to engage with new users and ultimately achieve more signups and how-tos. I would propose to have the "Create How-to" button at any time and if the user is not logged in he/she gets redirected to https://community.preciousplastic.com/sign-up to create an account and eventually an how-to.

Hope it makes sense 🤙

### PR DESCRIPTION
**Pull request by alromh87**
When not logged in create how to button will redirect to create account

Updated with changes from master, sends no error on build

### CODE REVIEW

**Comment by BenGamma** [comment]
With #1036  and this PR did you had anything to add or was is just to update with master ?

**Comment by alromh87** [comment]
Just update to master, no conflicts

Feature mentions adding the same behavior for pin and howto wich is not imlemented

**Comment by alromh87** [comment]
Just update to master, no conflicts

Feature mentions adding the same behavior for pin and howto wich is not implemented

**Comment by BenGamma** [comment]
> Feature mentions adding the same behavior for pin and howto wich is not implemented

Can you be a bit more precise here ? How is the feature linked to pin ?

**Comment by davehakkens** [comment]
That the same button should be there for "map" and "events"
 https://github.com/ONEARMY/community-platform/issues/964

**Comment by alromh87** [comment]
If I understand correctly [this](https://github.com/ONEARMY/community-platform/issues/964#issuecomment-630083818), the button to add event and pin
Captura de pantalla de 2020-09-14 16-04-13

Captura de pantalla de 2020-09-14 16-04-21

**Comment by davehakkens** [comment]
correct

**Comment by BenGamma** [comment]
Ah yes, I pushed some changes and reopen #987. I still need to add the Map pin button.

Will close this one.
Now Alejandro have rights to create PR directly from the repo so hopefully there will be no more jump for PR to PR in the futur

**Pull request closed without merging**
