### PR TITLE
feat(question): add username and Ask-On date

### LINKED ISSUE #2958: [QuestionPage] Show Username

### PR DESCRIPTION
**Pull request by goratt12**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Add username and Ask-On date to question card
The code relies on the `creatorCountry` property of question, this property wasn't populated before this PR so only new questions will show county flags (older questions will show grey flag)

## Git Issues

Closes #2958

## Screenshots/Videos

image
image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by evakill — CHANGES_REQUESTED** [review]
hiya @goratt12!

there are 2 things that i would love to see happen in this PR - let me know what you think
 
1. we store `creatorCountry` on the resources because it saves us a DB lookup for each load. however, we need to make sure we keep it up to date if the user changes location. we do this with a firebase function triggered on user update. when the user's country changes, we call a function to update all of their posts with their updated country. you can find the code for this [here](https://github.com/ONEARMY/community-platform/blob/master/functions/src/userUpdates/index.ts#L66), and we'll need to add some logic to do the same update on questions as we do on research and howto.
2. this little flag + username + published on would be a great candidate for a global component, as it is used across all our modules. we don't have a ton of these, but a good example i can think of is `SortFilterHeader`. would you be game for converting this into a reusable component and adding it to How to, Research, and Questions? i think it would be a step in the right direction in terms of reusability!

**Comment by goratt12** [comment]
> hiya @goratt12!
> 
> there are 2 things that i would love to see happen in this PR - let me know what you think
> 
> 1. we store `creatorCountry` on the resources because it saves us a DB lookup for each load. however, we need to make sure we keep it up to date if the user changes location. we do this with a firebase function triggered on user update. when the user's country changes, we call a function to update all of their posts with their updated country. you can find the code for this [here](https://github.com/ONEARMY/community-platform/blob/master/functions/src/userUpdates/index.ts#L66), and we'll need to add some logic to do the same update on questions as we do on research and howto.
> 2. this little flag + username + published on would be a great candidate for a global component, as it is used across all our modules. we don't have a ton of these, but a good example i can think of is `SortFilterHeader`. would you be game for converting this into a reusable component and adding it to How to, Research, and Questions? i think it would be a step in the right direction in terms of reusability!

Hey! both sound good, I'll get on it :)

**Comment by goratt12** [comment]
I'm not sure I understand how [this function](https://github.com/ONEARMY/community-platform/blob/a65cce28a29c45a5692020372c2c253638b2f394/functions/src/userUpdates/index.ts#L66) is called.
I see that the function is called from this code: https://github.com/ONEARMY/community-platform/blob/a65cce28a29c45a5692020372c2c253638b2f394/functions/src/userUpdates/index.ts#L20-L26

Could you explain what how this works? 
How does the `id` in the ``${DB_ENDPOINTS.users}/{id}`` is changed and create a listener for every user?

**Comment by goratt12** [comment]
I think we should also update all the user comments, currently only on how-to but in the future also for question comments

**Comment by evakill** [comment]
> I'm not sure I understand how [this function](https://github.com/ONEARMY/community-platform/blob/a65cce28a29c45a5692020372c2c253638b2f394/functions/src/userUpdates/index.ts#L66) is called. I see that the function is called from this code:
> 
> https://github.com/ONEARMY/community-platform/blob/a65cce28a29c45a5692020372c2c253638b2f394/functions/src/userUpdates/index.ts#L20-L26
> 
> Could you explain what how this works? How does the `id` in the `${DB_ENDPOINTS.users}/{id}` is changed and create a listener for every user?

yep - firebase will run this function every time a user is updated. it sounds like a lot, but somehow under the hood firebase optimizes for this 🤷‍♀️

**Comment by goratt12** [comment]
What defines Firebase to set a listener for every user?
how does new users are handled?

**Comment by evakill** [comment]
> I think we should also update all the user comments, currently only on how-to but in the future also for question comments

yes good call! the function that does that is `updateUserCommentsInfo` in the same fire - you might have seen it - and would be great to add the updates for question comments in there as well

**Comment by evakill** [comment]
> I think we should also update all the user comments, currently only on how-to but in the future also for question comments

yes good call! the function that does that is `updateUserCommentsInfo` in the same fire - you might have seen it - and would be great to add the updates for question comments in there as well

> What defines Firebase to set a listener for every user? how does new users are handled?

here are the docs on the triggers - https://firebase.google.com/docs/functions/firestore-events 

we use `onUpdate` and `onCreate` quite a bit in the functions directory. every export from `functions/src/index.ts` is deployed as a firebase function. there are different types: triggers, scheduled functions, and HTTP requests, that can all be deployed with firebase functions

**Comment by goratt12** [comment]
> > What defines Firebase to set a listener for every user? how does new users are handled?
> 
> here are the docs on the triggers - https://firebase.google.com/docs/functions/firestore-events
> 
> we use `onUpdate` and `onCreate` quite a bit in the functions directory. every export from `functions/src/index.ts` is deployed as a firebase function. there are different types: triggers, scheduled functions, and HTTP requests, that can all be deployed with firebase functions

Oh I see, thanks for the explanation!

**Comment by goratt12** [comment]
> > I think we should also update all the user comments, currently only on how-to but in the future also for question comments
> 
> yes good call! the function that does that is `updateUserCommentsInfo` in the same fire - you might have seen it - and would be great to add the updates for question comments in there as well

I see that there is a Question Comments issue currently blocked - #2962.
The issue is blocked because there is a Discussion module coming up 🥳

I think we should wait with the comments updating for this PR and handle it in the Discussion module
What do you think?

**Comment by evakill** [comment]
> #2962

ah yes - sounds reasonable. i will add a comment to that issue as a reminder

**Review by evakill — APPROVED** [review]
everything looks great!! thanks @goratt12 🥳

**Pull request merged**
