### PR TITLE
fix: make simplified profile default

### PR DESCRIPTION
**Pull request by Kiebert**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Description

Make the simplified profile the default layout  

## Git Issues

https://github.com/ONEARMY/community-platform/issues/1506

### CODE REVIEW

**Review by thisislawatts — APPROVED** [review]

**Comment by thisislawatts** [comment]
Looks great, thank you @Kiebert for taking the time to work on this ✨

**Comment by davehakkens** [comment]
I dont think this goes according to plan. @thisislawatts @Kiebert 
It made all existing profiles a member.

Click [any workspace](https://community.preciousplastic.com/u/precious-plastic) on the map and it shows a simplified profile
afbeelding
afbeelding

**Comment by Kiebert** [comment]
Hello.
In the code there are the following types:
- 'member',
- 'space',
- 'workspace',
- 'machine-builder',
- 'community-builder',
- 'collection-point',

So 'space' and 'workspace' should show the 'SpaceProfile', and the others should show the 'MemberProfile'? 
Is the assumption correct @davehakkens?

**Comment by davehakkens** [comment]
They should all show the 'SpaceProfile'
Except members. They have a member profile.

**Comment by Kiebert** [comment]
Ok. That was original state. 
I will revert the code.

**Comment by davehakkens** [comment]
The main issue was that when users signup and didn't select a profiletype yet (not space or member) they got the layout of the 'SpaceProfile'. But it should show the 'MemberProfile'

**Comment by Kiebert** [comment]
Ok.  I get it. Added a comment to issue: https://github.com/ONEARMY/community-platform/issues/1506
For now, this PR reverts the code to the old situation: https://github.com/ONEARMY/community-platform/pull/1966

**Comment by davehakkens** [comment]
ok. thanks for taking on the issues! :)
You want to continue working on this one?

**Comment by Kiebert** [comment]
Yes please.

**Comment by Kiebert** [comment]
I added a profileType check to the outstanding pull request: https://github.com/ONEARMY/community-platform/pull/1966
If this profileType === undefined it will use the member profile.

**Pull request merged**
