### PR TITLE
WIP: Comments UI & components

### LINKED ISSUE #1127: Comments! 💬 (front end)
### Description

Time to start adding comments to the platform! This is a big thing, its the first time we allow community interaction!
You can find more information in our [V2 Document ](https://docs.google.com/document/d/1hyWc2a9cn04B107UzUKd4-12T5v0VrlWmYTa8KZnYhQ/edit) (page 8) -Nested replies are skipped for now.

### Task
This issue is to get the front end in place. The buttons and the styling. The other issue #1128  is for connecting the backend.

### Page related

Will be used in :

- https://community.preciousplastic.com/how-to/page

### Mockup

Overview
afbeelding

Comments box:
afbeelding

When logged in:
afbeelding

When not logged in:
afbeelding

### PR DESCRIPTION
**Pull request by tudi2d**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
**This is still WIP & will update. Let me know, if you have suggestions**

Add the components & UI for viewing & creating comments for HowTos.

## Git Issues

Closes #1127

## Screenshots/Videos

Design

image

### CODE REVIEW

**Comment by davehakkens** [comment]
hi @tudi2d. Looks neat! Is this one ready from your end?
Seems complete but not sure if something is missing..

**Comment by tudi2d** [comment]
Hi. Yes, ist complete - now both PRs have to be merged together. Would suggest a separate PR for that - could do that on the weekend.

**Comment by davehakkens** [comment]
Sweeet! You mean you can merge them together?

**Comment by tudi2d** [comment]
Yes - @chrismclarke can than review the final PR, to avoid duplicate work

**Pull request merged**
