### PR TITLE
fix: confirmation when navigating from a form

### PR DESCRIPTION
**Pull request by mariojsnunes**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Updated `usePrompt` to use `useBlocker` which should be more reliable.
I remember I had to do this change a few months ago on another project due to a chrome update.
Hopefully this will improve flaky tests.

## Git Issues

Closes #

### CODE REVIEW

**Comment by benfurber** [comment]
@mariojsnunes I'll rerun the tests but [this one looks related to your change](https://cloud.cypress.io/projects/4s5zgo/runs/5600/test-results/1fe48389-3e20-45cb-8d28-022f726d8e38)?

**Review by evakill — COMMENTED** [review]
hey @mariojsnunes, the updates to the `usePrompt` hook look good.
could you give more context into the changes to `src/pages/index.tsx`? looks like we're pulling in some new components from `react-router-dom`, which is fine, but want to understand the motivation for the changes, as this impacts our entire routing infrastructure!

also, i noticed one weird behavior while testing - when you refresh from the `how-to/create` page, you get a 404 page not found
Screenshot 2024-06-03 at 3 21 39 PM

**Comment by mariojsnunes** [comment]
Thanks for the reviews!

The routing changes can be done on a different PR.
Also want to do some package updates first.

**Comment by benfurber** [comment]
@mariojsnunes I'm happy to pick this up from you. What's still required to get this finished?

**Comment by mariojsnunes** [comment]
The aim of this PR was to remove flakyness of tests and futureproof browser support.

Not sure if it does any of that in the current state because the same tests are still flaky and the current solution seems to work fairly well on prod.

**Pull request closed without merging**
