### PR TITLE
Rebase/add notifications for mentions 2

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description
Refactor of #2014 to include changes from #1917
Includes minor updates to tests

## Git Issues

Closes #2014

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by chrismclarke** [comment]
Thanks @thisislawatts 
The changes look great to me. I had a slight issue with conflicts from the refactor in @1917 which were merged ahead of this, and so have tried rebasing onto #2014. 

If you get a chance can you take a quick look to see changes are as expected? I made sure to copy the specific userStore changes which have been refactored into the userNotificationsStore (https://github.com/ONEARMY/community-platform/pull/2021/commits/54487c73d9aa67130fc51913611e95d79482b2c6) and merged the unit tests you created with ones I had in that branch (https://github.com/ONEARMY/community-platform/pull/2021/commits/b87074751e9575332dd3de2dce7f5c2b3b7373fa)

So assuming you are happy with those two commits I think the rest should be fine.

@davehakkens - I haven't managed to functionally test this myself yet, if you have a chance to make sure things work as expected when running locally that would be super handy, otherwise likely I can try have a second pass tomorrow

**Comment by chrismclarke** [comment]
Actually found a way to quickly test on emulator version (swapping between admin and beta_tester users). Functionality looks really nice to me, particularly love the scrolling link and highlight box.

My only question is whether the user should see the `@@{demo_beta_tester:demo_beta_tester}` part of the comment - whether that is a new regression, or a future update or something just because I'm admin?

[Community Platform.webm](https://user-images.githubusercontent.com/10515065/206379626-1cbdbbe9-0aa5-4a91-9b20-02efefee476f.webm)

**Comment by davehakkens** [comment]
works here! Dont see the `@@{demo_beta_tester:demo_beta_tester}`
But also not using emulator to test but preview link with two accounts

**Comment by thisislawatts** [comment]
Sounds like a regression. It is unexpected for the user to see the `@@{demo_beta_tester:demo_beta_tester}` string. This is an internal representation which should not be exposed to users.

**Comment by chrismclarke** [comment]
Thanks for checking both, I expect a regex issue unrelated to this PR as some users work correctly and others don't
image

Will take a look as a follow-up pr. Otherwise I just need to fix a unit test and I'd say good to go

**Pull request merged**
