### PR TITLE
fix: friendly sign up validation errors

### PR DESCRIPTION
**Pull request by EdwardAndress**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

1. Yup wasn't being used to validate password length at sign-up so the error message shown came from Firebase and included some slightly technical terms that are not relevant to the user.
2. Some tests for (simple) sign-up validation failures were missing, so I've added those as part of this work.

In working on this, I have noticed that `FRIENDLY_MESSAGES` are not being used very much. I was tempted to sort that out one way or another (either by increasing their use or removing them) but I felt that is probably another piece of work. I am open to your thoughts on that :)

## Git Issues

Closes 3412

## Screenshots/Videos

Error from firebase...

an image showing the error from firebase

Custom error from Yup...

an image showing the custom error from Yup

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by EdwardAndress** [comment]
Locally, the linter complains about all these files...

Checking formatting...
[warn] shared/lib/index.d.ts
[warn] shared/lib/index.js
[warn] shared/lib/messages.d.ts
[warn] shared/lib/messages.js
[warn] shared/lib/mocks/auth/index.d.ts
[warn] shared/lib/mocks/auth/index.js
[warn] shared/lib/mocks/auth/users.d.ts
[warn] shared/lib/mocks/auth/users.js
[warn] shared/lib/mocks/data/categories.d.ts
[warn] shared/lib/mocks/data/categories.js
[warn] shared/lib/mocks/data/discussions.d.ts
[warn] shared/lib/mocks/data/discussions.js
[warn] shared/lib/mocks/data/howtos.d.ts
[warn] shared/lib/mocks/data/howtos.js
[warn] shared/lib/mocks/data/index.d.ts
[warn] shared/lib/mocks/data/index.js
[warn] shared/lib/mocks/data/mappins.d.ts
[warn] shared/lib/mocks/data/mappins.js
[warn] shared/lib/mocks/data/questionCategories.d.ts
[warn] shared/lib/mocks/data/questionCategories.js
[warn] shared/lib/mocks/data/questions.d.ts
[warn] shared/lib/mocks/data/questions.js
[warn] shared/lib/mocks/data/research.d.ts
[warn] shared/lib/mocks/data/research.js
[warn] shared/lib/mocks/data/tags.d.ts
[warn] shared/lib/mocks/data/tags.js
[warn] shared/lib/mocks/data/users.d.ts
[warn] shared/lib/mocks/data/users.js
[warn] shared/lib/mocks/index.d.ts
[warn] shared/lib/mocks/index.js
[warn] shared/lib/models/common.d.ts
[warn] shared/lib/models/common.js
[warn] shared/lib/models/db.d.ts
[warn] shared/lib/models/db.js
[warn] shared/lib/models/howto.d.ts
[warn] shared/lib/models/howto.js
[warn] shared/lib/models/index.d.ts
[warn] shared/lib/models/index.js
[warn] shared/lib/models/maps.d.ts
[warn] shared/lib/models/maps.js
[warn] shared/lib/models/notifications.d.ts
[warn] shared/lib/models/notifications.js
[warn] shared/lib/models/research.d.ts
[warn] shared/lib/models/research.js
[warn] shared/lib/models/user.d.ts
[warn] shared/lib/models/user.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?

I don't think I have touched any of them

**Review by benfurber — CHANGES_REQUESTED** [review]
@EdwardAndress thank you so much for your first (of I hope many) contributions!

A nice tidy up, thanks!

Unfortunately we can rely on randomly generated css class names in the tests. I believe `cy.get('[data-cy=error-msg]')` will give you the erorrs container.

Second, rather than seperate describes/it's, I think it's better for these feature tests to have them as steps in the existing 'create new account' test before the sucessful account creation in that test.

Make sense?

**Comment by EdwardAndress** [comment]
Thanks @benfurber - that all makes sense. I will make your suggested changes 👍

**Comment by EdwardAndress** [comment]
@benfurber – for clarity, are you suggesting that I add 'everything' (with some tweaks) into this one `it` block?

```
 it('create new account', () => {
    fillSignupForm(newUser)
    cy.get('[data-cy=submit]').click()
    cy.url().should('include', 'sign-up-message')
    cy.get('div').contains('Sign up successful').should('be.visible')
    cy.get('[data-cy=user-menu]')
  })
```

**Comment by benfurber** [comment]
@EdwardAndress I'd say it's pretty common for feature tests to have multiple steps/workflows. These are problems the user could experience on their journey to a sucessful sign-up so I'd say they're part of that test.

**Comment by EdwardAndress** [comment]
@benfurber – unchecking / checking the consent checkbox was necessary because the field validation errors only appear once focus has been changed to another field. I wouldn't normally add comments but if you feel it's needed I can add one. Also, let me know if this wasn't how you had imagined the steps being used and I'll change it.

**Comment by benfurber** [comment]
Fantastic, thank you @EdwardAndress! I think we're about there, just running the formatter and rebase master and I can merge this in.

**Comment by EdwardAndress** [comment]
> Fantastic, thank you @EdwardAndress! I think we're about there, just running the formatter and rebase master and I can merge this in.

Are you asking me to do something?

**Comment by benfurber** [comment]
@EdwardAndress Ha, yes, apologies for my typo! 

Can **you** please run the formatter and rebase. The formatter command is `yarn format`.

**Comment by EdwardAndress** [comment]
@benfurber - formatter and rebasing done ✅

**Review by benfurber — APPROVED** [review]

**Comment by benfurber** [comment]
@all-contributors add @EdwardAndress for code

**Pull request merged**
