### PR TITLE
chore: add linting for commit messages

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Developer experience (targets the way that contributing to the project works)

## Description

As part of the `commit-msg` hook validate the stucture of the commit message to ensure that it is well formed. This change will allow us to parse the commit messages programmatically to generate release notes. 

More information:
* https://github.com/conventional-changelog/commitlint/#what-is-commitlint

In addition:

* Updates husky to the latest version 1.x => 7.x
* Moves [lintstaged](https://www.npmjs.com/package/lint-staged) configuration to dedicated file. 

This has no impact on the user facing software and only affects the developer workflow. 

[Why Use Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#why-use-conventional-commits)

- Automatically generating CHANGELOGs.
- Automatically determining a semantic version bump (based on the types of commits landed).
- Communicating the nature of changes to teammates, the public, and other stakeholders.
- Triggering build and publish processes.
- Making it easier for people to contribute to your projects, by allowing them to explore a more structured commit history.

### CODE REVIEW

**Review by chrismclarke — CHANGES_REQUESTED** [review]
This one makes me slightly nervous, I see the clear value but also it makes it harder for people who want to contribute if they're not used to writing commits in such an opinionated way.

Would the linting throw warnings or errors? Is there a way we could make this opt-in to start with and slowly encourage (and/or put to a vote on a monthly call?)

**Comment by thisislawatts** [comment]
@chrismclarke Happy to raise this in tomorrow's call for a vote. I think you're right that we should probably add some documentation to the project which introduces new contributors to the formatting standards.

Here's an example of the output from `commitlint` when it fails during the git hook.

```bash
$ git commit -m "poorly formatted commit"
No staged files match any of provided globs.
⧗   input: poorly formatted commit
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

**Review by chrismclarke — CHANGES_REQUESTED** [review]
So I ended up down a bit of a rabbit hole trying to review this one. There were a couple immediate issues I noticed:

1) The husky postinstall hook doesn't work with yarn v2 (workaround here: https://typicode.github.io/husky/#/?id=yarn-2)

2) Once up and running I wasn't a huge fan of the error messages. There wasn't a clear way to edit them (although after some deep dive found a way to add a custom formatter)

3) If committing via on windows there are errors on windows trying to call the husky hook (workaround here: https://typicode.github.io/husky/#/?id=yarn-on-windows)

I addressed the postinstall hook and windows issues in another branch and created a PR to this one https://github.com/ONEARMY/community-platform/pull/1397

I also made a few additions to the config, notes in PR. Let me know what you think and how you want to proceed

**Comment by thisislawatts** [comment]
I am happy to close to PR and defer to your branch.

**Pull request closed without merging**
