### PR TITLE
add comments editing

### LINKED ISSUE #1171: Add edit feature in comments
### Description
Currently, comments can be deleted but not edited. Editting is essential for us.
Clicking edit takes you back to the text editor. Publishing date stays unchanged but a little note `edited` is added.

1. Add "edit" and "delete" to the bottom of the comment
2. Show if a message is edited `(edited)`

### Page related
https://dev.onearmy.world/how-to

### Mockup
4_comments_edit_clean
5_comments_edit

### PR DESCRIPTION
**Pull request by danitrod**
PR Checklist

- [X] - Latest `master` branch merged
- [X] - PR title descriptive (can be used in release notes)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Adds editing possibility for user owned comments. Also added a confirmation prompt for deleting comments.

## Git Issues

Closes #1171

## Screenshots/Videos

Captura de Tela 2021-06-14 às 23 41 21

### CODE REVIEW

**Comment by davehakkens** [comment]
nice. Really like how it works with the popup!
Is it possible to make the width of the box 600PX instead of 300. (resize on mobile)
For the rest all cool :)

**Comment by danitrod** [comment]
done :) 
I remember we talked about making the comment be added from a button, rather from the enter key press, in the last meeting. Have you decided if we should do that? If so, I can add it to this PR too I guess

**Comment by davehakkens** [comment]
nice. Yes we have this issue https://github.com/ONEARMY/community-platform/issues/1170. @tudi2d said he wanted to take on, but perhaps easier for you while you are at it?

**Comment by tudi2d** [comment]
Go for it, if you want to - won't have time until next week to work on it :)

**Comment by danitrod** [comment]
Ohhh sorry hadn't noticed that we had issue, go ahead @tudi2d no worries!

**Review by chrismclarke — APPROVED** [review]
Looks good to me! Really like the modal popup (good to have the option of fixing the width too).
We might want to try add the same character limit counter at some point but for now definitely seems to do the job

**Pull request merged**
