### PR TITLE
fix: #2109-Change the discord link in Join our Chat

### LINKED ISSUE #2109: [bug] Discord link expired
**Describe the bug**
For some reason the "join our chat" link to Discord is expired.
Would need to be replaced
Old url: https://discord.com/invite/cGZ5hKP
New url: https://discord.gg/gJ7Yyk4

afbeelding

**To Reproduce**
Steps to reproduce the behaviour:

1. go to the platform on desktop
2. Click the button "join our chat"

### PR DESCRIPTION
**Pull request by adityakanu**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_
Fixes the expired Discord Link in the  Join our Chat. It was replaced with an updated link.
## Git Issues

Closes #2109

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by evakill — APPROVED** [review]
thank you!

**Comment by adityakanu** [comment]
> thank you!

This marks my first Open source contribution(although I don't know if this got merged successfully? these checks don't look good) Thank you for assigning it to me.

**Comment by evakill** [comment]
ah, yes. please change your commit message to fit the conventional commits format 
```
Commit needs to be formatted as conventional commit

<type>[optional scope]: <description>

Changed the discord link in the Join our Chat
✖   subject may not be empty
Changed the discord link in the Join our Chat
✖   type may not be empty


run `yarn commit` for interactive prompt or see examples at
https://www.conventionalcommits.org
```
i.e. Chore: Changed the discord link in the Join our Chat

**Comment by adityakanu** [comment]
> ah, yes. please change your commit message to fit the conventional commits format
> 
> ```
> Commit needs to be formatted as conventional commit
> 
> <type>[optional scope]: <description>
> 
> Changed the discord link in the Join our Chat
> ✖   subject may not be empty
> Changed the discord link in the Join our Chat
> ✖   type may not be empty
> 
> 
> run `yarn commit` for interactive prompt or see examples at
> https://www.conventionalcommits.org
> ```
> 
> i.e. Chore: Changed the discord link in the Join our Chat

I have done it. Please check

**Comment by adityakanu** [comment]
> ah, yes. please change your commit message to fit the conventional commits format
> 
> ```
> Commit needs to be formatted as conventional commit
> 
> <type>[optional scope]: <description>
> 
> Changed the discord link in the Join our Chat
> ✖   subject may not be empty
> Changed the discord link in the Join our Chat
> ✖   type may not be empty
> 
> 
> run `yarn commit` for interactive prompt or see examples at
> https://www.conventionalcommits.org
> ```
> 
> i.e. Chore: Changed the discord link in the Join our Chat

oh, wait I found another check failed. Let me correct that

**Comment by adityakanu** [comment]
> ah, yes. please change your commit message to fit the conventional commits format
> 
> ```
> Commit needs to be formatted as conventional commit
> 
> <type>[optional scope]: <description>
> 
> Changed the discord link in the Join our Chat
> ✖   subject may not be empty
> Changed the discord link in the Join our Chat
> ✖   type may not be empty
> 
> 
> run `yarn commit` for interactive prompt or see examples at
> https://www.conventionalcommits.org
> ```
> 
> i.e. Chore: Changed the discord link in the Join our Chat

Sorry for so many errors, but I think I changed the commit message to match the conventional format, and it is yet failing. Please help.

**Comment by davehakkens** [comment]
Can be a bit of a struggle to change the commit message @adityakanu 
Could also delete PR and raise a new one with the correct lint message. 
Might be easier for now

**Comment by adityakanu** [comment]
> Can be a bit of a struggle to change the commit message @adityakanu Could also delete PR and raise a new one with the correct lint message. Might be easier for now

Done @davehakkens, hope this will work.

**Pull request closed without merging**
