### PR TITLE
feat: add vertical categories to questions

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Feature (adds functionality)

## What is the current behavior?

Border category dropdown

## What is the new behavior?

The shiniest of toggles. 

Screenshot 2024-12-19 at 11 27 14

Screenshot 2024-12-19 at 11 26 54

## Git Issues

Part of #4003

### CODE REVIEW

**Comment by davehakkens** [comment]
for this one the content first need to be categorised and icons made before being released

**Review by mariojsnunes — APPROVED** [review]

**Comment by benfurber** [comment]
@davehakkens 'Moulds', 'machines' and 'other' are there so it's just 'Beyond Plastic' that's needed.

**Comment by benfurber** [comment]
@davehakkens Plus maybe a new category for all the V5 questions? Like, 'Organising' or something?

**Comment by davehakkens** [comment]
@benfurber We never made proper categories for PP questions.
I suggest to:
1. Change 'products' for 'recycling' as it broadens the category and involves any part of the making process (which has a lot of questions)
2. Remove beyond plastic (it only has 1 question ( Add the category if more questions pop up in 'other')
3. Add 'from the team' for the current V5 questions + upcoming ones until we have a news module. (organising sounded nice as well but can be mixed with users questions like 'want to organise an event for...' )
imag
[Icons Questions.zip](https://github.com/user-attachments/files/18204075/Icons.Questions.zip)
e

**Comment by benfurber** [comment]
Screenshot 2024-12-20 at 10 43 55

**Comment by benfurber** [comment]
Changes to prod data I'll make then merge this in:

1. Add a new From the Team category.
2. Change the five questions with Beyond Plastic category to Other
3. Delete the Beyond Plastic category.
4. Change the label of the Products category to Recycling.
5. Update the category label on the five product questions.
6. Change the questions with 'V5' in the title to the From the Team category.

**Pull request merged**
