### PR TITLE
fix: changed discord link in join our chat

### LINKED ISSUE #2109: [bug] Discord link expired
**Describe the bug**
For some reason the "join our chat" link to Discord is expired.
Would need to be replaced
Old url: https://discord.com/invite/cGZ5hKP
New url: https://discord.gg/gJ7Yyk4

afbeelding

**To Reproduce**
Steps to reproduce the behaviour:

1. go to the platform on desktop
2. Click the button "join our chat"

### PR DESCRIPTION
**Pull request by adityakanu**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Replaced the expired Discord invite link with new link in Join Our Chat.

## Git Issues

Closes #2109

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by adityakanu** [comment]
Sorry for so many disturbances @davehakkens, I did this PR from start. I hope this resolves it.

**Comment by evakill** [comment]
hm... not sure why prettier is angry now. could you run `yarn run prettier --write  src/pages/index.tsx` and commit any changes?

**Comment by evakill** [comment]
> Yeah, I did it. Should I write any new commit message or just copy the previous commit message?

if it were me, i would write something like `fix: run prettier` - as long as the commit message describes the changes in that commit and follow the conventional commit format, should be good to go!

**Comment by adityakanu** [comment]
> > Yeah, I did it. Should I write any new commit message or just copy the previous commit message?
> 
> if it were me, i would write something like `fix: run prettier` - as long as the commit message describes the changes in that commit and follow the conventional commit format, should be good to go!

Done 👍

**Comment by evakill** [comment]
worked! thanks for your contribution @adityakanu :)

**Pull request merged**
