### PR TITLE
fix: open links in new tab

### LINKED ISSUE #1619: Links open in new tab?
Would be really great to make links target="_blank" to open in new window.

 
target blank

### PR DESCRIPTION
**Pull request by tedspare**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description

- Implements behaviour proposed in #1619
- Parses in-content links with [react-linkify](https://tasti.github.io/react-linkify/) and adds the `target="_blank"` attribute so they open in a new tab
- Applies to how-to descriptions, how-to steps, research descriptions, and research updates
- Based on [this approach](https://github.com/ONEARMY/community-platform/pull/1639/files#diff-7aab05b5c350e50591b3ebe276a7734835df27cdd7b6e1f8f607576f2023cbddR76) for how-to comments and research comments in #1639

## Git Issues

Closes #1619

## Screenshots/Videos

Examples
- [How-to description and step](http://localhost:3000/how-to/test-links-in-description-and-step)
- [Research description](http://localhost:3000/research/test-test)
- Research update: could you, kind reviewer, test this one? 😅 (I couldn't figure out how)

image

### CODE REVIEW

**Comment by davehakkens** [comment]
works perfect here. Thanks for the fast PR!
(testing how-to can be tricky because an admin first need to approve them to be published. Until then they are "awaiting moderation")
afbeelding

**Review by thisislawatts — APPROVED** [review]

**Comment by thisislawatts** [comment]
Thanks for the PR @tedspare, this looks good to me. Please note that you're need to adjust the commit message so that it is formatted as `feat: open links in new tab from how-to, research update, and their comments`

Read more about the commit standards here: https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide

**Comment by tedspare** [comment]
thanks for catching that! Amended, and I'll know next time. 
 > Sent from <a href='https://neat.run?ref=gh_footer'>Neat</a>

**Review by thisislawatts — APPROVED** [review]

**Comment by davehakkens** [comment]
Thanks for the PR @tedspare 
Let me know if you want to take on another one :)

Optionally we have this one open https://github.com/ONEARMY/community-platform/issues/1610
So far non of the issues in the thread are fixed. They can be improved freestyling it using basic responsive logic to make sure its not terrible anymore. hehe

**Pull request merged**
