### PR TITLE
[feature request] align research filter section with how-to

### LINKED ISSUE #2480: [feature request] align research filter section with how-to
### Description

We want to align the research filter section with the how-to's
This could be seen as 3 different things to do.
1. Add a "sort by" dropdown that filters on `most useful`, `most comments`, `most updates` and `latest`
2. Add a search bar
3. Move `add research` button to the right. 

### Page related

Will be used in : [Research overview](https://community.projectkamp.com/research)
Similair to the [How-to overview](https://community.preciousplastic.com/how-to)

### Mockup

Update research layout

### PR DESCRIPTION
**Pull request by BaltacMihai**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

I tried to bring the Research page to the shape of the How-to page. That is, I added 2 new fields: one for search and another for Sort

## Git Issues

Closes #2480

## Screenshots/Videos

The version after the changes
image

### CODE REVIEW

**Comment by thisislawatts** [comment]
@BaltacMihai it would be great to introduce some tests which validate this functionality, do you have a preference around introducing these either with Cypress or jest?

**Comment by AlfonsoGhislieri** [comment]
I also thought the idea here was to unite this with the howto filtering? Making a reusable component and maybe some transferable back end logic as well.

I don’t think we should have two similar sets of logic and front end for the same functionality. 

Thoughts @thisislawatts ?

**Comment by BaltacMihai** [comment]
@thisislawatts  Also looking at the tests from howto.store. I think I will go with the Jest, to have a linearity.

@AlfonsoGhislieri Yes, I am of the same opinion, at the moment I wanted to integrate the functionalities both in the backend and frontend to understand what similarities we have. This is also the reason why I left PR in the draft, because I am trying to work on the clean code part.

Instead, what should I focus on first? On unit tests or on clean code? I think that the priority is to do the clean code part.

**Comment by davehakkens** [comment]
Thanks @BaltacMihai. Works really well!
Another tiny remark.
On mobile it could use some extra margin so filters don't touch eachother
afbeelding

**Review by thisislawatts — APPROVED** [review]

**Pull request closed without merging**
