### PR TITLE
feat(profile): added a text component to settings

### LINKED ISSUE #1870: Profile Settings UX rework
**Issue**
Many users create their accounts but don’t update their infos resulting in incomplete/spam accounts diminishing the overall UX on the Community Platform. 
image3

**Solution**
There are probably multiple solutions to tackle this problem. With this issue we want to improve the overall UX of the user settings page to make sure anyone that makes it to their settings is able to complete their profile with as little effort and frustration as possible.

**Current behavior**
“Save profile” button is greyed out (not clickable) by default until users input all fields correctly. There is no indication of what fields are mandatory (beyond a little star*), what fields are missing or mistaken for completing the profile. This might leave many users confused on what they have to do to complete their account. 
image6

**Proposed behavior**
“Save profile” button is enabled at all times (even when editing settings). When user clicks “Save profile” there are two possible outcomes:

1. Success. All mandatory fields are filled correctly and profile is saved. This triggers:
a. Success message
image2

2. Error. Some mandatory fields are missing or wrong. This triggers 2 things happen:
a. Missing/wrong fields become red + alert text (change to "Make sure this field is filled correctly.") using [this](https://onearmy.github.io/community-platform/storybook-static/index.html?path=/story/base-components-input--error) component
image5
b. Error message below “Save profile” button
image4

This is kind of a big issue so if you have any questions feel free to comment or reach out. 
Big up ✌️

### PR DESCRIPTION
**Pull request by ThakurKarthik**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Always Enabling profile save button and show form submit message when success or failure.

## Git Issues

Closes #1870 

## Screenshots/Videos

image

### CODE REVIEW

**Comment by thisislawatts** [comment]
Thanks for sharing the work so far @ThakurKarthik, looks good! I would recommend looking into the underlying ThemeUI library which provides an Alert component. We can then introduce two variants; success and error to represent these different states. This would then extract the styling from `FormSubmitResult.tsx` to a reusable configuration we can introduce elsewhere. ✨ 

Let me know if you've any questions on the suggested approach.

**Comment by ThakurKarthik** [comment]
Ah, do you mean this component https://theme-ui.com/components/alert ? If I am understanding it correctly we want to use this component, and move the colors / styles related to success & error to a different location, sorry I am not that familiar with theme ui but the docs mentions somethingn like that I guess. Anyway I am happy to change it on your reply to this.

**Comment by thisislawatts** [comment]
That's right @ThakurKarthik, you'd need to extend the Theme definitions in each of these locations to add an `alert` property:
* https://github.com/ONEARMY/community-platform/blob/master/src/themes/project-kamp/styles.ts#L199
* https://github.com/ONEARMY/community-platform/blob/master/src/themes/precious-plastic/styles.ts#L199
* https://github.com/ONEARMY/community-platform/blob/master/src/themes/fixing-fashion/styles.ts#L199


Future work would be to introduce a base theme definition and remove some of this duplication. :)

**Comment by ThakurKarthik** [comment]
> That's right @ThakurKarthik, you'd need to extend the Theme definitions in each of these locations to add an `alert` property:
> 
> * https://github.com/ONEARMY/community-platform/blob/master/src/themes/project-kamp/styles.ts#L199
> * https://github.com/ONEARMY/community-platform/blob/master/src/themes/precious-plastic/styles.ts#L199
> * https://github.com/ONEARMY/community-platform/blob/master/src/themes/fixing-fashion/styles.ts#L199
> 
> Future work would be to introduce a base theme definition and remove some of this duplication. :)

I have moved the styles to the theme styles location. Please review it.

**Comment by thisislawatts** [comment]
This looks great @ThakurKarthik, thanks for addressing the feedback ✨

**Review by thisislawatts — APPROVED** [review]

**Comment by thisislawatts** [comment]
I've approved the approach, however you will need to address the automated checks before this will be mergeble.

Consider squashing the 3 existing commits into a single commit that clearly communicates the changes introduced. Making sure to observe the [commit style guide](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide).

**Comment by thisislawatts** [comment]
Thanks @ThakurKarthik, I have been away from the internet for a few days. Let me take a look and get back to you.

**Comment by thisislawatts** [comment]
@ThakurKarthik, based on the failing tests would you be able to format the code? You can use the `yarn format` command to do this.

**Comment by ThakurKarthik** [comment]
@thisislawatts I have pushed my changes

**Comment by thisislawatts** [comment]
These test failures look consistent @ThakurKarthik, but I haven't yet been able to recreate them locally. I will take a further look at this but it won't be until the weekend. Thanks for your patience.

**Comment by thisislawatts** [comment]
Thanks @ThakurKarthik, I ended up pushing a branch with your work and adding a commit to adjust the Cypress selector to bypass the test failure. 

I have no good answers at the moment on _why_ this flaked as a result of the changes introduced in this PR.

Closed via #1907

**Comment by thisislawatts** [comment]
@all-contributors add @ThakurKarthik for code

**Comment by thisismattia** [comment]
Hey @ThakurKarthik thanks for this, already looking really great. Few small issues:

1. The alert box font color should be black
Screenshot 2022-09-06 at 05 41 51
2. Alert text boost up font size to 12px
3. Would also be great if the text wouldn't break but stays on one line
Screenshot 2022-09-06 at 05 29 09
4. Contacts and links only need the first alert text
Screenshot_2022-09-06_at_05_29_02
5. On collection opening time would be better if the text was aligned vertical-left to avoid layout being messed up. 
Screenshot_2022-09-06_at_05_30_59
6. There seem to be 2 types of alert text? Would be great to just have one. Could we either remove this one or style it to look like the other smaller one?
Screenshot 2022-09-06 at 05 30 01

That should be it for now, thanks!

**Pull request closed without merging**
