### PR TITLE
fix: allcontributors doesnt skip ci

### PR DESCRIPTION
**Pull request by AlfonsoGhislieri**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

As noticed in #2227 there is an issue as the bot skips ci in its commit messages but in doing so this breaks the ability to merge as CI is required.

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by thisislawatts** [comment]
I think the issue here is the GitHub configuration. If CI has been skipped then it should be possible to not have the associated checks as required. 

However that seems like a known product gap in GitHub based on this documentation. A weird workaround here:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

My preference would be NOT to spin up our CI infrastructure for PRs which don't need it.

**Review by thisislawatts — APPROVED** [review]

**Comment by AlfonsoGhislieri** [comment]
This is definitely a weird one, I also saw this workaround but wasn't sure how it could be implemented with circle ci. I agree that ideally we don't want to spin up the CI when it's not necessary. How was this dealt with before, I noticed the bot has pushed plenty of commits in the past.

**Comment by thisislawatts** [comment]
@AlfonsoGhislieri I guess previously I had access to merge without required checks passing.

**Comment by AlfonsoGhislieri** [comment]
Ah right, so that could also be another solution (easiest probably).

**Pull request merged**
