### PR TITLE
feat: more information in Follower notifications

### LINKED ISSUE #2922: [feature request] more information in Follower notifications
**Is your feature request related to a problem? Please describe.**
The notification "$person posted an update on a research you follow" is annoying because it lacks information about which specific research the update pertains to. Additionally, it sends a new notification for an edit made very shortly after the initial message, which can be confusing.

Screenshot_from_2023-10-18_20-26-55

**Describe the solution you'd like**
I would like the notification message to specify the research topic that the person has posted an update to. This will help users quickly identify the relevance of the update without needing to dig deeper.

**Additional context**
Being informed about research updates is useful, but it's equally important to immediately understand the context of these updates. Enhancing the clarity of notifications can lead to a more user-friendly experience.

### PR DESCRIPTION
**Pull request by AltinGruda**
PR Checklist

- [ x ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

The notification message specifies the research topic that the person has posted an update, commented, or found useful.  Messages are based on suggestions that were being discussed.

## Git Issues

Closes #2922

## Screenshots/Videos
notifications-1
notifications-2

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by davehakkens** [comment]
Hey thanks for looking into this!
Text seems good.
Would this also modify the notifications triggered in emails?
And if I get it correct this is only for research module right? (not how-to or mentions)

**Comment by AltinGruda** [comment]
> Hey thanks for looking into this! Text seems good. Would this also modify the notifications triggered in emails? And if I get it correct this is only for research module right? (not how-to or mentions)

Hey, thank you for commenting! This is my first time contributing so this is new to me.
This is only for the research module right now. But I am willing to work on other modules such as how-to or mentions in the future if needed. 
Would this modify the notifications triggered in emails? I don't really know, I did not touch any other module rather than the research one.

**Comment by AlfonsoGhislieri** [comment]
Thanks for this @AltinGruda, just following up here as I saw the issue was under discussion. And we would to extend it to something like shown in https://github.com/ONEARMY/community-platform/issues/2922#issuecomment-1773929803 

What are we thinking @davehakkens ?

**Review by AlfonsoGhislieri — APPROVED** [review]
Looks good to me! Thanks :)

**Comment by davehakkens** [comment]
hey @AltinGruda your PR seems to be working nice, thanks. Would you be up for extending this to our other notifications as well? Then we will make the issues

**Pull request merged**
