### PR TITLE
(DRAFT) Comment Textarea UI Improvements

### PR DESCRIPTION
**Pull request by elideg**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Our current "Submit a comment" UI falls short when viewing on mobile devices. 

## Git Issues

Closes [#3655](https://github.com/ONEARMY/community-platform/issues/3656)

## Screenshots/Videos

In-progress UI:

Screenshot 2024-06-19 at 10 47 46 PM
Screenshot 2024-06-19 at 10 47 43 PM
Screenshot 2024-06-19 at 10 47 35 PM

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by elideg** [comment]
Still need to setup ESLint in my IDE, will fix the messed up formatting in a later commit. I just wanted to place this here for discussion purposes as I'm using some patterns I want input on.

**Comment by benfurber** [comment]
Exciting work @elideg, thank you. Looking forward to seeing it finished!

**Comment by davehakkens** [comment]
Are you able to finish this one @elideg?
Would be a very nice one to merge in!

**Comment by benfurber** [comment]
Hey @elideg, as we haven't heard from you for a while I'm going to close this PR and unassign you from the ticket. Would love it if you were able to contribute in the future though. :)

**Pull request closed without merging**
