### PR TITLE
docs: update md-style-guide.md

### PR DESCRIPTION
**Pull request by MIfoodie**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Adds more information on when to use admonitions.

### CODE REVIEW

**Comment by chrismclarke** [comment]
Thanks for trying to reopen this one @MIfoodie , I can see each time it's kept the original commit which is why the lint errors are failing.

I should have been clearer, I think you would have needed to first set your code editor back to the master branch, and then created a new branch from there (to have a clean history). Then you would need to manually copy/paste the text edits. 

Want to give things one final try? Otherwise I can manually push the edits onto a clean branch and edit the commits if that doesn't work.

**Review by chrismclarke — CHANGES_REQUESTED** [review]
Thanks for trying to reopen this one @MIfoodie , I can see each time it's kept the original commit which is why the lint errors are failing.

I should have been clearer, I think you would have needed to first set your code editor back to the master branch, and then created a new branch from there (to have a clean history). Then you would need to manually copy/paste the text edits.

Want to give things one final try? Otherwise I can manually push the edits onto a clean branch and edit the commits if that doesn't work.

**Comment by MIfoodie** [comment]
If you could manually do it that would be great!

**Comment by chrismclarke** [comment]
Sorry for the slow response. I've simplified the changes a little as I realise they're covered better in the official documentation, and moved into #2106 so will close here and merge from there. Thanks for the contribution!

**Pull request closed without merging**
