### PR TITLE
fix: add support for ff member types on map

### LINKED ISSUE #1731: [bug] Fixing Fashion Map shows wrong spaces
**Describe the bug**
The map for Fixing Fashion isntance still shows the Precious Plastic spaces.
It should show the ones from Fixing Fashion
- Member
- Space

**Screenshots**
afbeelding

### PR DESCRIPTION
**Pull request by thisislawatts**
Closes https://github.com/ONEARMY/community-platform/issues/1731

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Git Issues

Closes #1731

### CODE REVIEW

**Comment by davehakkens** [comment]
Looks good. But the icons don't seem correct, sorry didnt spot this before. 
We use different badges (avatars) when showing them in small size
[Member Icon](https://github.com/ONEARMY/community-platform/blob/master/src/assets/images/themes/fixing-fashion/avatar_member.svg)
[Space Icon](https://github.com/ONEARMY/community-platform/blob/master/src/assets/images/themes/fixing-fashion/avatar_space.svg)

Also on mobile it says "others", would be better if that was not there...
afbeelding

**Comment by thisislawatts** [comment]
@davehakkens, I've pushed an update to ensure the correct badges are being loaded. 

Regarding the other point around the hanging _others_ title for the mobile filters, I would prefer to iterate on that in a separate PR. The work [I flagged to @kfern here](https://github.com/ONEARMY/community-platform/issues/1197#issuecomment-1153105097) would likely be the best place to address this behaviour so I don't want use to tread on each other toes here.

**Comment by davehakkens** [comment]
nice, thanks!
Just double checking to make sure it doesn't belong in this PR.
Since it does seem somewhat related to theming, because the "others" filter does work for other instances like Precious Plastic when there are multiple pins
afbeelding

Just wanted to give that piece of information. Will trust your judgement though 
Happy to merge and no problem if we iterate on it later!

**Comment by thisislawatts** [comment]
It _could_ be done in this PR but the core issue is around the datastructure used to populate the dropdown. This is something which also needs to be resolved to support the `Verified` option which we want to appear without a group heading. I have a few open threads/PRs open so would rather defer this work for now.

I will open a separate Issue to track this item and assign it to the FF milestone.

Screengrab showing Verified _without_ an _Others_ heading
Screenshot 2022-06-12 at 10 40 59

**Pull request merged**
