### PR TITLE
feat: update map setting design

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix (fixes an issue)

## What is the new behavior?

Design follow-ups from #3787

Screenshot 2024-07-26 at 10 09 34

### CODE REVIEW

**Comment by benfurber** [comment]
@davehakkens This uses the existing 'delete' icon. @dalibormrska's in the design file is better but maybe could be even more one-army-ifed?

Screenshot 2024-07-26 at 10 11 33

**Comment by davehakkens** [comment]
try this one

[Trashcan Icon.svg.zip](https://github.com/user-attachments/files/16400734/Trashcan.Icon.svg.zip)

**Comment by benfurber** [comment]
@davehakkens With the updated delete icon:

Screenshot 2024-07-30 at 11 40 48

Other instances:
Screenshot 2024-07-30 at 11 40 39
Screenshot 2024-07-30 at 11 42 12
Screenshot 2024-07-30 at 11 42 25
Screenshot 2024-07-30 at 11 42 41

**Comment by davehakkens** [comment]
One additional remark
image
This text is only valid for space profiles. Not individuals profiles. They dont have a moderation process

**Review by mariojsnunes — APPROVED** [review]

**Pull request merged**
