### PR TITLE
Add character count to field input

### LINKED ISSUE #2598: [refactor] update FieldInput component to use new CharacterCount component
A CharacterCount component has been added to the platform.  FieldInput can be refactored to use the new CharacterCount as pointed out by @aaronguernsey :

Much of the `TextLimitIndicator` / `CharacterCount` logic came from the `FieldInput` component. Should I update that component with the new `CharacterCount` component? Or would that be a separate task?

_Originally posted by @aaronguernsey in https://github.com/ONEARMY/community-platform/issues/2581#issuecomment-1625430907_

### PR DESCRIPTION
**Pull request by CrowsVeldt**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

_What this PR does_

Replace TextLimitIndicator in FieldInput with CharacterCount component

## Git Issues

Closes #2598

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by CrowsVeldt** [comment]
Accidentally left space in issue number. This should close #2598

**Review by AlfonsoGhislieri — COMMENTED** [review]
Thanks for raising this @CrowsVeldt, I see you’ve also made changes to other components (the trim) to other components. This feels like it’s outside of the scope of solving the issue. Would be good to just keep this PR focused on adding characterCount

**Comment by CrowsVeldt** [comment]
> Thanks for raising this @CrowsVeldt, I see you’ve also made changes to other components (the trim) to other components. This feels like it’s outside of the scope of solving the issue. Would be good to just keep this PR focused on adding characterCount

Yeah. I left those in by accident. I'll sort it out

**Review by AlfonsoGhislieri — APPROVED** [review]

**Comment by AlfonsoGhislieri** [comment]
@all-contributors add @CrowsVeldt for code

**Comment by CrowsVeldt** [comment]
> @AlfonsoGhislieri
> 
> I've put up [a pull request](https://github.com/ONEARMY/community-platform/pull/2650) to add @CrowsVeldt! 🎉

Thanks!

**Pull request merged**
