### PR TITLE
feat: impact - change currency from $ to usd (#3289)

### PR DESCRIPTION
**Pull request by iandorr**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Description

Change the $ dollar sign to a more specific USD in impact question

## Git Issues

#3289

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by benfurber — CHANGES_REQUESTED** [review]
^

**Comment by iandorr** [comment]
Hi @benfurber. I changed the currency in the unit test, hope it's alright now

**Comment by benfurber** [comment]
Hey @iandorr, if you have a look at the checks here, you'll see there's at least one problem still - the commit linting. `impact - change currency from $ to usd - unit test fix` doesn't fit the style. Needs to be something like `chore: fix tests for current change`

**Comment by benfurber** [comment]
Hey @iandorr - will you still have time to finish this off soon?

**Pull request closed without merging**
