### PR TITLE
chore: make node version more explicit

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description
Recently trying to run functions build I noticed it doesn't work with node v18 (workarounds required for ssl issue)

That's not a huge issue as for now we suggest people use node 16, although as of October the official active version of node is 18 so we might see some people starting to try and use (https://github.com/nodejs/release#release-schedule)

So for now I'm suggesting to add a few more hooks to make more explicit the recommendation to use node 16. This includes a small update to the docs, as well as a `preinstall` hook that _should_ put a warning in the terminal when people first run the platform (although has known issues on windows and some older versions of node, so no guarantees).

Otherwise I would suggest a follow-up issue to get fully working with node 18 (although likely that will be easier when no longer using webpack, following on from #2031)

The actual error seen is 
```
error:03000086:digital envelope routines::initialization error
```
Solution seems to be setting `NODE_OPTIONS=--openssl-legacy-provider`, however may not be required when no longer using webpack, so haven't updated the scripts for now

## Testing Notes
Would be interested if anything happens running on mac/linux and a different node version (is the warning clear?). I'm on windows which doesn't seem to do anything

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by evakill — COMMENTED** [review]
i have a mac and tested this locally by
1. switch to node v15.14.0
2. pull branch
3. delete `node_modules` and `yarn.lock`
4. run `yarn install`

the preinstall hook was not run. i also tried:

1. adding/removing single dependencies
2. running `yarn cache clean` and `yarn install:clean` before above steps

but no dice.

based on this [documentation](https://yarnpkg.com/advanced/lifecycle-scripts), i expected the hook to fire when i updated my dependency tree - but lmk if there are repro steps i'm missing. after a quick google, seems like there have been similar issues raised with this hook in the past. 

when i run `yarn preinstall` the script works as expected. 

what if we ran the script directly in `yarn build` or `yarn start`? then the user would receive the message more reliably and more often.

**Comment by chrismclarke** [comment]
Thanks for trying things out @evakill, I was vaguely hopeful that the hooks not firing would just be a quirk with Windows but sounds like I've I'm doing something wrong or they're just not designed that way. 

I like your idea of making it an explicit script instead of relying on hooks, although for now I think I'll avoid adding onto the existing start/build because they're already a bit clunky. Instead I might just revisit if/when we add #2030 as that does a better job of organising scripts. 

If possible could I ask you just to check one-time running `npm install` instead of yarn to see if it at least prompts a message for that case? If it does then I'd say probably still worth merging for the minor docs update and npm catch, and will create a backlog issue for fixing node version incompatibilities

**Comment by evakill** [comment]
> If possible could I ask you just to check one-time running `npm install` instead of yarn to see if it at least prompts a message for that case? If it does then I'd say probably still worth merging for the minor docs update and npm catch, and will create a backlog issue for fixing node version incompatibilities

yup, when i ran `npm install` i got: 
```
➜  community-platform git:(chore/install-hooks) npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/evakillenberg/.npm/_logs/2022-12-28T15_47_59_194Z-debug.log
```

then after `rm -rf node_modules yarn.lock` this showed up 
```
➜  community-platform git:(chore/install-hooks) rm -rf node_modules yarn.lock        
➜  community-platform git:(chore/install-hooks) ✗ npm install                   
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: one-army-community-platform@undefined
npm ERR! Found: firebase@8.10.1
npm ERR! node_modules/firebase
npm ERR!   firebase@"^8.10.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer firebase@"^3.5.2 || ^4.0.0 || ^5.0.0" from react-firebase-file-uploader@2.4.4
npm ERR! node_modules/react-firebase-file-uploader
npm ERR!   react-firebase-file-uploader@"2.4.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/evakillenberg/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/evakillenberg/.npm/_logs/2022-12-28T15_51_18_918Z-debug.log
```

and then again with `npm install --force`
```
➜  community-platform git:(chore/install-hooks) ✗ npm install --force
npm WARN using --force Recommended protections disabled.
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/evakillenberg/.npm/_logs/2022-12-28T15_53_36_681Z-debug.log
```

**Comment by chrismclarke** [comment]
Thanks for checking all this @evakill 
I think my main takeaway is that the hooks just don't work well enough to be relied on, so instead I've taken your suggestion to just move into a generic `healthcheck` script which currently isn't imposed (but may be in the future).

image

I'll still go ahead and merge this to retain the checks for future use and the docs update, and turn my attention to getting node-18 working correctly.

**Review by evakill — APPROVED** [review]
sgtm!

**Pull request merged**
