### PR TITLE
feat: show recent past events

### LINKED ISSUE #1705: Add Previous events to event page
### Description

We would like to display previous events in the event module.
- It makes the page more rich
- It could help people to find eachother locally even after events.

### Page related

Will be used in : [Event page](https://community.preciousplastic.com/events)

### Build suggestion
- Previous events should be greyed out. 
- They are loaded with infinite scroll as the [how-to](https://community.preciousplastic.com/how-to) page)

### Mockup
events-previous

### PR DESCRIPTION
**Pull request by Xyli0**
Displaying a list of the 20 most recent past events

PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Displaying a list of the 20 last (chronologically) events . The opacity of these list items is reduced compared to the upcoming events list.

## Git Issues

Closes #1705 

## Screenshots/Videos
Screenshot 2022-06-14 at 23-25-31 Community Platform

Screenshot 2022-06-14 at 23-29-06 Community Platform

These are two different states on one screenshot.

1.Upcoming events are not found:
    Title disappears.
    In place "At the moment there is no upcoming events" is shown with a button to create a new event below.

2.Past events are not found:
    Title stays in place.
    "Event not found" is displayed

### CODE REVIEW

**Review by thisislawatts — APPROVED** [review]

**Comment by thisislawatts** [comment]
@allcontributors-bot add @Xyli0 for code

**Comment by thisislawatts** [comment]
@all-contributors add @[Xyli0](https://github.com/Xyli0) for code

**Comment by thisislawatts** [comment]
@all-contributors add @Xyli0 for code

**Comment by thisislawatts** [comment]
Thanks @Xyli0 ✨  Let me know here if you'd rather **not** have your information included as a contributor on the readme :)

**Comment by davehakkens** [comment]
thanks for the PR @Xyli0 Looks really nice! 💪
There was a bounty for this issue (read more about it [here](https://onearmy.github.io/community-platform/Contributing/bounties) If you send me your mail address I can explain how to redeem it!

**Comment by davehakkens** [comment]
awesome, good to hear that! :) We will make sure to keep track of it.
Are you also on our Discord?

**Comment by Xyli0** [comment]
I just joined the One Army server. Is this the one you talk about or is there any specific server for development ?

**Comment by Xyli0** [comment]
Awesome! Thanks.

**Pull request merged**
