### PR TITLE
fix: edit comments

### LINKED ISSUE #1864: [bug] Cant edit or delete comments
**Describe the bug**
The edit and delete feature doesnt work in comments.
For both the research module and the how-to's
1. In the research module the button is there but non clickable
2. in How-to's the `Remove` and `Edit` button are not present

This probably got broken when migrating the component
In this https://github.com/ONEARMY/community-platform/pull/1742 or this https://github.com/ONEARMY/community-platform/pull/1772 one

**To Reproduce**
Steps to reproduce the behaviour:

1. Login [deviste](https://dev.onearmy.world) 
2. Leave a comment in research or howto
3. try to edit or delete

**Screenshots**
In research module after leaving a comment 
afbeelding
In how-to after leaving a comment
afbeelding

### PR DESCRIPTION
**Pull request by asheerrizvi**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Fixes ability to edit comments in how-to and research

## Git Issues

Closes #1864

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by davehakkens** [comment]
thanks for the pr @asheerrizvi.
It works now in the research module, but not in the how-to's
As you can see in the two screenshots below, no edit or delete button for how-to.
Does it work there?

afbeelding


afbeelding

**Comment by asheerrizvi** [comment]
@davehakkens that's weird, I can see the buttons:

https://user-images.githubusercontent.com/17976252/185871047-f5a7c1db-5ebb-4c5c-9434-4913ede88b72.mp4

I am logged in using the `howto_reader@test.com` user which I found in a test. We are using the same component in both of these pages.

**Comment by davehakkens** [comment]
Strange. Tried again locally and with the [preview link](https://github.com/ONEARMY/community-platform/pull/1901#issuecomment-1223971745)

My usual test account, didnt work.
afbeelding

Created a new account and there it works.
afbeelding

Not sure what is going on here?

**Comment by asheerrizvi** [comment]
Seems like the `isEditable` property is false. I am not sure why that might be for your usual account?

**Review by thisislawatts — APPROVED** [review]

**Comment by thisislawatts** [comment]
I tested this out locally and running on the preview deployment and was not able to recreate the issue you saw @davehakkens. Merging in favour of iterating in production.

**Pull request merged**
