### PR TITLE
Add Useful Button to Research Module

### LINKED ISSUE #1405: Add useful button to Research module
### Description

We have a useful button in our [how-to](https://community.preciousplastic.com/how-to) module. We need the same button in our research module ( will be used extensively in Project Kamp setup next season🔥)

### Page related

Will be used in :
- PR related to useful button https://github.com/ONEARMY/community-platform/pull/1097
- See the [research module](https://community.preciousplastic.com/research) 

### Mockup

Add useful to research

### PR DESCRIPTION
**Pull request by mmortar**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Adds a useful button to the research module
currently does not store the updated useful count on the research

### CODE REVIEW

**Comment by mmortar** [comment]
@thisislawatts Here's the pr draft for the Research Useful button.  The issue I was having was with onUsefulClick in ResearchItemDetail.tsx

**Comment by thisislawatts** [comment]
@mmortar out of interest were you were running the firebase emulator locally? 
As the research documents are being updated via a background function we need that to be available and subscribed to the firestore instance.

I will approve this for deployment to the preview environment which will ensure the full stack is available.

**Comment by davehakkens** [comment]
hey @mmortar how is the draft PR going, would you manage to turn it into a full functioning PR? 🔥
Let me know! Otherwise we can also assign to someone else if you are stuck or not able to finish.

**Comment by mmortar** [comment]
hey @davehakkens thanks for reaching out! Sorry for the delay on this one, just had a lot going on the past few weeks between work and school so this project got pushed to the back burner.  I'm going to get back on it this weekend and I'll let you know by Monday if I can't figure out how to overcome the issue I've been having.

**Comment by chrismclarke** [comment]
Thanks for the additions @mmortar - I'm aware quite a few conflicts have been introduced with some recent changes. I just took a quick look and resolving should be pretty straight-forward, although I'm going to wait until after #1516 is merged as that will add some extra conflicts with verified badges. But hopefully that will get merged this week and then I will resolve here and review

**Comment by chrismclarke** [comment]
moving to #1602 to rebase for linting issues

**Pull request closed without merging**
