### PR TITLE
Security suggestions

### PR DESCRIPTION
**Pull request by wallies**

### CODE REVIEW

**Comment by chrismclarke** [comment]
Thanks for adding these, really interested to see what the lhbot and zap proxy show. 

As I'm guessing the master branch will probably fail the new tests I'll rebase to `ci/testing`, and then add an issues to get anything thats needs to be resolved done before merge into master.

**Comment by chrismclarke** [comment]
@wallies 
So the first logs came back, available in full here:
https://travis-ci.org/ONEARMY/community-platform/jobs/579123772

Lighthouse threw an error:
```
throw new Error('This script can only be run on Travis PR requests.');
 at getConfig (/home/travis/build/ONEARMY/community-platform/node_modules/lighthousebot/runlighthouse.js:134:11)
```
I'm guessing this is because I applied the commit directly on the branch (?). In the future we will only need to run this on merges into master, so I'm assuming it will work once merged in (?).

Zap proxy also threw an error:
```
Usage: zap-cli quick-scan [OPTIONS] URL
Error: Got unexpected extra argument (https://dev.onearmy.world)
```
I'm guessing this is just a minor config syntax issue

**Comment by wallies** [comment]
@chrismclarke Yes I think lighthouse might need to have an only on PR branches option, forgot that sorry. Would also need an environment variable set in travis LIGHTHOUSE_API_KEY, setup instructions here https://web.dev/using-lighthouse-bot-to-set-a-performance-budget#5.-setting-up-lighthouse-bot.
Dont know what happened to zap but looks to be that travis doesnt like the slash, so needs to be this instead
```
docker run -u zap -i owasp/zap2docker-stable zap-cli quick-scan -sc -o '-config api.disablekey=true' -s xss,sqli --spider "https://dev.onearmy.world"
```

**Comment by chrismclarke** [comment]
Ok cool, will update the lighthouse config now. Will update the zap script if you haven't already (see another pr open)

**Comment by chrismclarke** [comment]
Lighthouse is a manual process!!! Seriously tech giants, what's going on?? 🙈

**Comment by BenGamma** [comment]
@chrismclarke any news on this ? Planning on merging `ci/testing` on master branch ?

**Comment by wallies** [comment]
@chrismclarke also moved to lightkeeper https://github.com/lfre/lightkeeper as seems to work better with PRsand fixed some Travis bits
https://github.com/wallies/onearmy/pull/11/files. You will notice in the PR example in my repo it is using netlify to run up the site and test it. I think this will work nicely with the new jest testing and lighthouse Web perf

**Pull request merged**
