### PR TITLE
[feat]: Add question mark validation to question title form

### LINKED ISSUE #3604: [feature request] Add mandatory questionmark for Questions module
**Is your feature request related to a problem? Please describe.**
The questions module should host "questions" 

**Describe the solution you'd like**
1. Make it mandatory to have a questionmark inside the title.
2. Add an error message the explain to the user
3. ideally it can be combined with the current error message regarding the character length 

**Describe alternatives you've considered**
To avoid complexcity, don't make the validation error. Just mention it in the title of the input field

**Screenshot**

questionmark

### PR DESCRIPTION
**Pull request by lucaasrojas**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Add a new validator ( endsWithQuestionMark ) that validates the value allowing only one question mark at the end. Also, it modifies the composeValidator function to return multiple error messages at once.

## Git Issues

Closes #3604 

## Screenshots/Videos

image

image

image

image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by benfurber** [comment]
Hey @lucaasrojas! Thanks for the first time contribution! 

Sorry about the flaky route tests (I know it's unrelated to your change. The global timeout is actually set to 15 seconds so probably better to review the custom timeouts entirely?

**Review by benfurber — APPROVED** [review]
Waiting to see what you think about the routes tests, then this is good to go.

**Comment by lucaasrojas** [comment]
> Hey @lucaasrojas! Thanks for the first time contribution!
> 
> Sorry about the flaky route tests (I know it's unrelated to your change. The global timeout is actually set to 15 seconds so probably better to review the custom timeouts entirely?

Hi, I removed all custom timeouts. Regarding the tests it is weird because they fail randomly, I reviewed them a little bit and there seems to be an issue connecting the backend and another one on the profile settings page.

**Comment by benfurber** [comment]
Ha, yes it's annoying isn't it(!) Sorry if it got in your way. I'm working on user settings stuff atm so should be fixed soon...

**Comment by benfurber** [comment]
@all-contributors please add @lucaasrojas for code

**Comment by benfurber** [comment]
@all-contributors please add @lucaasrojas for code

**Comment by benfurber** [comment]
@all-contributors Yeah, but you made a mess with the PR...

**Comment by benfurber** [comment]
@all-contributors please add @lucaasrojas for code

**Pull request merged**
