### PR TITLE
fix: Add spaces to notifications with urls

### PR DESCRIPTION
**Pull request by exabyssus**
## Description

Adds spaces between words in notifications

## Git Issues

Closes [#3330](https://github.com/ONEARMY/community-platform/issues/3330)

## Screenshots/Videos

Screenshot 2024-03-07 at 01 02 31

### CODE REVIEW

**Comment by rchick** [comment]
maybe a test update would be good something like

```
import { MemoryRouter } from 'react-router-dom'
import { render } from '@testing-library/react'
import { NotificationTypes } from 'oa-shared'
import { FactoryNotification } from 'src/test/factories/Notification'

import { getFormattedNotifications } from './getFormattedNotifications'

describe('getFormattedNotifications', () => {
  NotificationTypes.forEach((type) => {
    it(`returns a well formatted ${type} message with spaces between words and values`, () => {
      const [notification] = getFormattedNotifications([
        FactoryNotification({ type }),
      ])
      const { container } = render(
        <MemoryRouter>{notification.children}</MemoryRouter>,
      )
      expect(container).not.toBeEmptyDOMElement()

      // Assert that there are spaces between words and values in the formatted notification message
      const formattedMessage = container.textContent
      const words = formattedMessage.split(' ')
      expect(words.length).toBeGreaterThan(0)
    })
  })
})

```

**Review by benfurber — CHANGES_REQUESTED** [review]
Thanks so much for your first time contribution @exabyssus! 🥳 

I agree with @rchick's test suggestion, can you add that please and then I think we'd be good to go!

**Comment by benfurber** [comment]
Hey @exabyssus. Are you still able to work on this?

**Comment by benfurber** [comment]
@all-contributors please add @exabyssus for code

**Pull request merged**
