### PR TITLE
fix: map pin caching

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description
Revert changes in #3466 to allow caching of map pins (see comment in PR for details)

Unfortunately the `getWhere` query always executes against server, whereas the `stream` query includes ability to cache results and retrieve from cache

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by mariojsnunes** [comment]
But by using streaming, doesn't that mean than whenever a pin changes, all users will get an update?

**Comment by chrismclarke** [comment]
> But by using streaming, doesn't that mean than whenever a pin changes, all users will get an update?

It does mean that yes, although querying we will also always pull all pins regardless of whether they have been updated or not on every page load. So I'm working on the assumption that a user streaming map pin updates will still result in fewer reads than a user who loads 3.7k every page load - but can definitely still be optimised a lot more (just not using the `getWhere` operation which unfortunately only queries against the server)

**Comment by mariojsnunes** [comment]
> It also reads from a separate cache for users visiting for the first time, meaning that new users only make 1 read request for first batch of data and then just stream docs as updated.

Can you explain this in more detail? How does streaming differ from getWhere on the first page load?
(I understand there is caching after the first page load)

**Comment by chrismclarke** [comment]
> > It also reads from a separate cache for users visiting for the first time, meaning that new users only make 1 read request for first batch of data and then just stream docs as updated.
> 
> Can you explain this in more detail? How does streaming differ from getWhere on the first page load? (I understand there is caching after the first page load)

The logic of `getWhere` is:

1. retrieve all docs from server (unless limit specified) 
2. retrieve docs from cache (if none on server, e.g. offline) 
3. return docs (no cache update)

Whereas the logic for `stream` is:

1a. retrieve all docs from cache
1b. if no docs exist (new user) use special server-cache which stores daily copy of all docs as single request and update cache
1c. emit list of docs retrieved from cache
2a. check all cache docs for most recent `_modified` timestamp
2b. update cache with updated server docs
2c. emit combined list
3a. subscribe to any new doc changes

So getWhere always forces a large number of read ops on server whereas stream is usually much smaller initially and only increases if lots of docs are getting actively modified. 

So really we want something between the 2, where we use cache-first with server update but without streaming

**Comment by chrismclarke** [comment]
@mariojsnunes 
I've just pushed [a05fd9b](https://github.com/ONEARMY/community-platform/pull/3472/commits/a05fd9bc64bb50fc2b9004fe7d75d62cba609d5e) which manually stops the stream operation after the initial docs have been retrieved from the cache and server. A bit of a hacky/temp workaround but hopefully should provide an alternative option

**Comment by mariojsnunes** [comment]
Thank you!
I agree with the changes. And I understand now, that that PR was naive and assumed way less Pins than exist in reality. And didn't know about the cache db.
Still something is causing lots of pin updates, need to understand what.

**Comment by chrismclarke** [comment]
> Thank you! I agree with the changes. And I understand now, that that PR was naive and assumed way less Pins than exist in reality. And didn't know about the cache db. Still something is causing lots of pin updates, need to understand what.

No worries at all, nothing about this is very intuitive - ordinarily faking a single request makes way more sense than multiple, but unfortunately there's a lot of layers of compilation abstracted away which works like `stream` and `query` don't represent very well.

**Comment by chrismclarke** [comment]
I've added #3474 to try and clarify the code a little more and add general support for not keeping stream alive if not necessary to do so

**Pull request merged**
