### PR TITLE
fix: Show uploaded images on how to edit screen

### LINKED ISSUE #2701: [bug] Step images disappear when a step is moved
**Describe the bug**
When a step is moved, if images are attached to it they're no longer present/shown to the user.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to create/edit a how-to.
2. Upload an image to a step.
4. Move the step you've added an image to.
5. The image disappears.

**Expected behaviour**
The images should still be present.

**Screenshots**
Screenshot 2023-08-01 at 19 46 47
Screenshot 2023-08-01 at 19 47 27

**Additional context**
I wonder if it's something about how the images are passed to each HowtoStep and when the move callback is called, something gets lost in the mix. Not sure yet though, any other thoughts?

### PR DESCRIPTION
**Pull request by benfurber**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

It passes down the uploaded image props to the edit steps form so that they now appear to users after they leave the page.

## Git Issues

Closes #2701

### CODE REVIEW

**Comment by benfurber** [comment]
I'll add a prop test for this once #2698 has been merged in.

**Comment by evakill** [comment]
@benfurber can you show screenshot diffs? i might be looking in the wrong place, but I'm already seeing the image previews on the how to step form
Screen Shot 2023-08-09 at 7 17 18 AM

**Comment by benfurber** [comment]
@evakill Can you check I got it this time please?

**Comment by evakill** [comment]
@benfurber now shows an empty preview image after swapping steps

https://github.com/ONEARMY/community-platform/assets/37253846/8e2802a8-a7ff-4a00-8a4a-cb53505950a3

**Comment by benfurber** [comment]
@evakill That was a fun browser difference to work out! (I'd be working on firefox).

Working for you now?

**Review by evakill — APPROVED** [review]
works! thanks :D

**Pull request merged**
