### PR TITLE
chore: use react-router new routing approach RouterProvider

### PR DESCRIPTION
**Pull request by mariojsnunes**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

https://github.com/remix-run/remix/blob/bbead33bf530be030d16a1466b52cd99d077382a/decisions/0005-remixing-react-router.md#react-router-api-surface
Use the newer and recommended routing approach to make it easier to migrate to Remix later.

### CODE REVIEW

**Comment by mariojsnunes** [comment]
I'll wait for someone else to take a look. And also test on the preview website.

**Review by benfurber — APPROVED** [review]
Could deffo refactor the routing setup but not the focus of this PR. Will do a quick manual check on the preview build too.

**Comment by benfurber** [comment]
A basic click through confirmed all routes working as before.

**Comment by mariojsnunes** [comment]
Found that after this change, confirmation on leaving the page no longer works.
Added a fix that also improves the confirmation to use our modal instead of the browser default one. (easier to test too)

Besides that, found a few more instances where forms were being submitted by clicking other buttons, which were breaking some tests. (because the default type of buttons is submit, not button)

**Comment by mariojsnunes** [comment]
found more issues when saving forms

**Comment by benfurber** [comment]
Awesome, this looks like really good work @mariojsnunes.

**Pull request merged**
