### PR TITLE
feat: fixed comments render

### PR DESCRIPTION
**Pull request by jojudre**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)

## Description

- fixed comment text not to go beyond
- added «show more/ show less» button, to hide comments with big height
- fixed textarea resizing when editing comment

## Git Issues

Closes #

## Screenshots/Videos

https://user-images.githubusercontent.com/42969746/157303961-21b5ed47-7af6-46de-a955-e8395bc13c3f.mp4

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by chrismclarke** [comment]
Thanks for adding this @jojudre , looks like a really nice addition to have. 

The code looks nice and clean to me, @davehakkens - would you be able to run locally to check the visuals look good to you?

**Comment by chrismclarke** [comment]
I'll also take a quick look at the caching issue which is causing tests to fail (nothing to do with the code)

**Comment by davehakkens** [comment]
works/looks great. thanks a lot @jojudre

**Comment by chrismclarke** [comment]
I've opened a separate PR #1529 to try resolve the test errors - once merged and if working I think this one should be good to go also.

**Review by chrismclarke — APPROVED** [review]
All issues resolved, good to go! Thanks again @jojudre

**Pull request merged**
