### PR TITLE
Feat: Support a new member to pick a valid username - v1

### LINKED ISSUE #3271: Feat: Support a new member to pick a valid username - v1
At the moment we don't support users to pick a valid username, so they might learn after clicking submit that a username is already taken.

Please change the field on `SignUpPage` to accomidate this.

Screenshot 2024-02-12 at 17 01 17

1. As you're creating a much more complex field, please create a new component for this. 
2. The logic for `checkUserNameUnique` already exists and will now be needed in two spaces so please move it to a util with a lovely little couple of unit tests.
3. Probably call the function, say after five initial characters typed and then only onBlur after that? Happy for any other ideas.
4. Don't reinvent the wheel for the error handling, use the conventions/handling of Field in 'react-final-form'.

### PR DESCRIPTION
**Pull request by saile515**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Added a test to the Sign Up validation schema which checks if the username is already taken, before the user submits. This is my first PR. I tried my best to follow all guidelines and the project structure, but some things will inevitably be wrong. If something needs changing, please leave a comment and I will do my best to fix it.

## Git Issues

Closes #3271 

## Screenshots/Videos

image

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by benfurber — CHANGES_REQUESTED** [review]
Awesome, thanks @saile515! 

Looks like the tests are failing. To get them passing, I think you're going to need to mock a user store in the file so you can then get to something like this for the tests:

```
  describe('checkUserNameUnique', () => {
    it('user does not exist', () => {
      const store = storeMock
      // stub the store true

      expect(checkUserNameUnique(store, 'testUser')).toBe(true)
    })
  
  
    it('user does exist', async () => {
      const store = storeMock
      // stub the store false

      expect(checkUserNameUnique(store, 'testUser')).toBe(false)
    })
  })

**Comment by saile515** [comment]
Thanks for the suggestions @benfurber, and sorry for the late response. I just have a couple of questions regarding the codebase. When I follow the testing guide, only cypress tests seem to be run, and not jest tests. I also noticed my commit broke one of the cypress tests. Should I just remove that test, since the new jest test replaces it, or rewrite it (which seems hard to do since the underlying error message of this implementation is abstracted).

I also can't figure out how to create a mock store. In the code I submitted, I tried to replicate the relevant parts of the userStore test, but this has apparently not worked.

I am quite new to open source and testing frameworks, sorry if these are beginner problems.

**Comment by benfurber** [comment]
Hey @saile515. Delighted for your contribution, no worries about these kinds of bits, we're all learning hopefully all the time. 

On the easy one to answer, to get the unit tests running locally, call `yarn test:unit`.

Good to have unit tests and feature (cypress) tests where possible.

This unit test will work!
```
import { checkUserNameUnique } from './checkUserNameUnique'

import type { UserStore } from '../stores/User/user.store'

describe('checkUserNameUnique', () => {
  const mock = jest.fn().mockImplementation(() => {
    return {
      getUserProfile: () => jest.fn(),
    }
  })
  const store = new mock() as UserStore

  it('user does not exist', async () => {
    jest.spyOn(store, 'getUserProfile').mockResolvedValue(undefined)

    const check = await checkUserNameUnique(store, 'testUser')

    expect(check).toBe(true)
  })

  it('user does exist', async () => {
    jest.spyOn(store, 'getUserProfile').mockResolvedValue({})

    const check = await checkUserNameUnique(store, 'testUser')

    expect(check).toBe(false)
  })
})
```

I don't see a cypress test failing right now? Could try be one of our flaky ones.

**Review by benfurber — APPROVED** [review]

**Comment by benfurber** [comment]
@saile515 Ah yes, I see what you mean about the feature test now. I think the scenario that's covered in the test should stay but should be changed based on your work. You OK with that?

**Review by benfurber — CHANGES_REQUESTED** [review]
(Realising the cypress sign-up test needs changing)

**Comment by saile515** [comment]
@benfurber Yeah that sounds like a good idea. Do you know how I could add a `data-cy` attribute to the error message? If I understand the code correctly, 'yup' injects the message if the username is taken.

**Review by benfurber — APPROVED** [review]

**Comment by benfurber** [comment]
@all-contributors please add @saile515 for code

**Comment by benfurber** [comment]
Amazing @saile515, thank you so much! Which issue takes your fancy next?

**Pull request merged**
