### PR TITLE
feat: update design of zoom controls on new map

### LINKED ISSUE #3872: feat: update design of zoom controls on new map
PP Map Final

The zoom controls for the new map (`<MapWithList />`) are currently the default design. 

Please update them with the design above. (Though leave them on the top left).

We use an old version of leaflet for the map.

### PR DESCRIPTION
**Pull request by JoseAConcepcion**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix (fixes an issue)
- [x] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?
The zoom controls for the new map are currently the default design.

## What is the new behavior?
The zoom controls were updated with the correct design.
old_design
new_design

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Git Issues

Closes #3872  

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by benfurber — CHANGES_REQUESTED** [review]
Fantastic, thank you @JoseAConcepcion!

Minor feedback.

1. Make the size of the buttons even bigger. Let's go with 22px font size.
2. More spacing in the element - i.e. around the text.
3. More spacing around - around the element should be the same size spacing other components on the page have (ideally added to the parent element so it can be added through style props rather than css).

**Comment by JoseAConcepcion** [comment]
Hi @benfurber, the font size of the buttons already were 25px. Should it be higher still? Did you mean the general size of the actual buttons?

**Comment by benfurber** [comment]
> Hi @benfurber, the font size of the buttons already were 25px. Should it be higher still? Did you mean the general size of the actual buttons?

@JoseAConcepcion Ha. I misread the code! Yes I mean the general size of the buttons. If it's 25px already, how's about 30px?

**Comment by JoseAConcepcion** [comment]
@benfurber its bigger now, increased the size and the padding of the element but I'm not sure it's the spacing of the other elements, for some reason modifying the parent doesn't do the trick :(

feedback_design

**Comment by benfurber** [comment]
Awesome! Thanks @JoseAConcepcion, I'll get this merged in now. Anything else on the issues list take your fancy?

**Comment by benfurber** [comment]
@all-contributors add @JoseAConcepcion for code

**Comment by JoseAConcepcion** [comment]
@benfurber happy to help :)  
I will be back in two weeks give or take, got to finish some final projects and exams. 
For sure I will take another issue.

**Pull request merged**
