### PR TITLE
feat: add profile labels to machine profile type

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently the profile type machine shop has a custom profile attribute.

## What is the new behavior?

This removes that custom attribute and replaces it with a more generic field that all profile types will eventually use.

Screenshot 2024-10-16 at 14 17 12

Screenshot 2024-10-17 at 13 14 46

Screenshot 2024-10-17 at 13 36 18

https://www.figma.com/design/x4DcaUjwiigjCySAt5omxB/CP-%2F-Signup%2C-Settings-and-Gatekeeping?node-id=1140-2633&node-type=frame&t=MryI3JVwVnwhTJMn-11

Part of #3908

### CODE REVIEW

**Comment by benfurber** [comment]
@mariojsnunes I'm starting to [work on this](https://www.figma.com/design/x4DcaUjwiigjCySAt5omxB/CP-%2F-Signup%2C-Settings-and-Gatekeeping?node-id=1140-2633&node-type=frame&t=MryI3JVwVnwhTJMn-11)

Ideally the labels are DB stored/content editable for mods. But I'd rather that done later down the line. Do you think this service pattern is appropriate for this usecase? These labels will end up being called at least on the map, profiles and settings.

**Comment by davehakkens** [comment]
Are you making them profile specific @benfurber? -as they should work cross profile

**Comment by benfurber** [comment]
> Are you making them profile-type specific @benfurber? -as they should work cross all profile-types

@davehakkens Generic is the direction of travel.

**Comment by mariojsnunes** [comment]
> @mariojsnunes I'm starting to [work on this](https://www.figma.com/design/x4DcaUjwiigjCySAt5omxB/CP-%2F-Signup%2C-Settings-and-Gatekeeping?node-id=1140-2633&node-type=frame&t=MryI3JVwVnwhTJMn-11)
> 
> Ideally the labels are DB stored/content editable for mods. But I'd rather that done later down the line. Do you think this service pattern is appropriate for this usecase? These labels will end up being called at least on the map, profiles and settings.

Looks good! It can easily evolve into calling an API

**Comment by davehakkens** [comment]
What is the end state of the travel you have in mind @benfurber? -so I understand better how to review this

**Comment by benfurber** [comment]
@davehakkens [The to-do list for this work](https://github.com/ONEARMY/community-platform/issues/3908)

**Comment by davehakkens** [comment]
Nice thanks for the update. Sounds good to me

**Comment by benfurber** [comment]
Update. Worked with Mario on this for a bit. We got caught on a build error. Going to change the tech approach on this. Will resume work on it Monday.

**Comment by benfurber** [comment]
(All the hard work is in this branch, most of the rest should be straightforward after this.)

**Comment by benfurber** [comment]
Right. I think is is finally ready now. So will work on the PP database change tomorrow.

**Comment by benfurber** [comment]
Data updated and looking good. Deploying this now.

**Pull request merged**
