### PR TITLE
fix:(platform): fix negative numbers on impact feature

### LINKED ISSUE #3291: [bug] Impact - negative numbers allowed
**Describe the bug**
On the impact feature, users are able to add negative numbers

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Settings'
2. Scroll down to 'Positive impact 🤙'
3. Click on 'Expand and edit'
4. Click on 'Edit data'
5. Add negative numbers
6. See error

**Expected behaviour**
Only numbers above 0 should be considered. If a negative number is written, some behaviours could be considered:
1. Show error message to remove the "-" sign before saving
2. Automatically delete the "-" sign when saving

**Screenshots**
image

### PR DESCRIPTION
**Pull request by manacespereira**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Fixes the negative numbers being presented in the Impact content. I did a real quick fix and added a unit test. From now on, everything that is negative in this area, will be replaced for the positive version of the number. Example: -3 will be 3, etc...

## Git Issues

Closes #3291 

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by thisislawatts** [comment]
@manacespereira do we know that that is the correct behaviour? It seems likely that we should either:
1. Prevent users saving negative value, eg. validate on client + server side that value is `x > 0`
2. If any saved values to not meet requirements (`x < 0`) we do not render them. This seems preferable to manipulating data entered by the community.

**Comment by benfurber** [comment]
@manacespereira Same access as I mentioned on the other issue, just create an account with your local setup. The components you'll need to play around with are all in `src/pages/UserSettings/content/formSections/Impact`.

**Comment by benfurber** [comment]
Hey @manacespereira - will you have a chance to finish this off soon?

**Comment by manacespereira** [comment]
> Hey @manacespereira - will you have a chance to finish this off soon?

hey, sure i can!!! i just need more time and understand how can i access with this specific profile... i will let you know if i have any doubt :)

**Comment by benfurber** [comment]
Hey @manacespereira happy for you to pick this up again if you get a chance.

**Pull request closed without merging**
