### PR TITLE
fix: how-to virtualized grid

### LINKED ISSUE #1850: [mobile] Inconsistent space btw how-tos
Issue:
In the how-tos in the list page have inconsistent spacing. 

Link:
https://community.preciousplastic.com/how-to

Screenshots:
Screenshot_20220724-173808_Brave

Proposal:
All how-tos have equal spacing btw them (30px).

### PR DESCRIPTION
**Pull request by asheerrizvi**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Fixes spacing for how-to grid items

## Git Issues

Closes #1850

## Screenshots/Videos

https://user-images.githubusercontent.com/17976252/192139251-49b60116-ad02-4797-8444-a4f5ad336d6f.mp4

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by thisislawatts** [comment]
Thanks for raising this PR @asheerrizvi.

What do you think about removing the virtualized grid layout for howto's entirely and falling back to a combination of:
* CSS Grid driven layout – there is good support for this in our target browsers and it removes a 3rd party dependency.
* Pagination with links – better for SEO and accessibility.

**Comment by asheerrizvi** [comment]
@thisislawatts I think it must have been virtualized because we expect this page to have a lot of items. I like your suggestion about using grid for layout and then paginating these items. How do you think we should go on about implementing pagination?

**Comment by thisislawatts** [comment]
@asheerrizvi, the simplest implementation would probably be to:
* Drop the Virtualized grid element
* Add a query limit of say 36
* Introduce a load more button
* Add routing support for; `/how-to/2`, `/how-to/23`
* Add error handling (404) when no results found, such as: `/how-to/8219231231231231`

**Comment by asheerrizvi** [comment]
@thisislawatts from what I understand this (pagination) should be implemented using MobX right? I haven't worked with MobX but I'll look into it. Also this issue was just for spacing, should I work on pagination using this issue itself or you want me to create a new one and merge this one?

**Comment by thisislawatts** [comment]
The original issue, bad spacing, was a symptom of layout being handled by a JS component rather than using modern CSS techniques. My recommendation here is to address the underlying cause. 

Understandable if you would prefer not to engage with the larger body of work here. It would probably be worth raising a separate issue/feature request to surface the pagination work.

**Comment by asheerrizvi** [comment]
Yea that's understandable. Will do it as a part of this issue then 👍

**Comment by thisislawatts** [comment]
Thanks @asheerrizvi! Let me know if there's anything I can help with here. I would recommend raising a Draft PR early then we can provide feedback on the approach before you have invested too much time. 

You mentioned Mobx, but I think the state that needs to managed here is quite simple and could be handled with the state management available within React itself.

**Comment by asheerrizvi** [comment]
@thisislawatts sure, will start over the weekend 😄

**Comment by asheerrizvi** [comment]
@thisislawatts have opened a new draft PR here:

https://github.com/ONEARMY/community-platform/pull/1959

**Pull request closed without merging**
