### PR TITLE
chore: introduce check for spelling within documentation

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [X] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Developer experience (improves developer workflows for contributing to the project)

## Description

Introduce a spell checker for our documentation (markdown files) to save our reviewers from thinking about these things. One question this raises is which version of English would we prefer to standardize/standardise on?

- British :gb:
- International :us: / 🇺🇳

This check is run as part of our CI pipeline to block any markdown being merged which contains incorrect spelling or unknown words.

### CODE REVIEW

**Comment by davehakkens** [comment]
nice! 
No idea which version to choose though. What is mostly used in the current documentation?
(This is for Community Platform [docs](https://onearmy.github.io/community-platform/) I assume?)

**Comment by thisislawatts** [comment]
@davehakkens that's right, this is for the community documentation _and_ the various documentation presented in the Github interface, for example the primary [README document](https://github.com/ONEARMY/community-platform/blob/master/README.md). 

At the moment there seems to be slightly more instances of UK spelling across the documentation. 

Spelling violations when testing with US dictionary:
```
analyse
customisation
dockerised
favourite
finalise
initialise
maximise
optimisation
optimisations
Optimise
organise
realised
recognise
```

Spelling violations when testing with UK dictionary:
```
behavior
bigquery
Boxen
centered
dockerised
favorite
flavored
labeled
reuseable
Teardown
```

As someone with UK English as my first language, I have my own bias due to familiarity. I am more interested in which is more familiar to those who use English as an additional language.

**Comment by davehakkens** [comment]
hehe yeh we got our two main maintainers from UK. 
I actually think that would  be reason enough for me at this point to go for that!

**Comment by thisislawatts** [comment]
@davehakkens seems reasonable enough in the short. The use of `cspell` will make it straight forward enough to switch back to US english if the wider community prefers.

**Pull request merged**
