### PR TITLE
feat: introduce username component

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

here are a wide variety of styles when
displaying a user name. The aim is to move
all instances to use a single component so
that the UI becomes more consistent.

### CODE REVIEW

**Comment by thisislawatts** [comment]
For @franknoirot flagging the appearance of this within the How to Listing, as I am not sure about:
* The horizontal alignment, flag is indented slightly by the padding
* Vertical alignment, maybe a bit more space between bottom of title and top of username?

<table>
<tr>
<td>

</td>
<td>

</td>
</tr>
</table>

**Comment by davehakkens** [comment]
Cool component!
Not sure if you are aware. But on [profiles](https://onearmy-next--pr1954-feat-introduce-usern-4kbu4oht.web.app/u/chrismclarke) they still show double
afbeelding

**Comment by thisislawatts** [comment]
> Cool component! Not sure if you are aware. But on [profiles](https://onearmy-next--pr1954-feat-introduce-usern-4kbu4oht.web.app/u/chrismclarke) they still show double afbeelding

✅ Fixed

**Comment by thisislawatts** [comment]
@davehakkens, updated to offset the component left and reduce the type size.

**Review by davehakkens — APPROVED** [review]
looks awesome

**Pull request merged**
