### PR TITLE
feat: updated pin card

### PR DESCRIPTION
**Pull request by benfurber**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Feature (adds functionality)

## What is the current behavior?

New map used old pins.

## What is the new behavior?

Uses the new card style.
Screenshot 2024-09-05 at 16 43 36
Screenshot 2024-09-05 at 16 29 30
Screenshot 2024-09-05 at 16 29 43
Screenshot 2024-09-05 at 16 31 21

### CODE REVIEW

**Comment by davehakkens** [comment]
Needs a @dalibormrska in here :)

**Comment by dalibormrska** [comment]
Uuuu, juicy!!! Overall looks goooood, there were two things that popped into my mind... 

1. Looking at the closing button, I see the problem with the button component in this case. I see that as it is it's hard to customise it and make it round and without border as in the screenshot. Currently I think it is too prominent and takes too much attention if it has the primary color and the border. image image
Later on, if needed, I could see myself visiting the button component and designing all the variants we might need so that we can use the button component consistently across the platform in suitable variants. What do you think could be the solution for now? I can see that the filter in the old map had the closing button made quite simply. Could we maybe replicate that? Having the closing SVG (maybe a bit bigger than the one) with a white circle behind it? image
The svg could be scaled to 32x32px as well as the circle.image

**Comment by dalibormrska** [comment]
The second thing would be that the card does not need to have the hover effect in the map. But awesome progress nevertheless!  🎉

**Comment by benfurber** [comment]
I agree about the button prominence and card hover (which is partly because I don't want to duplicate some work in #3841). I'll have a play with both.

**Pull request merged**
