### PR TITLE
fix: make member profiles responsive

### LINKED ISSUE #1610: [bug] Collecting Mobile (reponsive) weirdness
**Describe the bug**
This issue is to gather all the incorrect mobile behaviour on the website. Throughout time we've build new componenets and refractored the site but don't always keep a good eye on mobile.
This thread is to gather all the pages to improve. 

**Users:** Screenshot and dump them here.
**Developers:** Feel free to adress them and make a PR

### PR DESCRIPTION
**Pull request by amandaqiu1**
PR Checklist

- [ x ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ x ] - Latest `master` branch merged

PR Type

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

The member profiles are now responsive. The text shows below the image on mobile. 

## Git Issues

Closes #1610 (part of it)

## Screenshots/Videos
Screen Shot 2022-05-02 at 2 29 46 AM

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by thisislawatts** [comment]
@amandaqiu1 would you be able include screenshots with illustrate the changes that have been made in this PR?

**Comment by amandaqiu1** [comment]
Sure, just updated it with the screenshot.

**Comment by davehakkens** [comment]
hey @amandaqiu1 thanks for the PR.
Looks nice. A few small remarks:
1. Could you center the avatar and increase the height to 200px?
2. Reduce the width of the "how-to" box to fit the main div.
3. Increase the width of the description box to the full width of the main div.
feedback-mobile

**Comment by davehakkens** [comment]
Hi @amandaqiu1. Do you think it would be possible to wrap this one up?
Would be a nice one to merge in!

**Comment by thisislawatts** [comment]
Closing as stale, fixes inbound via: https://github.com/ONEARMY/community-platform/pull/1768

**Pull request closed without merging**
