### PR TITLE
fix: remove use of theme from forgot password

### LINKED ISSUE #2295: [refactor] Remove direct usage of Theme from "ForgotPassword.tsx"
Remove the following

```ts
// TODO: Remove direct usage of Theme
import { preciousPlasticTheme } from 'oa-themes'
const theme = preciousPlasticTheme.styles
```

At the moment we are importing the theme object directly and accessing its style properties. We should avoid doing this and instead make use of `sx` property available on all ThemeUI components to load these values out of the theme definition.

Read more about it here: 
> The `sx` prop lets you add any valid CSS to an element, while using values from your theme to keep styles consistent. You can think of the style object that the `sx` prop accepts as a _superset_ of CSS.
https://theme-ui.com/sx-prop

The aim should be for there to be no visual differences. However there may be circumstances where this would introduce better visual consistency across the UI. Feel free to reach out on [Discord ](https://discord.com/channels/586676777334865928/938781727017558018) if you think you have found one of those scenarios.

Here's an example where the same change has been made, although I would call out that this specific file required more work than most 🤗  https://github.com/ONEARMY/community-platform/pull/2282

### PR DESCRIPTION
**Pull request by CDeighton**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

Removes direct usage of the theme object, replacing it with the `Label` component that is used on the signup screen

## Git Issues

Closes #2295

## Screenshots/Videos

Seems to be no visual diff to my eyes -

On master:
Screenshot 2023-06-20 at 10 38 19 PM

After:
Screenshot 2023-06-20 at 10 37 30 PM

### CODE REVIEW

**Review by iSCJT — APPROVED** [review]
Thanks for the contribution @CDeighton.  I agree that the additional styling doesn't seem to be necessary.  Good simplification 👍

**Comment by iSCJT** [comment]
@all-contributors add @CDeighton for code

**Comment by CDeighton** [comment]
@iSCJT apologies if this is a dumb question, but do I leave this one with you to merge? It looks like some of the build steps don't run for me

Screenshot 2023-06-20 at 11 32 43 PM

**Comment by iSCJT** [comment]
> @iSCJT apologies if this is a dumb question, but do I leave this one with you to merge? It looks like some of the build steps don't run for me
> 
> Screenshot 2023-06-20 at 11 32 43 PM

Not a dumb question.  I've approved the changes, our CI workflow sometimes takes a while to kick off all of the necessary steps.  As long as one of them doesn't fail then it will auto-merge when they complete.

**Comment by iSCJT** [comment]
@CDeighton actually maybe there is something else going on, I'll take a look and resolve but don't worry you shouldn't need to do anything.

**Comment by CDeighton** [comment]
@iSCJT awesome, thanks 🙏

**Pull request merged**
