### PR TITLE
fix: used theme specific icons for fixing-fashion

### LINKED ISSUE #1948: [bug] Wrong Icon size on Fixing Fashion Map
**Describe the bug**
The icons on the map of Fixing Fashion are not correct.
The icons shown are for large display size, but they should be for small display size.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://community.fixing.fashion/map
2. See the icons

**Expected behaviour**

1. Space icon should be: 
https://github.com/ONEARMY/community-platform/blob/master/src/assets/images/themes/fixing-fashion/avatar_space.svg

2. Member icon should be: 
https://github.com/ONEARMY/community-platform/blob/master/src/assets/images/themes/fixing-fashion/avatar_member.svg

**Screenshots**
FF-map-icons

**Additional context**
Add any other context about the problem here

### PR DESCRIPTION
**Pull request by asheerrizvi**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Theme specific icons for fixing-fashion

## Git Issues

Closes #1948 

## Screenshots/Videos

image

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by asheerrizvi** [comment]
@davehakkens We don't have all the assets for every theme present, for example precious plastic assets are being used in project kamp as well. If we can have those assets then I can add theme specific checks for each of these assets.

**Comment by davehakkens** [comment]
Hey thanks
I could provide the assets for (kamp) one so we can add the theming for all?
Seems worth it to do it all the way.

Also if i see it correctly running your PR locally 
The icon you use for Precious Plastic is [this one](https://user-images.githubusercontent.com/17976252/194038506-aae9acbb-f5e4-4a0b-85db-bb0475a1f6e5.png)
afbeelding
But it should be this one (without text around it, optimised for small screens)
afbeelding

**Comment by asheerrizvi** [comment]
@davehakkens sure let me have it and I'll add it for all 😃

**Comment by asheerrizvi** [comment]
@davehakkens can you check now? Let me know if you need any changes.

**Comment by davehakkens** [comment]
Nice. Just curious how do you test this one with all the different themes, locally?
Annd looks like a test is failing @asheerrizvi?

**Comment by asheerrizvi** [comment]
Hey @davehakkens, used this theme select element to switch themes on local:

image

I'll check out the test tomorrow I suppose.

**Comment by davehakkens** [comment]
any luck on the test @asheerrizvi?

**Comment by asheerrizvi** [comment]
Hey @davehakkens, I'll push it tomorrow. Was a bit busy these last few days.

**Comment by asheerrizvi** [comment]
@davehakkens I have fixed the tests. However, I think we will need verified member assets for each theme as well. Currently for verified member the only asset we have is based on Precious Plastic member icon. Should we do it now only or come back to it later?

image

**Comment by davehakkens** [comment]
We won't have verified members @asheerrizvi, it's only for spaces.
We might have a verified FF and PK Space. But not anytime soon.
So we could also leave it like this for now and add those later.

**Comment by asheerrizvi** [comment]
@davehakkens cool, can you have a look and see if this can be merged?

**Comment by davehakkens** [comment]
This one is hard to test locally because it contains different themes and some element can only be loaded if the data is there. For instance a Fixing Fashion Space and Project Kamp member dont exist in our dev database or emulator.

For now i'll merge it so it gets deloyed to all the devsites and we can test it!
Which means it might become an iterative proces, hope thats ok :)

**Review by davehakkens — APPROVED** [review]

**Comment by asheerrizvi** [comment]
@davehakkens yep, no worries. It was difficult for me to test on local as well. Let me know if anything seems out of ordinary.

**Comment by davehakkens** [comment]
Hmm seems to fail when deploying to all 3 instances.
https://app.circleci.com/pipelines/github/ONEARMY/community-platform/3211/workflows/78509865-77a1-488b-9538-00e2fb3cb62c

 [error](https://circleci.com/api/v1.1/project/github/ONEARMY/community-platform/19991/output/110/0?file=true&allocation-id=6353000f1b60351ff87d5e7f-0-build%2F444125F6) here
afbeelding

**Comment by asheerrizvi** [comment]
@davehakkens not sure why it is erroring out for these two files. Building and serving it locally seems to work also the deploy previews were working earlier in the PR :/

**Comment by asheerrizvi** [comment]
I can also try importing this using a relative path but I am not sure why is this causing an error for these two files only while `PlatformTheme` has been imported in a similar manner in other files like `Sprites.tsx`, `Workspace.tsx` etc.

**Comment by davehakkens** [comment]
Got some info for you on this @asheerrizvi 
These are the relevant error messages:
```
ERROR in /home/circleci/project/src/modules/profile/index.ts
[tsl] ERROR in /home/circleci/project/src/modules/profile/index.ts(3,36)
      TS2307: Cannot find module 'src/themes/types' or its corresponding type declarations.
```
```
ERROR in /home/circleci/project/src/modules/profile/SupportedProfileTypesFactory.ts
[tsl] ERROR in /home/circleci/project/src/modules/profile/SupportedProfileTypesFactory.ts(19,36)
      TS2307: Cannot find module 'src/themes/types' or its corresponding type declarations.
```

The issue here is taking place during the build process for the serverless functions. It looks like the changes you have introduced here have changed the dependency tree which is no resulting in broken tests.

You should be able to run `yarn workspace functions build `to recreate the behaviour which is breaking in CI. This will help to determine the source of this breakage

**Comment by asheerrizvi** [comment]
@davehakkens awesome, was able to fix it with this. Here's the PR: #1993 

Some things to note:

- Moved all profile related imports to the `..profile/types` file
- Updated all files which were importing these types from `..profile/index.tsx` to import them from `..profile/types` file.

**Comment by davehakkens** [comment]
cool thanks for the changes. Let's see 🤞

**Comment by davehakkens** [comment]
Just tested on devsites.
In case you ever need them
PP = https://dev.onearmy.world
PK = https://dev.community.projectkamp.com
FF = https://dev.community.fixing.fashion

Works all good, thanks a lot for the cleanup @asheerrizvi

**Comment by davehakkens** [comment]
Found a little bug on this one. in [profile/settings](https://dev.onearmy.world/settings)
The member icon is wrong in this overview.
It shows the small, not large one.
afbeelding

**Comment by asheerrizvi** [comment]
@davehakkens got you. Will push a fix tomorrow.

**Comment by davehakkens** [comment]
little reminder on this @asheerrizvi
Bug is still there

**Comment by asheerrizvi** [comment]
@davehakkens ahh slipped my mind. Here you go: https://github.com/ONEARMY/community-platform/pull/2003

**Pull request merged**
