### PR TITLE
Feat/howtos search

### LINKED ISSUE #3455: [Howtos] Improve search
Refactor the Howtos search, same as the work done for Questions and Research.

Will improve: #3239
Requirement for: https://github.com/ONEARMY/community-platform/discussions/1646

### PR DESCRIPTION
**Pull request by mariojsnunes**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

Changes:

- Refactors research search to query firestore.
- Displays only 12 howtos per page.
- The author filter was removed as it required creating a new collection to keep track of research authors (same was done for research, discussed with Dave).
- The author username is now added to searchable keywords so we still allow filtering by author (updated user statistics link).

This PR requires a migration before merging.

## Git Issues

Closes #3455

### CODE REVIEW

**Review by benfurber — APPROVED** [review]

**Comment by benfurber** [comment]
@mariojsnunes YES!

Unit test failure if you haven't seen yet:
```
AssertionError: expected '/how-to?q=Test User' to be '/how-to?author=Test User' // Object.is equality
 ❯ src/UserStatistics/UserStatistics.test.tsx:35:44

**Comment by davehakkens** [comment]
Looks nice!
Just double checking. Not all filters in dropdown work but I assume this will work when using the migrated data?
afbeelding

**Comment by davehakkens** [comment]
@benfurber  cant test further. The preview link doesnt load how-tos anymore

**Comment by mariojsnunes** [comment]
> @benfurber cant test further. The preview link doesnt load how-tos anymore

This PR creates indexes on firestore that are required for search to work. Likely there was another deploy that has overridden the indexes. I'm deployed them again now :)

**Comment by mariojsnunes** [comment]
>Not all filters in dropdown work but I assume this will work when using the migrated data? 

Found the issue, all filters should be working now, thanks!

> Not for this PR but there's definitely a UI issue for me around ordering by filters you don't see, e.g. by comments

I've added comment and download counters to the howto cards, should fix that UI issue.

I still want to review search unit tests. But should be pretty much finished.

**Comment by davehakkens** [comment]
Works now

> I've added comment and download counters to the howto cards, should fix that UI issue.

Thanks for adding them but I think this needs a bit more thinking.
- Most how-to don't have any files attached
- Some of the top how-to's have 5 diget downloads. Which would break the UI.

Proposal.
- We remove download counts for now
- We leave comments. But is there an option to hide if 0 (to keep the same behaviour as useful count and many have none)

**Comment by mariojsnunes** [comment]
> * We remove download counts for now

Ok removed the download count from the card. But keep the sort option right?

> * We leave comments. B̶u̶t̶ ̶i̶s̶ ̶t̶h̶e̶r̶e̶ ̶a̶n̶ ̶o̶p̶t̶i̶o̶n̶ ̶t̶o̶ ̶h̶i̶d̶e̶ ̶i̶f̶ ̶0̶ ̶(̶t̶o̶ ̶k̶e̶e̶p̶ ̶t̶h̶e̶ ̶s̶a̶m̶e̶ ̶b̶e̶h̶a̶v̶i̶o̶u̶r̶ ̶a̶s̶ ̶u̶s̶e̶f̶u̶l̶ ̶c̶o̶u̶n̶t̶ ̶a̶n̶d̶ ̶m̶a̶n̶y̶ ̶h̶a̶v̶e̶ ̶n̶o̶n̶e̶)̶ **Edit: I see you already changed this behaviour for useful as well. (dont hide if 0) Happy to keep what you've already made.**

You mean hide the card or the icon? If it's the card, it's just an effect of the new search.

**Comment by davehakkens** [comment]
Just the icon+number to avoid visual clutter. But we can leave it how you made it now. Might encourage people to leave some comments if 0

**Pull request merged**
