### PR TITLE
fix: roles required checked in dev view correctly

### PR DESCRIPTION
**Pull request by AlfonsoGhislieri**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

The authwrapper was not correctly working in DEV view because it was not setup to check through an array of required roles.

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by thisislawatts** [comment]
Sorry for missing this @AlfonsoGhislieri, can we introduce tests that verify the desired behaviour? Let me know if you are pushed for time. I am happy to pick this up if needed.

**Comment by AlfonsoGhislieri** [comment]
No worries at all @thisislawatts, I also missed it during the review.. Time is definitely little scarce right now, so yeah if you can jump on this that would be great! I appreciate it, thanks :)

**Comment by thisislawatts** [comment]
Sure thing, I can pick this up next week.

**Comment by evakill** [comment]
@AlfonsoGhislieri @thisislawatts should we go ahead and push this in if it's still an active bug?

**Review by evakill — APPROVED** [review]

**Comment by evakill** [comment]
this has been blocking devs from testing so going to merge in

**Pull request merged**
