### PR TITLE
feat: add cta to log in to research comments section for logged-out

### LINKED ISSUE #1591: [bug] Add CTA to log in to Research Comments section for logged-out users
**Describe the bug**
This was a miss in my designs of the [Research Comments in Figma](https://www.figma.com/file/nPDwFo0Ee4wcHvtnEGtAu9/ONE-ARMY-Community-Platform?node-id=10%3A72) that was caught by @davehakkens.

The How-To comments on pages like [this one on Precious Plastic](https://community.preciousplastic.com/how-to/easily-hands-free-connect-moulds-to-the-injector) have a section that appears if the user is not signed in, which looks like a fake comment prompt (which is not editable as a text field) that contains a link to log in. The Comment button is disabled and set to 50% opacity as well. We should add this section to the Research Comments component to not confuse users who are not logged in and want to comment.

**To Reproduce**

1. Visit https://community.projectkamp.com/research as a logged-out user
2. Locate a Research module with comments (unsure if there is one currently, the test with comments was deleted).
3. Note how there is no clear way to comment, or reminder that you can't comment until logging in.

**Expected behavior**
Using a modified version of the comment prompt to invite the user to log in.

**Screenshots**
Here is a [link to the full design of this page](https://www.figma.com/file/nPDwFo0Ee4wcHvtnEGtAu9/ONE-ARMY-Community-Platform?node-id=208%3A814), but this is a close-up of the element we want to add to the component:
Screen Shot 2022-04-04 at 10 12 09 PM

Here is what it looks like on [a Precious Plastic How-To](https://community.preciousplastic.com/how-to/easily-hands-free-connect-moulds-to-the-injector):
image

### PR DESCRIPTION
**Pull request by jojudre**
…sers

PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)

## Description

Add CTA to log in to Research Comments section for logged-out users

## Git Issues

Closes #1591

## Screenshots/Videos

Снимок экрана 2022-04-05 в 14 48 43

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on slack in the `platform-dev` channel.

### CODE REVIEW

**Comment by davehakkens** [comment]
Nice one. Little note (which I realised is not in the Issue)
Would it be possible to always show the "Start a discussion" button. So also for non logged in users.
If they click the button they see the "hey there, login to leave a comment" from this PR you created

Like this:
comment_button

**Comment by jojudre** [comment]
@davehakkens yes, will fix) if it was in the design at the beginning, it would be even easier)

**Comment by davehakkens** [comment]
looks perfect now. Thanks a lot!

**Review by thisislawatts — APPROVED** [review]

**Pull request merged**
