### PR TITLE
fix: nested anchor tags in ResearchListItem

### LINKED ISSUE #3278: [bug] Research Listing page
**Describe the bug**

When viewing the Research listing page locally, http://localhost:3000/research, the browser console includes the following error message. 

```
 at a
    at LinkWithRef (http://localhost:3000/static/js/bundle.js:200471:7)
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Link
    at InternalLink (http://localhost:3000/static/js/bundle.js:225523:21)
    at Username (http://localhost:3000/static/js/bundle.js:227672:21)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Grid (http://localhost:3000/static/js/bundle.js:108137:20)
    at a
    at LinkWithRef (http://localhost:3000/static/js/bundle.js:200471:7)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Card
    at ResearchListItem (http://localhost:3000/static/js/ResearchList.chunk.js:236:5)
    at observerComponent (http://localhost:3000/static/js/bundle.js:159967:69)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:201749:5)
    at Routes (http://localhost:3000/static/js/bundle.js:202370:5)
    at Suspense
    at routes
    at ResearchModuleContainer (http://localhost:3000/static/js/bundle.js:18281:76)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at Main (http://localhost:3000/static/js/bundle.js:20789:5)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:201749:5)
    at Routes (http://localhost:3000/static/js/bundle.js:202370:5)
    at Suspense
    at Router (http://localhost:3000/static/js/bundle.js:202308:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:200359:5)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at Pages
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:15141:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:27979:64)
    at Provider (http://localhost:3000/static/js/bundle.js:160993:24)
    at observerComponent (http://localhost:3000/static/js/bundle.js:159967:69)
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Start the local development server for the application.
2. Navigate to the Research listing page by going to http://localhost:3000/research.
3. Open the browser's developer tools to access the console.

**Expected behaviour**
The Research listing page should load without any JavaScript errors in the console. All components on the page should function correctly, including links, layouts (grids, flexboxes), and any custom components like ResearchListItem.

### PR DESCRIPTION
**Pull request by kimskovhusandersen**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description
- Fixed the nested anchor tag issue by placing the main link around the title inside the `<h2>` tag inside each card, following the pseudo-content approach recommended in  [Inclusive Components](https://inclusive-components.design/cards/).
- Additionally, wrapped the list of cards in a `<ul>` element and set the as property of each card to `li` to improve accessibility.

## Git Issues

Closes #3278 

## Screenshots/Videos

Screenshot 2024-07-07 at 21 14 45

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Review by benfurber — CHANGES_REQUESTED** [review]
Thanks for picking this up @kimskovhusandersen. It's been annoying for ages! And thanks for trying to set it up in a more semantic/accessible way. Broad feedback before a line-by-line review.

Please fix:
1. I think you've created a UI regression. The `IconCountWithTooltip`s should align to the right especially on desktop (probably align self to flex end and have the middle column (with the title) to expand to fill the space (maybe just with flex: 1?). 
2. When uses basic components from `theme-ui` we try to stay away from styled components these days (though I did use it in a recent PR(!)) and put all styling into the sx prop for a theme-ui component - this approach isn't event consistent on the file atm but I would like it.

Would prefer you changes:
1. Is using `Grid` rather than nested `Flex` helping or hurting us do you think?
2. I believe on `QuestionListItem` I setup the responsiveness in a way that avoids having mobile specific layouts. Do you think that's possible here too?
 
Bonus points for a follow-up PR:

There's probably some styling/basic layout duplication between `ResearchListItem` and `QuestionListItem`. Could be worth tidying up into a component for the component library?

**Comment by benfurber** [comment]
@davehakkens This adds a little hover effect on the list item as a whole. I think it's nice interaction to add, wanted to check you noticed and were OK with it. 

https://github.com/ONEARMY/community-platform/assets/16688508/b0d5504e-3ff1-42aa-895f-9ccb261c7bcf

**Comment by davehakkens** [comment]
> @davehakkens This adds a little hover effect on the list item as a whole. I think it's nice interaction to add, wanted to check you noticed and were OK with it.

Keep it for a different issue/PR so we can align it on all modules?

**Comment by kimskovhusandersen** [comment]
> Thanks for picking this up @kimskovhusandersen. It's been annoying for ages! And thanks for trying to set it up in a more semantic/accessible way. Broad feedback before a line-by-line review.
> 
> Please fix:
> 
> 1. I think you've created a UI regression. The `IconCountWithTooltip`s should align to the right especially on desktop (probably align self to flex end and have the middle column (with the title) to expand to fill the space (maybe just with flex: 1?).
> 2. When uses basic components from `theme-ui` we try to stay away from styled components these days (though I did use it in a recent PR(!)) and put all styling into the sx prop for a theme-ui component - this approach isn't event consistent on the file atm but I would like it.
> 
> Would prefer you changes:
> 
> 1. Is using `Grid` rather than nested `Flex` helping or hurting us do you think?
> 2. I believe on `QuestionListItem` I setup the responsiveness in a way that avoids having mobile specific layouts. Do you think that's possible here too?
> 
> Bonus points for a follow-up PR:
> 
> There's probably some styling/basic layout duplication between `ResearchListItem` and `QuestionListItem`. Could be worth tidying up into a component for the component library?

Hi @benfurber,

Thanks for your detailed feedback on this update! 👍 

- I've fixed the adjustment of the IconCountWithTooltips to align to the right as you mentioned.
- I swapped out the StyledLink for an InternalLink. Since we only had an ExternalLink component and using Link from theme-ui directly led to a lint error—plus, the Link from react-router-dom doesn't support pseudo-classes in its style object—I wrapped a react-router-dom Link in a theme-ui Link component to use pseudo-classes. I've used this component in the QuestionListItem as well to keep things consistent.
- For this PR, I decided to continue using the Grid component in ResearchListItem due to its complexity and to avoid potential regression issues. However, I agree that there might be a better approach. I can take a look at the possibility of abstracting common elements between ResearchListItem and QuestionListItem into a reusable component in a follow-up PR :-)
- Additionally, I removed the hover styling, as I noticed that you'd prefer to address this in a separate PR as well.

I hope this works with you and I'm looking forward to your thoughts on these adjustments!

**Comment by benfurber** [comment]
Awesome. Looks good to me, @kimskovhusandersen. Thank you.

For the follow-up, the reason I think grid might be in our way in this instance is this issue at a viewpoint nearing tablet. To be clear you didn't create this issue, I've just been ignoring it.

Screenshot 2024-07-09 at 08 17 27

(@davehakkens if you have time to double check the display today. I'll merge in towards the end of the day.)

**Comment by benfurber** [comment]
@davehakkens Yes, that was what I was looking for thank you. I think the display around that breakpoint are bad but hard for me to prioritise as I doubt it impacts many users. ...Which why it's great @kimskovhusandersen is looking around this stuff atm! :)

**Pull request merged**
