### PR TITLE
feat: member map pins

### LINKED ISSUE #1362: Add "Want to get started" to map.
### Description
At the moment Workspace profiles can add a pin to the map to display their workspace. 
Member profiles cannot add a pin to the map.

This new feature would allow members (everyone) to create a "want to get started" pin on the map

### Pages
https://community.preciousplastic.com/settings
https://community.preciousplastic.com/map

### Related to
This is related to PR https://github.com/ONEARMY/community-platform/pull/1267 that will simplify member profiles. This will also create the function to upload an avatar for members.

### Function
📍 Add yourself to the map > Country flag is shown in profile and name
╳ If not added to the map > No Country flag is shown in profile and name

🇫🇮🏴󠁧󠁢󠁥󠁮󠁧󠁿🇧🇯🇬🇶🇱🇻 This would be fun/useful so you know that every user with a flag is on the map 

### Mockup

**How to add a pin:**
afbeelding

**How it's shown on the map**
afbeelding

**Where it's shown on the map**
afbeelding

This issue is made as a conversation starter to discuss the best way to build it

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [X] - Latest `master` branch merged
- [X] - PR title descriptive (can be used in release notes)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

📺 A short video demo:
https://www.loom.com/share/da3860de0ee743a5aae4fd723db30deb

The video shows:

1. A member creating a new map pin
2. Saving the profile
3. Pin being available straight away on the Map **without** any moderation step required

**Please note:** 
The component which captures the User's location has been completely rebuilt and now:
1. Does not have a dependency on Algolia Places, instead we are using the OSM API as [suggested by](https://github.com/ONEARMY/community-platform/issues/1177#issuecomment-995983535) @kfern
1. The Marker can be dragged around if needed to fine tune the exact position.

Closes #1362 

Default appearance of the pane, the user is prompted to `Add a map pin`

Screenshot 2022-01-02 at 13 39 55

When clicking `Add a map pin` the user is then presented with an empty description field and map

Screenshot 2022-01-02 at 13 40 14

The component once a user has specified a description and location. 

Screenshot 2022-01-02 at 13 42 09

### CODE REVIEW

**Comment by davehakkens** [comment]
Wauw works very nice! 
1. Nice default appearance in the profile
1. Would you envision the same OSM API used on the main map search? 
2. My original account was an `Extrusion workspace` I've changed the account to `member` to make a "want to get started pin" The pin shows up, but it's still categorized as an `extrusion workspace` Caching?
afbeelding
afbeelding

**Comment by thisislawatts** [comment]
2. Would you envision the same OSM API used on the main map search?

Absolutely, we could either use the OSM API _or_ search for our map pins for any that match the queried location. 

3. My original account was an Extrusion workspace I've changed the account to member to make a "want to get started pin" The pin shows up, but it's still categorized as an extrusion workspace Caching?

Good catch, this is definitely a flow which I did not run through locally. I will take a look, get some tests around this 🐛 and then fix.

**Comment by davehakkens** [comment]
Another little bug. 
Country flag seems to be gone after the map change. On both `member` and original `workspace` profile
afbeelding

afbeelding

**Comment by davehakkens** [comment]
Not sure if it was intended. But this is actually quite a nice fix for this issue https://github.com/ONEARMY/community-platform/issues/1155 as well
afbeelding

**Comment by thisislawatts** [comment]
> Not sure if it was intended. But this is actually quite a nice fix for this issue #1155 as well
>
> afbeelding

Yes @davehakkens, I added _View on map_ as a fallback but we shouldn't need it all that often.

The new OSM API powered mechanism for generating Location data has be limited down to a single language with: `accept-language=en`
https://github.com/ONEARMY/community-platform/pull/1365/files#diff-777873ae5fb42cece21e6af1347582045f2955fd0ae23244773becf8673d3a8dR305

**Comment by thisislawatts** [comment]
@davehakkens fixed the other two issues flagged in your feedback. Thanks for playing the Sunday Bug Hunt 🔍 🐛

**Comment by davehakkens** [comment]
Perfect, even better! Thank you for the fast coding!🔥🔥🔥

**Comment by thisislawatts** [comment]
@davehakkens following on from the call yesterday, I have now removed the location field from the profile settings. 

Let me know if there's anything else you would like addressed. Otherwise I think this is good to go 🚀

**Comment by davehakkens** [comment]
Asked around. everyone actually loves to have it in PP community.
Got 1 remark before release.
We don't have DM in the Platform (yet) So we depend on people listing their **Contacts & links**
This is a mandatory field and also contains `Discord` and `forums`. 
However this is a bit useless since it's very complex to share your Discord ID and our old forums are hard to access.

In Short:
If we remove `Discord` and `Forums` from the profile Contact & Links settings it's good to go!
afbeelding


Edit: I see a bunch of ❌❌❌ up their. 👆 
You sure it's good to go?

**Comment by thisislawatts** [comment]
@davehakkens thanks, I will take a closer look at those failing tests. :eyes:

**Comment by thisislawatts** [comment]
All tests passing. I've raised a separate PR to remove the Discord/Forum links
https://github.com/ONEARMY/community-platform/pull/1368

**Review by davehakkens — APPROVED** [review]
awesome

**Pull request merged**
