### PR TITLE
feat: updates design of 404 page

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [X] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Git Issues

Closes https://github.com/ONEARMY/community-platform/issues/1863

## Screenshots/Videos

Screenshot 2022-09-14 at 22 13 43
Screenshot 2022-09-14 at 22 14 11

### CODE REVIEW

**Comment by thisislawatts** [comment]
Replaces #1881

**Comment by thisislawatts** [comment]
@thisismattia, can you take a look at https://onearmy-next--pr1924-error-page-p7l6e0ay.web.app/abc123 and let me know if you've got any feedback on the implementation? Otherwise I think we're ready to :shipit:

**Comment by thisismattia** [comment]
Thanks @thisislawatts sorry it slipped my mind. 
Couple of comments for @pkpndy 

1. Image should ideally be centered vertically and horizontally 
2. Text has style="margin-bottom: 2em;" which is very large, could you please remove the margin?
image

Thanks

**Comment by thisislawatts** [comment]
Updated @thisismattia, please take another look. New behaviour is to center the content within the available viewport. Attached screengrab demonstrates this at ~3,000 pixel wide.

**Comment by thisismattia** [comment]
Brilliant thanks!
Good to go for me :)

**Pull request merged**
