### PR TITLE
bug: setting as draft a published research does not reset the total comment count

### LINKED ISSUE #3905: [bug] Research article's total comments count is reset to 0 after being set to Draft or Republished
**Describe the bug**
Editing or setting as draft a research reset its total comments count to 0

Example of this issue on on PRD:
[Should we get a tractor or digger to work on the land?](https://community.projectkamp.com/research/should-we-get-a-tractor-or-digger-to-work-on-the-land)

**To Reproduce**

- create a research
- create an update
- add comments to update -> the comments total count is correctly updated
- set the research as draft or publish it again -> the comments total count is set to 0

**Expected behaviour**
The research article's total comment count should not be reset

**Screenshots**
image

### PR DESCRIPTION
**Pull request by onim-at**
## PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ ] - Unit and e2e tests for the changes that have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix (fixes an issue)
- [ ] Feature (adds functionality)
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation changes
- [ ] Other... Please describe:

## What is the current behavior?
Re publishing or updating a research reset its total comments count to 0

## What is the new behavior?
The total comments count is not reset on Publish/Draft

Note: this PR does not fix the researches already affected by the bug. The correct count value will be displayed when a new comment or update is posted

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Git Issues

Closes #3905

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the month)

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by mariojsnunes** [comment]
I wonder if it would be best to not define `totalCommentCount` so it won't change the database value at all.

**Comment by onim-at** [comment]
@mariojsnunes good point! I'll update the PR

**Comment by mariojsnunes** [comment]
thanks @onim-at! Do you confirm it doesn't cause the bug anymore?

**Comment by onim-at** [comment]
@mariojsnunes sorry for the late reply, yes, I've double checked it locally and it works well

**Pull request merged**
