### PR TITLE
fix: try fix edit question

### LINKED ISSUE #3362: [bug] ActiveUser randomly cleared on Questions page
**Describe the bug**
For some reason, when you're on one of your own Question pages and refresh the page, the activeUser is cleared and so the edit button disappears.

**To Reproduce**
Steps to reproduce the behaviour:

1. Make question.
2. View it (see the edit button).
3. Refresh the page (see the edit button has gone).
4. Go to any other page.
5. Click forward to the question page (see the edit button is back).

This doesn't seem to happen on any other content types (e.g. How tos).

### PR DESCRIPTION
**Pull request by mariojsnunes**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Workaround for checking question edit permissions. Unsure if this solves the issue as I couldn't replicate.
@benfurber could you take a look?

## Git Issues

Closes  #3362

### CODE REVIEW

**Comment by benfurber** [comment]
@mariojsnunes I can replicate it as far back in the history as `15ca598519479afccb15d2c3adb8527475f4b539` but it looks like I fixed it in #3261... which is weird because that's when I was working on when I thought I'd found the bug!

Sorry for wasting your time.

Do you think we should merge this branch in or leave it? The use of memo is probably better.

**Review by benfurber — APPROVED** [review]

**Comment by mariojsnunes** [comment]
No worries. I think it's better to leave it. The use memo isn't doing anything then.

**Comment by benfurber** [comment]
@mariojsnunes I just recreated the problem again on prod. Reopening this for the moment.

**Comment by benfurber** [comment]
Oh no! Can't reopen as the branch is deleted now!

**Pull request closed without merging**
