### PR TITLE
docs: add initial design contribution docs

### PR DESCRIPTION
**Pull request by franknoirot**
PR Checklist

- [x] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [x] - Latest `master` branch merged

PR Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Developer experience (improves developer workflows for contributing to the project)

## Description

Adding initial design contribution documentation. Would like to add a "How to use designs as a developer" doc in the future.

### CODE REVIEW

**Comment by davehakkens** [comment]
Nice one! Looks complete. Are you still planning to add images?
Looking forward to see how this gets used.

**Comment by franknoirot** [comment]
Ah @davehakkens I forgot images! I'll add them now then request another review

**Comment by franknoirot** [comment]
@davehakkens I've added images to the contributing feedback doc, ready for your review.

**Comment by davehakkens** [comment]
nice!  Did you also see these comments? -i'm doubting because it says "pending"

afbeelding

**Comment by franknoirot** [comment]
Oh sorry @davehakkens I don't think I see those until you submit them as a review! There should be a button to submit all your comments as a review and select "request additional changes" I think. Sorry I missed some Slack references I'll fix them

**Review by davehakkens — APPROVED** [review]
perfect!

**Comment by franknoirot** [comment]
@thisislawatts sorry I don't understand out to get my "Lint commits" check to pass, I don't understand what I'm doing wrong here.

**Comment by thisislawatts** [comment]
Thanks for the feedback @franknoirot. Looking at the commits there were a few issues:

* One of of them was missing a `fix:` prefix.
* Another was `fix: Remove …`, where as the expected style would be `fix: remove …`

I have squashed all of the commits into a single message.

It would be great to figure out how we could make these errors easier to debug. Were you able to [find the failure output in CircleCI](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/2150/workflows/6d91aa9e-30b2-4ae3-9024-6ee09ad94bb7/jobs/11795)? If so, was there anything we could change about the message to make it easier to understand.

**Comment by franknoirot** [comment]
Thanks so much @thisislawatts. I don't think it's really any issue with the checks just my novice understanding of Git workflows. Yeah I read that error message "subject must not be sentence-case, start-case, pascal-case, upper-case", and didn't connect that "subject" was the same thing as "description" in the example conventional commit message "<type>[optional scope]: <description>", definitely should have been able to make that connection.

The other issue that I don't think I would have solved on my own is that I needed to squash the commits. What I tried to do was use `git commit --amend` to correct my commit message, but I think that actually just made a couple new commits and the checks kept failing.

**Pull request merged**
