### PR TITLE
fix (#2017): AdminTag label loosing focus on every input change

### LINKED ISSUE #2017: [bug] Inputs for adding tags and categories re-render on each key stroke
**Describe the bug**
The inputs for adding a tag and adding a category are somewhat broken. These inputs re-render on each keystroke and thereby makes the input go out of focus on each such action.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the Admin panel.
2. Click on Tags Admin or Categories Admin.
3. Trying adding a tag or a category
4. See the behaviour by typing the tag or the category name.

**Expected behaviour**
Inputs should not re-render on each key stroke and the user is able to type without losing focus.

**Screenshots**

https://user-images.githubusercontent.com/17976252/205485688-72d04442-ba36-4d8d-814f-20c55f9ee1cf.mov

**Additional context**

### PR DESCRIPTION
**Pull request by cerkiewny**
PR Checklist

- [ ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)

PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Developer experience (improves developer workflows for contributing to the project)

## Description

Add an autofocus property to input label in admin tag editor

## Git Issues

Closes #2017

## Screenshots/Videos

---

## What happens next?

Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to all!).

If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once updated.

If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/938781727017558018).

### CODE REVIEW

**Comment by cerkiewny** [comment]
Ugh, wrong commit, give me few minutes to amend it, it has something I was testing there that shouldn't be there.

**Comment by chrismclarke** [comment]
I think there might be one more issue with commitlint 😓 
If I can remember right the sentence after the `:` needs to be lower case. I think this is imposed by commitlint itself and goes beyond the conventional commits spec (possibly a config setting somewhere). So if you are able to fix that also that would be great (sorry for all the inconvenience)

**Comment by cerkiewny** [comment]
This is mildly frustrating as the tool itself prevents the amends to commits which are miss formatted so I needed to work around it with git gui instead of cmd line commits. Well, probably just a first time commiter - gotchya.

**Comment by chrismclarke** [comment]
> This is mildly frustrating as the tool itself prevents the amends to commits which are miss formatted so I needed to work around it with git gui instead of cmd line commits. Well, probably just a first time commiter - gotchya.

Agreed - usually malformed commit messages should get notified before commit in the command line or interactive code editor (e.g. vscode), however that depends on the hooks created by husky/yarn triggering correctly which does not always happen (something I've never really been able to get to the bottom of). And also if using web editor or similar they just don't get checked.

One of the things maintainers do is try to help out when this happens, although more often than not I end up just having to abandon the PR and move entirely to another instead because super fiddly editing if there's multiple commits or branch updated with master. So really appreciate you managing to resolve so quickly, hopefully won't cause as much friction in the future

**Review by chrismclarke — APPROVED** [review]
Really nice, simple solution. Can confirm tested and working as expected, many thanks for the fix!

[Admin.webm](https://user-images.githubusercontent.com/10515065/228219496-ae6c1047-1479-4597-ab62-4aca4a1d49a4.webm)

**Comment by thisislawatts** [comment]
@cerkiewny to better understand the issue you were having with amending commits, could you please confirm the command you were attempting to use?

**Comment by cerkiewny** [comment]
As mentioned in discord - once I was able to commit something not adhearing to the community commit message `git commit --amend` wasn't working (it checked the message before amending, not after) and since message didn't adhere to standard I was unable to change it to do so. I got around it by using git gui instead of cmd in the end.

**Pull request merged**
