### PR TITLE
fix: adjust ordering of paths so that auth'd routes take precedent

### PR DESCRIPTION
**Pull request by thisislawatts**
PR Checklist

- [X] - Latest `master` branch merged
- [X] - PR title descriptive (can be used in release notes)

PR Type

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fixes an issue where a user can not edit a Research item, or add an Update to a Research article.

I _think_ it is happening because the paths are being matched from top to bottom, meaning that the `Route` item here is being matched first before the `AuthRoute` wrappers which contains the edit logic.

Steps to recreate:
1. Add new Research item to the site
2. View the new Research item
3. Clicking either the Add Update or Edit button flashes a 404 page before returning to render the Research item

### CODE REVIEW

**Comment by davehakkens** [comment]
it might have to do with the roles we have on the platform.
We are still testing the module so at the moment only users with `Beta tester` Role can use it

**Comment by thisislawatts** [comment]
@davehakkens have you been able to successfully edit an existing Research item? If so, which install was that on?

**Comment by davehakkens** [comment]
yep, edit here: https://dev.community.projectkamp.com/research/make-a-roof-from-recycled-plastic--edit

**Comment by davehakkens** [comment]
FYI. Made you and admin (you can access in the /admin url)

afbeelding

**Comment by thisislawatts** [comment]
:D Some further clarification @davehakkens, this bug fix is **already deployed** to the Project Kamp instance.

So I am wondering if you had seen this edit behaviour working on any of the other Platform instances we have deployed at the moment.

**Comment by davehakkens** [comment]
yeh you are right. I still get a 404 error when I try to edit a research on https://community.preciousplastic.com/research/
sharp.💪

We were aware of the bug though. And I do think @chrismclarke worked on this about a month ago. 
But i guess it never went live because to release was made?
afbeelding

**Comment by thisislawatts** [comment]
@davehakkens, I can still recreate the issue on the install at https://dev.onearmy.world/ which is automatically deployed from the latest code in GitHub's `master` branch. 

@chrismclarke did you get a chance to work on this? I think something we could do with adding here is some kind of test coverage to ensure we don't introduce any regressions here.

**Review by davehakkens — APPROVED** [review]

**Pull request merged**
