### PR TITLE
feat: adding categories

### LINKED ISSUE #1590: Add categories for How-to
### Description

We will introduce categories to the how-to's.
This is needed to better organise them in specific areas.

- Unlike tags a howto's can only be in one category. 
- Categories are moderated by the community managers.
- Categories can be removed and added like the tags.

### Categories on release
- Products
- Moulds
- Machines 
- Guides
- Hacks

### Notes

Categories need to be released to `beta-testers` so the Precious Plastic community managers can organise them first

### Page related

Will be used in :

- [How-to
](https://community.preciousplastic.com/how-to)

### Mockup

Dropdown menu on the homepage
category dropdown

Select category when submitting a how-to
Categories_submit

### PR DESCRIPTION
**Pull request by jojudre**
New feature (non-breaking change which adds functionality)
Closes #1590

### CODE REVIEW

**Comment by jojudre** [comment]
@chrismclarke Hi! if you will have a time, would you look please?

**Comment by chrismclarke** [comment]
Ah, I can see the problem. You correctly added the new category to the `IDexieSchema` object which defines how we keep a cache of server data in the local indexeddb (using [Dexie](https://dexie.org/docs/)), which I had completely forgotten about, but one extra thing is that whenever the dexie schema changes it needs a new version number.

You can see the `DB_CACHE_NUMBER` listed in `src\stores\databaseV2\clients\dexie.tsx`, for convenience it is just the current date (at time of edit), so feel free to change it to `20220428` or similar (as long as it is a number bigger than what it currently is)

Also, before you do that you might want to edit the message on your last commit or rebase so that it passes our [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) lint check (prefixing with a keyword such as `feat: 
adding categories`)

**Comment by thisislawatts** [comment]
@jojudre I've pushed a few commits into this branch to address the failing linting. Do you want to test it out.

**Comment by jojudre** [comment]
@thisislawatts thank you very much! website launched without errors , and i can go further

**Comment by davehakkens** [comment]
Nicee! Looks and works very good here! 
Would be great to merge and test it live on dev site @thisislawatts

**Review by thisislawatts — APPROVED** [review]

**Pull request merged**
